module
public import Mathlib

/-!
# Near-linear cycles and paths in connected vertex-transitive graphs

This is the small statement surface for Theorem 1.1 and its path inputs,
Theorems 3.17 and A.1, from *Lovász conjecture holds asymptotically*
(Bucić, Christoph, Pokrovskiy, Steiner).

For every positive real `ε`, a sufficiently large graph of the indicated kind
has a simple cycle with at least `n^(1-ε)` edges, where `n` is its number of
vertices. The two accompanying path results give the same lower bound for path
edges, implying the paper's path-vertex bounds. The thresholds may depend on
`ε` and are not made explicit.
-/

@[expose] public section


namespace PalomarLovasz

/-- A simple path represented by its list of vertices: consecutive entries are
adjacent and no vertex occurs twice. The empty list is also admitted by this
predicate, but the lower bound in either theorem rules it out when applicable. -/
def IsPathL {V : Type*} (G : SimpleGraph V) (l : List V) : Prop :=
  l.IsChain G.Adj ∧ l.Nodup

/-- The undirected, loopless Cayley graph generated by `S`. Adjacency is the
symmetric, irreflexive closure of `x⁻¹ * y ∈ S`; `S` need not be symmetric. -/
def cay {H : Type*} [Group H] (S : Set H) : SimpleGraph H :=
  SimpleGraph.fromRel (fun x y => x⁻¹ * y ∈ S)

/-- Every pair of vertices is related by a graph automorphism. -/
def VertexTransitive {V : Type*} (X : SimpleGraph V) : Prop :=
  ∀ u v : V, ∃ φ : X ≃g X, φ u = v

/-- The near-linear cycle statement for connected vertex-transitive graphs
(Theorem 1.1). `c.IsCycle` is Mathlib's nontrivial simple closed walk; its
`length` counts cycle edges. -/
theorem vertex_transitive_long_cycle :
    ∀ ε : ℝ, 0 < ε → ∃ n₀ : ℕ, ∀ (V : Type) [Fintype V] (X : SimpleGraph V),
      X.Connected → VertexTransitive X → n₀ ≤ Fintype.card V →
      ∃ (v : V) (c : X.Walk v v), c.IsCycle ∧
        (Fintype.card V : ℝ) ^ (1 - ε) ≤ c.length := by
  sorry

/-- The Cayley-graph specialization of the near-linear cycle theorem. -/
theorem cayley_long_cycle :
    ∀ ε : ℝ, 0 < ε → ∃ n₀ : ℕ, ∀ (H : Type) [Group H] [Finite H] (S : Set H),
      (cay S).Connected → n₀ ≤ Nat.card H →
      ∃ (v : H) (c : (cay S).Walk v v), c.IsCycle ∧
        (Nat.card H : ℝ) ^ (1 - ε) ≤ c.length := by
  sorry

/-- The Cayley-graph path statement corresponding to Theorem 3.17. The bound
counts edges of a simple path, and so is slightly stronger than a bound on its
number of vertices. -/
theorem cayley_long_path :
    ∀ ε : ℝ, 0 < ε → ∃ n₀ : ℕ, ∀ (H : Type) [Group H] [Finite H] (S : Set H),
      (cay S).Connected → n₀ ≤ Nat.card H →
      ∃ l : List H, IsPathL (cay S) l ∧
        (Nat.card H : ℝ) ^ (1 - ε) ≤ (l.length : ℝ) - 1 := by
  sorry

/-- The vertex-transitive path statement corresponding to Theorem A.1. -/
theorem vertex_transitive_long_path :
    ∀ ε : ℝ, 0 < ε → ∃ n₀ : ℕ, ∀ (V : Type) [Fintype V] (X : SimpleGraph V),
      X.Connected → VertexTransitive X → n₀ ≤ Fintype.card V →
      ∃ l : List V, IsPathL X l ∧
        (Fintype.card V : ℝ) ^ (1 - ε) ≤ (l.length : ℝ) - 1 := by
  sorry

end PalomarLovasz
