module
public import RequestProject.BondyLockeMain

/-! Proved counterparts of the declarations in `Challenge.lean`. -/

@[expose] public section


namespace PalomarLovasz

/-- A simple path represented by its list of vertices. -/
def IsPathL {V : Type*} (G : SimpleGraph V) (l : List V) : Prop :=
  l.IsChain G.Adj ∧ l.Nodup

/-- The undirected, loopless Cayley graph generated by `S`. -/
def cay {H : Type*} [Group H] (S : Set H) : SimpleGraph H :=
  SimpleGraph.fromRel (fun x y => x⁻¹ * y ∈ S)

/-- Transitivity of the graph automorphism action on vertices. -/
def VertexTransitive {V : Type*} (X : SimpleGraph V) : Prop :=
  ∀ u v : V, ∃ φ : X ≃g X, φ u = v

theorem vertex_transitive_long_cycle :
    ∀ ε : ℝ, 0 < ε → ∃ n₀ : ℕ, ∀ (V : Type) [Fintype V] (X : SimpleGraph V),
      X.Connected → VertexTransitive X → n₀ ≤ Fintype.card V →
      ∃ (v : V) (c : X.Walk v v), c.IsCycle ∧
        (Fintype.card V : ℝ) ^ (1 - ε) ≤ c.length :=
  Lovasz.vt_long_cycle

theorem cayley_long_cycle :
    ∀ ε : ℝ, 0 < ε → ∃ n₀ : ℕ, ∀ (H : Type) [Group H] [Finite H] (S : Set H),
      (cay S).Connected → n₀ ≤ Nat.card H →
      ∃ (v : H) (c : (cay S).Walk v v), c.IsCycle ∧
        (Nat.card H : ℝ) ^ (1 - ε) ≤ c.length :=
  Lovasz.cayley_long_cycle

theorem cayley_long_path :
    ∀ ε : ℝ, 0 < ε → ∃ n₀ : ℕ, ∀ (H : Type) [Group H] [Finite H] (S : Set H),
      (cay S).Connected → n₀ ≤ Nat.card H →
      ∃ l : List H, IsPathL (cay S) l ∧
        (Nat.card H : ℝ) ^ (1 - ε) ≤ (l.length : ℝ) - 1 :=
  Lovasz.cayley_long_path_unconditional

theorem vertex_transitive_long_path :
    ∀ ε : ℝ, 0 < ε → ∃ n₀ : ℕ, ∀ (V : Type) [Fintype V] (X : SimpleGraph V),
      X.Connected → VertexTransitive X → n₀ ≤ Fintype.card V →
      ∃ l : List V, IsPathL X l ∧
        (Fintype.card V : ℝ) ^ (1 - ε) ≤ (l.length : ℝ) - 1 :=
  Lovasz.vt_long_path_unconditional

end PalomarLovasz
