module
public import RequestProject.BGTGleason

/-!
# Finitary nilpotence modulo the zero-escape subgroup

Let `B` be a strong `K`-approximate group (Definition 7.1 of Breuillard–Green–Tao).  Using the
commutator estimate of Theorem 8.1 (iii) (`escNorm_commutator_le`), left-normed commutators of
elements of small escape norm have geometrically decreasing escape norm.  Since `B` is finite, the
escape norm takes only finitely many values on `B`; so long enough commutators have escape norm
exactly `0`, i.e. they lie in the subgroup `H = {g | ‖g‖_{e,B} = 0}` of
`exists_subgroup_escNorm_eq_zero`.  Hence the subgroup `Γ` generated by the elements of small
escape norm is nilpotent modulo `H` (`exists_lcs_le_zeroEsc`).

Together with the Sanders–Croot–Sisask theorem (`sanders_small_neighbourhoods`) this gives a
uniformly large approximate group `S ⊆ B⁴` inside `Γ` (`finite_nilpotent_mod_zeroEsc`).

**Warning.** The nilpotency class `j` obtained here depends on the minimum positive escape norm on
the finite set `B`, hence on the particular group, and is *not* bounded in terms of `K` alone.

The file also proves the general group-theoretic fact used for the conclusion:
`lcs_le_normalClosure_leftComm`, the `j`-th term of the lower central series of a group generated
by `T` is the normal closure of the left-normed commutators of weight `j + 1` in letters from `T`
(one inclusion, which is all that is needed).
-/

@[expose] public section

open scoped Pointwise
open scoped commutatorElement

namespace Lovasz.BGT

section LeftComm

variable {K : Type*} [Group K]

/-- Left-normed commutators `⁅⋯⁅⁅t₀, t₁⁆, t₂⁆, …, t_j⁆` of weight `j + 1` with all `tᵢ ∈ T`. -/
def leftComm (T : Set K) : ℕ → Set K
  | 0 => T
  | j + 1 => {g | ∃ x ∈ leftComm T j, ∃ t ∈ T, g = ⁅x, t⁆}

/-- If `T` generates `K`, then `γ_j(K)` lies in the normal closure of the left-normed commutators
of weight `j + 1` in letters from `T`. -/
theorem lcs_le_normalClosure_leftComm (T : Set K) (hT : Subgroup.closure T = ⊤) :
    ∀ j, (⊤ : Subgroup K).lowerCentralSeries j ≤ Subgroup.normalClosure (leftComm T j) := by
  intro j
  induction j with
  | zero =>
    rw [lowerCentralSeries_zero, ← hT]
    exact Subgroup.closure_le_normalClosure
  | succ j ih =>
    set M := Subgroup.normalClosure (leftComm T (j + 1))
    set π := QuotientGroup.mk' M
    have hcen : Subgroup.normalClosure (leftComm T j) ≤ (Subgroup.center (K ⧸ M)).comap π := by
      apply Subgroup.normalClosure_le_normal
      intro x hx
      rw [SetLike.mem_coe, Subgroup.mem_comap, Subgroup.mem_center_iff]
      intro g
      have hg : g ∈ Subgroup.closure (π '' T) := by
        rw [← MonoidHom.map_closure, hT,
          Subgroup.map_top_of_surjective π (QuotientGroup.mk'_surjective M)]
        trivial
      have hle : Subgroup.closure (π '' T) ≤ Subgroup.centralizer {π x} := by
        rw [Subgroup.closure_le]
        rintro _ ⟨t, ht, rfl⟩
        rw [SetLike.mem_coe, Subgroup.mem_centralizer_singleton_iff]
        have hm : ⁅x, t⁆ ∈ M := Subgroup.subset_normalClosure ⟨x, hx, t, ht, rfl⟩
        have h1 : π ⁅x, t⁆ = 1 := (QuotientGroup.eq_one_iff _).2 hm
        rw [map_commutatorElement, commutatorElement_eq_one_iff_mul_comm] at h1
        exact h1.symm
      have := hle hg
      rw [Subgroup.mem_centralizer_singleton_iff] at this
      exact this
    rw [Subgroup.lowerCentralSeries_succ, Subgroup.commutator_le]
    intro p hp q _
    have hpc := hcen (ih hp)
    rw [Subgroup.mem_comap, Subgroup.mem_center_iff] at hpc
    show p * q * p⁻¹ * q⁻¹ ∈ M
    rw [← QuotientGroup.eq_one_iff]
    have := hpc (π q)
    simp only [π, QuotientGroup.mk'_apply] at this
    simp only [QuotientGroup.mk_mul, QuotientGroup.mk_inv]
    rw [← this]; group

/-- If `T` generates `K` and all left-normed commutators of weight `j + 1` in letters from `T`
lie in a normal subgroup `N`, then `γ_j(K) ≤ N`, i.e. `K/N` is nilpotent of class at most `j`. -/
theorem lcs_le_of_leftComm_subset (T : Set K) (hT : Subgroup.closure T = ⊤) (N : Subgroup K)
    [N.Normal] (j : ℕ) (h : leftComm T j ⊆ N) :
    (⊤ : Subgroup K).lowerCentralSeries j ≤ N :=
  (lcs_le_normalClosure_leftComm T hT j).trans (Subgroup.normalClosure_le_normal h)

end LeftComm

variable {G : Type*} [Group G]

/-- On a finite set containing `1`, the positive values of the escape norm are bounded below. -/
lemma exists_escNorm_gap {B : Set G} (hBf : B.Finite) (h1 : (1 : G) ∈ B) :
    ∃ μ : ℝ, 0 < μ ∧ ∀ b ∈ B, escNorm B b = 0 ∨ μ ≤ escNorm B b := by
  classical
  set F := hBf.toFinset.filter (fun b => 0 < escNorm B b)
  by_cases hF : F.Nonempty
  · obtain ⟨b0, hb0, hmin⟩ := F.exists_min_image (escNorm B) hF
    refine ⟨escNorm B b0, (Finset.mem_filter.1 hb0).2, fun b hb => ?_⟩
    by_cases h : 0 < escNorm B b
    · right; exact hmin b (Finset.mem_filter.2 ⟨hBf.mem_toFinset.2 hb, h⟩)
    · left; exact le_antisymm (not_lt.1 h) (escNorm_nonneg h1)
  · refine ⟨1, one_pos, fun b hb => Or.inl ?_⟩
    by_contra h
    exact hF ⟨b, Finset.mem_filter.2 ⟨hBf.mem_toFinset.2 hb,
      lt_of_le_of_ne (escNorm_nonneg h1) (Ne.symm h)⟩⟩

/-- **Finitary nilpotence modulo the zero-escape subgroup.**  Let `B` be a strong `K`-approximate
group and `0 ≤ δ < 1` with `10²⁷ K⁹ δ ≤ 1/2`.  Let `Γ` be the subgroup generated by the elements
of escape norm at most `δ`, and `H` the subgroup of elements of escape norm `0`.  Then `H ≤ Γ`,
`H` is normal in `Γ`, and `Γ/H` is nilpotent (of some class `j`, which may depend on `B`). -/
theorem exists_lcs_le_zeroEsc {K : ℝ} {B : Set G} (hB : IsStrongApproxGroup K B) {δ : ℝ}
    (hδ : 0 ≤ δ) (hδ1 : δ < 1) (hCδ : 10 ^ 27 * K ^ 9 * δ ≤ 1 / 2) :
    ∃ (H : Subgroup G) (j : ℕ), (H : Set G) = {g | escNorm B g = 0} ∧ (H : Set G) ⊆ B ∧
      H ≤ Subgroup.closure {g | escNorm B g ≤ δ} ∧
      (H.subgroupOf (Subgroup.closure {g | escNorm B g ≤ δ})).Normal ∧
      (⊤ : Subgroup (Subgroup.closure {g | escNorm B g ≤ δ})).lowerCentralSeries j ≤
        H.subgroupOf (Subgroup.closure {g | escNorm B g ≤ δ}) := by
  have hB1 : (1 : G) ∈ B := hB.1.2.1
  have hBinv : B⁻¹ = B := hB.1.2.2.1
  have hBf : B.Finite := hB.1.1
  have hK1 := one_le_of_isBGTApproxGroup hB.1
  have hB10 : B ⊆ B ^ 10 := by
    simpa using Set.pow_subset_pow_right hB1 (show 1 ≤ 10 by norm_num)
  obtain ⟨H, hHset, hHB, hHconj⟩ := exists_subgroup_escNorm_eq_zero hB
  set X : Set G := {g | escNorm B g ≤ δ} with hX
  set Γ := Subgroup.closure X
  have hmemH : ∀ g, g ∈ H ↔ escNorm B g = 0 := fun g => by
    rw [← SetLike.mem_coe, hHset]; rfl
  have hXB : ∀ g ∈ X, g ∈ B := fun g hg => mem_of_escNorm_lt_one hB1 (lt_of_le_of_lt hg hδ1)
  have hHΓ : H ≤ Γ := fun g hg => Subgroup.subset_closure (by
    show escNorm B g ≤ δ; rw [(hmemH g).1 hg]; exact hδ)
  have hnorm : Γ ≤ Subgroup.normalizer (H : Set _) := by
    rw [Subgroup.closure_le]
    intro g hg
    rw [SetLike.mem_coe, Subgroup.mem_normalizer_iff]
    intro h
    have hgB := hXB g hg
    have hginv : g⁻¹ ∈ B := by rw [← hBinv]; simpa using hgB
    constructor
    · intro hh
      simpa using hHconj g⁻¹ (hB10 hginv) h hh
    · intro hh
      simpa [mul_assoc] using hHconj g (hB10 hgB) _ hh
  set C : ℝ := 10 ^ 27 * K ^ 9
  have hC0 : 0 ≤ C := by have : 0 ≤ K ^ 9 := pow_nonneg (by linarith) 9; positivity
  set T : Set Γ := {x : Γ | escNorm B x ≤ δ} with hT
  have hbound : ∀ k, ∀ y ∈ leftComm T k, escNorm B (y : G) ≤ δ * (1 / 2) ^ k := by
    intro k
    induction k with
    | zero => intro y hy; simpa [leftComm, T] using hy
    | succ k ih =>
      rintro _ ⟨x, hx, t, ht, rfl⟩
      have hxb := ih x hx
      have ht' : escNorm B (t : G) ≤ δ := ht
      have hpow : δ * (1 / 2 : ℝ) ^ k ≤ δ := by
        apply mul_le_of_le_one_right hδ; apply pow_le_one₀ <;> norm_num
      have hxB : (x : G)⁻¹ ∈ B ^ 10 := by
        apply hB10; rw [← hBinv]; simpa using hXB _ (hxb.trans hpow)
      have htB : (t : G)⁻¹ ∈ B ^ 10 := by
        apply hB10; rw [← hBinv]; simpa using hXB _ ht'
      have hc := escNorm_commutator_le hB hxB htB
      simp only [inv_inv, escNorm_inv hBinv] at hc
      have e : ((⁅x, t⁆ : Γ) : G) = (x : G) * t * (x : G)⁻¹ * (t : G)⁻¹ := by
        simp [commutatorElement_def]
      rw [e]
      refine hc.trans ?_
      have hn1 := escNorm_nonneg (g := (x : G)) hB1
      have hn2 := escNorm_nonneg (g := (t : G)) hB1
      calc C * escNorm B (x : G) * escNorm B (t : G) ≤ C * (δ * (1 / 2) ^ k) * δ := by
            gcongr
        _ = (C * δ) * (δ * (1 / 2) ^ k) := by ring
        _ ≤ (1 / 2) * (δ * (1 / 2) ^ k) := by
            apply mul_le_mul_of_nonneg_right hCδ; positivity
        _ = δ * (1 / 2) ^ (k + 1) := by ring
  obtain ⟨μ, hμ, hgap⟩ := exists_escNorm_gap hBf hB1
  obtain ⟨j, hj⟩ := exists_pow_lt_of_lt_one (show 0 < μ / 2 by positivity)
    (show (1 / 2 : ℝ) < 1 by norm_num)
  have hHn : (H.subgroupOf Γ).Normal :=
    (Subgroup.normal_subgroupOf_iff_le_normalizer hHΓ).2 hnorm
  refine ⟨H, j, hHset, hHB, hHΓ, hHn, ?_⟩
  refine lcs_le_of_leftComm_subset T Subgroup.closure_closure_coe_preimage _ j ?_
  intro y hy
  have hyb := hbound j y hy
  have hsmall : escNorm B (y : G) < μ := by
    calc escNorm B (y : G) ≤ δ * (1 / 2) ^ j := hyb
      _ ≤ 1 * (1 / 2) ^ j := by gcongr
      _ < μ := by linarith
  have hyB : (y : G) ∈ B := mem_of_escNorm_lt_one hB1 (hyb.trans_lt (by
    calc δ * (1 / 2 : ℝ) ^ j ≤ δ :=
          mul_le_of_le_one_right hδ (pow_le_one₀ (by norm_num) (by norm_num))
      _ < 1 := hδ1))
  rw [SetLike.mem_coe, Subgroup.mem_subgroupOf, hmemH]
  rcases hgap _ hyB with h | h
  · exact h
  · linarith

/-- A uniformly large approximate group of uniformly small escape norm, from the
Sanders–Croot–Sisask theorem and the first trapping condition. -/
theorem exists_large_small_escNorm (K : ℝ) (hK : 1 ≤ K) (L : ℕ) :
    ∃ K' c : ℝ, 0 < c ∧ ∀ {G : Type*} [Group G] (B : Set G), IsStrongApproxGroup K B →
      ∃ S : Set G, IsBGTApproxGroup K' S ∧ c * B.ncard ≤ S.ncard ∧ S ⊆ B ^ 4 ∧
        ∀ s ∈ S, escNorm B s ≤ 1000 / (L + 1) := by
  obtain ⟨K', c, hc, hS⟩ := sanders_small_neighbourhoods K hK (L + 1)
  refine ⟨K', c, hc, fun {G} _ B hB => ?_⟩
  obtain ⟨S, hSapp, hcard, hpow⟩ := hS B hB.1
  have hS1 : (1 : G) ∈ S := hSapp.2.1
  have hB1 : (1 : G) ∈ B := hB.1.2.1
  have hpowS : ∀ s ∈ S, ∀ i ≤ L + 1, s ^ i ∈ B ^ 4 := fun s hs i hi =>
    hpow (Set.pow_subset_pow_right hS1 hi (Set.pow_mem_pow hs))
  obtain ⟨-, S', -, -, htrap, -⟩ := hB
  refine ⟨S, hSapp, hcard, fun s hs => by simpa using hpowS s hs 1 (by omega), fun s hs => ?_⟩
  have h4 : B ^ 4 ⊆ B ^ 100 := Set.pow_subset_pow_right hB1 (by norm_num)
  exact escNorm_le_of_first_trapping htrap (n := L) (fun i hi => h4 (hpowS s hs i (by omega)))

/-- **Finitary nilpotence for strong approximate groups.**  For every `K ≥ 1` there are `K'` and
`c > 0` such that every strong `K`-approximate group `B` admits a `K'`-approximate group
`S ⊆ B⁴` with `|S| ≥ c |B|`, and a subgroup `Γ ⊇ S` such that the zero-escape subgroup `H ⊆ B`
is a normal subgroup of `Γ` with `Γ/H` nilpotent.

The constants `K'`, `c` depend only on `K`, but the nilpotency class `j` is allowed to depend on
`B` (it does, in this argument). -/
theorem finite_nilpotent_mod_zeroEsc (K : ℝ) (hK : 1 ≤ K) :
    ∃ K' c : ℝ, 0 < c ∧ ∀ {G : Type*} [Group G] (B : Set G), IsStrongApproxGroup K B →
      ∃ (S : Set G) (H Γ : Subgroup G) (j : ℕ), IsBGTApproxGroup K' S ∧
        c * B.ncard ≤ S.ncard ∧ S ⊆ B ^ 4 ∧ S ⊆ Γ ∧
        (H : Set G) = {g | escNorm B g = 0} ∧ (H : Set G) ⊆ B ∧ H ≤ Γ ∧
        (H.subgroupOf Γ).Normal ∧ (⊤ : Subgroup Γ).lowerCentralSeries j ≤ H.subgroupOf Γ := by
  set C : ℝ := 10 ^ 27 * K ^ 9 with hCdef
  set L : ℕ := ⌈2000 * C⌉₊ + 1000 with hL
  obtain ⟨K', c, hc, hS⟩ := exists_large_small_escNorm K hK L
  refine ⟨K', c, hc, fun {G} _ B hB => ?_⟩
  obtain ⟨S, hSapp, hcard, hS4, hSsmall⟩ := hS B hB
  have hC0 : 0 ≤ C := by have : 0 ≤ K ^ 9 := pow_nonneg (by linarith) 9; positivity
  have hLC : 2000 * C + 1000 ≤ (L : ℝ) := by
    rw [hL]; push_cast; linarith [Nat.le_ceil (2000 * C)]
  have hLpos : (0 : ℝ) < L + 1 := by positivity
  have hδ1 : (1000 : ℝ) / (L + 1) < 1 := by rw [div_lt_one hLpos]; linarith
  have hCδ : C * (1000 / (L + 1)) ≤ 1 / 2 := by
    rw [mul_div_assoc', div_le_iff₀ hLpos]; linarith
  obtain ⟨H, j, hHset, hHB, hHΓ, hHn, hlcs⟩ :=
    exists_lcs_le_zeroEsc hB (δ := 1000 / (L + 1)) (by positivity) hδ1 hCδ
  exact ⟨S, H, _, j, hSapp, hcard, hS4, fun s hs => Subgroup.subset_closure (hSsmall s hs),
    hHset, hHB, hHΓ, hHn, hlcs⟩

end Lovasz.BGT
