module
public import RequestProject.TTCayley
public import RequestProject.TTNormalClosure
public import Mathlib.GroupTheory.IndexNormal
public import RequestProject.BGTSanders

/-!
# The Breuillard–Green–Tao main theorem and its Gromov-type corollary

Breuillard, Green and Tao, *The structure of approximate groups* (Publ. IHÉS 2012), state their main
result as Theorem 1.6 ("Main theorem, simple form").  Tessera–Tointon use instead the Gromov-type
consequence (Corollary 11.2 together with Remark 11.4 of that paper), which the project had stated
as `BreuillardGreenTao`.

Here we state Theorem 1.6 itself, with the paper's own definition of an approximate group
(Definition 1.2), as `BGTMainTheorem`, and we prove the deduction of Corollary 11.2 / Remark 11.4
given in Section 11 of the paper: `breuillardGreenTao_of_main : BGTMainTheorem → BreuillardGreenTao`.
So the whole project now depends only on the headline theorem of the Breuillard–Green–Tao paper.
-/

@[expose] public section


open scoped Pointwise

namespace Lovasz

/-- **Theorem 1.6** of Breuillard–Green–Tao (main theorem, simple form).  For every `K ≥ 1` there
is a constant `C = O_K(1)` such that for every `K`-approximate group `A` in a group `G` there are a
subgroup `G₀` and a finite subgroup `H ≤ G₀`, normal in `G₀`, with
* (i) `A` covered by at most `C` left translates of `G₀`;
* (ii) `G₀/H` nilpotent of step at most `C` (the `C`-th term of the lower central series of `G₀`
  lies in `H`) and generated by at most `C` elements;
* (iii) `A⁴` contains `H` and a generating set of `G₀`. -/
def BGTMainTheorem : Prop :=
  ∀ K : ℝ, 1 ≤ K → ∃ C : ℕ, ∀ (G : Type) [Group G] (A : Set G), IsBGTApproxGroup K A →
    ∃ G₀ H : Subgroup G, H ≤ G₀ ∧ (H.subgroupOf G₀).Normal ∧ (H : Set G).Finite ∧
      (∃ T : Finset G, T.card ≤ C ∧ A ⊆ ⋃ t ∈ T, t • (G₀ : Set G)) ∧
      (⊤ : Subgroup G₀).lowerCentralSeries C ≤ H.subgroupOf G₀ ∧
      (∃ F : Finset G, F.card ≤ C ∧ (F : Set G) ⊆ G₀ ∧ Subgroup.closure (F : Set G) ⊔ H = G₀) ∧
      (H : Set G) ⊆ A ^ 4 ∧ Subgroup.closure (A ^ 4 ∩ (G₀ : Set G)) = G₀

section Aux

variable {G : Type*} [Group G]

/-- A `K`-approximate subgroup in Mathlib's sense (covering set not required to be symmetric or
to lie in `A³`) is a `2K`-approximate group in the sense of Breuillard–Green–Tao. -/
lemma isBGTApproxGroup_of_isApproximateSubgroup [Finite G] {K : ℝ} {A : Set G}
    (hA : IsApproximateSubgroup K A) : IsBGTApproxGroup (2 * K) A := by
  classical
  obtain ⟨h1, hinv, F, hF, hcov⟩ := hA
  have hinv3 : (A ^ 3)⁻¹ = A ^ 3 := by rw [← inv_pow, hinv]
  set F' : Finset G := F.filter (fun x => x ∈ A ^ 3) with hF'
  have hcov' : A * A ⊆ (F' : Set G) * A := by
    intro y hy
    have hy2 : y ∈ A ^ 2 := by rw [pow_two]; exact hy
    obtain ⟨x, hx, b, hb, rfl⟩ := hcov hy2
    refine ⟨x, ?_, b, hb, rfl⟩
    simp only [hF', Finset.coe_filter, Set.mem_setOf_eq]
    refine ⟨hx, ?_⟩
    have : x = (x • b) * b⁻¹ := by simp
    rw [this, pow_succ]
    refine Set.mul_mem_mul hy2 ?_
    rw [← hinv]; simpa using hb
  refine ⟨Set.toFinite A, h1, hinv, F' ∪ F'⁻¹, ?_, ?_, ?_, ?_⟩
  · push_cast; rw [Set.union_inv, inv_inv, Set.union_comm]
  · push_cast
    refine Set.union_subset (fun x hx => (Finset.mem_filter.1 hx).2) ?_
    intro x hx
    rw [← hinv3]
    exact (Finset.mem_filter.1 (show x⁻¹ ∈ F' by simpa using hx)).2
  · have h1 : ((F' ∪ F'⁻¹).card : ℝ) ≤ F'.card + F'⁻¹.card := by
      exact_mod_cast Finset.card_union_le _ _
    have h2 : (F'.card : ℝ) ≤ F.card := by exact_mod_cast Finset.card_filter_le _ _
    rw [Finset.card_inv] at h1
    linarith
  · refine hcov'.trans (Set.mul_subset_mul_right ?_)
    push_cast; exact Set.subset_union_left

/-- The images of the powers `A^i` in `G/N` are either everything or have at least `i+1`
elements. -/
lemma image_pow_eq_univ_or [Finite G] (A : Set G) (h1 : 1 ∈ A) (hA : A⁻¹ = A)
    (hcl : Subgroup.closure A = ⊤) (N : Subgroup G) (i : ℕ) :
    (QuotientGroup.mk : G → G ⧸ N) '' (A ^ i) = Set.univ ∨
      i + 1 ≤ ((QuotientGroup.mk : G → G ⧸ N) '' (A ^ i)).ncard := by
  set c : ℕ → Set (G ⧸ N) := fun i => (QuotientGroup.mk : G → G ⧸ N) '' (A ^ i) with hc
  have hmono : ∀ i, c i ⊆ c (i + 1) := fun i =>
    Set.image_mono (Set.pow_subset_pow_right h1 (by omega))
  show c i = Set.univ ∨ i + 1 ≤ (c i).ncard
  induction i with
  | zero => right; simp [c]
  | succ i ih =>
    by_cases hu : c (i + 1) = Set.univ
    · left; exact hu
    right
    rcases ih with h | h
    · exact absurd (Set.eq_univ_of_univ_subset (h ▸ hmono i)) hu
    have hne : c i ≠ c (i + 1) := by
      intro heq
      apply hu
      have hP := eq_univ_of_mul_closed A hA hcl ((QuotientGroup.mk : G → G ⧸ N) ⁻¹' c i) ?_ ?_
      · rw [← heq]
        ext y
        obtain ⟨z, rfl⟩ := QuotientGroup.mk_surjective y
        simp only [Set.mem_univ, iff_true]
        have : z ∈ (QuotientGroup.mk : G → G ⧸ N) ⁻¹' c i := hP ▸ Set.mem_univ z
        exact this
      · exact ⟨1, Set.one_mem_pow h1, rfl⟩
      · intro a ha p hp
        obtain ⟨q', hq', hpq⟩ := hp
        show (QuotientGroup.mk (a * p) : G ⧸ N) ∈ c i
        rw [heq]
        refine ⟨a * q', ?_, ?_⟩
        · rw [pow_succ']; exact Set.mul_mem_mul ha hq'
        · rw [QuotientGroup.eq] at hpq ⊢
          simpa [mul_assoc] using hpq
    have hlt : (c i).ncard < (c (i + 1)).ncard :=
      Set.ncard_lt_ncard (lt_of_le_of_ne (hmono i) hne) (Set.toFinite _)
    omega

/-- If `A^j` is covered by at most `j` left cosets of `G₀`, then `G₀` has index at most `j` (the
observation at the start of the proof of Corollary 11.2 of Breuillard–Green–Tao). -/
lemma index_le_of_pow_covered [Finite G] (A : Set G) (h1 : 1 ∈ A) (hA : A⁻¹ = A)
    (hcl : Subgroup.closure A = ⊤) (G₀ : Subgroup G) (j : ℕ) (T : Finset G) (hT : T.card ≤ j)
    (hcov : A ^ j ⊆ ⋃ t ∈ T, t • (G₀ : Set G)) : G₀.index ≤ j := by
  classical
  set c := (QuotientGroup.mk : G → G ⧸ G₀) '' (A ^ j) with hc
  have hsub : c ⊆ (T.image (QuotientGroup.mk : G → G ⧸ G₀) : Set (G ⧸ G₀)) := by
    rintro _ ⟨x, hx, rfl⟩
    have := hcov hx
    simp only [Set.mem_iUnion] at this
    obtain ⟨t, ht, hxt⟩ := this
    obtain ⟨g, hg, rfl⟩ := hxt
    simp only [Finset.coe_image, Set.mem_image, Finset.mem_coe]
    refine ⟨t, ht, ?_⟩
    rw [QuotientGroup.eq]
    simpa using hg
  have hcard : c.ncard ≤ j := by
    calc c.ncard ≤ (T.image (QuotientGroup.mk : G → G ⧸ G₀) : Set (G ⧸ G₀)).ncard :=
          Set.ncard_le_ncard hsub (Finset.finite_toSet _)
      _ = (T.image (QuotientGroup.mk : G → G ⧸ G₀)).card := Set.ncard_coe_finset _
      _ ≤ T.card := Finset.card_image_le
      _ ≤ j := hT
  rcases image_pow_eq_univ_or A h1 hA hcl G₀ j with h | h
  · rw [← hc] at h
    rw [h, Set.ncard_univ] at hcard
    exact hcard
  · rw [← hc] at h
    omega

/-- The lower central series of a normal subgroup, viewed in the ambient group, is normal. -/
lemma lowerCentralSeries_map_subtype_normal (N : Subgroup G) [N.Normal] (s : ℕ) :
    (((⊤ : Subgroup N).lowerCentralSeries s).map N.subtype).Normal := by
  constructor
  rintro _ ⟨x, hx, rfl⟩ g
  set φ : N ≃* N := MulAut.conjNormal g
  have hchar : ((⊤ : Subgroup N).lowerCentralSeries s).map φ.toMonoidHom =
      (⊤ : Subgroup N).lowerCentralSeries s :=
    (Subgroup.characteristic_iff_map_eq.1 inferInstance) φ
  have hmem : φ x ∈ (⊤ : Subgroup N).lowerCentralSeries s := by
    rw [← hchar]; exact Subgroup.mem_map_of_mem _ hx
  refine ⟨φ x, hmem, ?_⟩
  simp [φ, MulAut.conjNormal_apply]

end Aux

/-- **Corollary 11.2 and Remark 11.4** of Breuillard–Green–Tao (the form used by Tessera–Tointon
as their Theorem 6.4), for finite groups, deduced from **Theorem 1.6** as in Section 11 of the
paper. -/
theorem breuillardGreenTao_of_main (hM : BGTMainTheorem) : BreuillardGreenTao := by
  intro K hK
  obtain ⟨C, hC⟩ := hM (2 * K) (by linarith)
  refine ⟨C, C.factorial, C, ?_⟩
  intro G _ _ A m h1 hinv hcl hm happ
  have hB := isBGTApproxGroup_of_isApproximateSubgroup happ
  obtain ⟨G₀, H, hHG₀, -, -, ⟨T, hTC, hcov⟩, hlcs, -, hH4, -⟩ := hC G (A ^ m) hB
  -- `G₀` has index at most `C`.
  have hidx : G₀.index ≤ C := by
    refine index_le_of_pow_covered A h1 hinv hcl G₀ C T hTC ?_
    exact (Set.pow_subset_pow_right h1 hm).trans hcov
  set G₁ := G₀.normalCore with hG₁
  have hG₁le : G₁ ≤ G₀ := G₀.normalCore_le
  have hidx₁ : G₁.index ≤ C.factorial := by
    have h : G₁.index ∣ G₀.index.factorial := by
      rw [hG₁, Subgroup.normalCore_eq_ker, Subgroup.index_ker, Subgroup.index_eq_card,
        ← Nat.card_perm]
      exact Subgroup.card_subgroup_dvd_card _
    exact (Nat.le_of_dvd (Nat.factorial_pos _) h).trans (Nat.factorial_le hidx)
  refine ⟨((⊤ : Subgroup G₁).lowerCentralSeries C).map G₁.subtype, G₁,
    lowerCentralSeries_map_subtype_normal G₁ C, G₀.normalCore_normal, ?_, ?_, hidx₁, le_rfl⟩
  · rintro _ ⟨x, -, rfl⟩; exact x.2
  · -- `γ_C(G₁) ≤ γ_C(G₀) ≤ H ⊆ A^(4m)`.
    have e1 : ((⊤ : Subgroup G₁).lowerCentralSeries C).map G₁.subtype ≤
        ((⊤ : Subgroup G₀).lowerCentralSeries C).map G₀.subtype := by
      have hinc := lowerCentralSeries_map_subtype_le (G₁.subgroupOf G₀) C
      rintro _ ⟨x, hx, rfl⟩
      have hx' : (⟨⟨(x : G), hG₁le x.2⟩, x.2⟩ : G₁.subgroupOf G₀) ∈
          (⊤ : Subgroup (G₁.subgroupOf G₀)).lowerCentralSeries C := by
        have e : (Subgroup.subgroupOfEquivOfLe hG₁le).symm x =
            (⟨⟨(x : G), hG₁le x.2⟩, x.2⟩ : G₁.subgroupOf G₀) := rfl
        rw [← e]
        have hchar := lowerCentralSeries_map_of_surjective
          ((Subgroup.subgroupOfEquivOfLe hG₁le).symm : G₁ →* G₁.subgroupOf G₀)
          (Subgroup.subgroupOfEquivOfLe hG₁le).symm.surjective C
        rw [← hchar]
        exact Subgroup.mem_map_of_mem _ hx
      exact ⟨_, hinc (Subgroup.mem_map_of_mem _ hx'), rfl⟩
    have e2 : ((⊤ : Subgroup G₀).lowerCentralSeries C).map G₀.subtype ≤ H := by
      rintro _ ⟨x, hx, rfl⟩
      exact hlcs hx
    intro x hx
    have := hH4 (e2 (e1 hx))
    rwa [← pow_mul, mul_comm] at this

end Lovasz
