module
public import RequestProject.BGTMain
public import RequestProject.TointonNormal

/-!
# The rank form of Green–Ruzsa from the Breuillard–Green–Tao theorem

Applied to an abelian group, Theorem 1.6 of Breuillard–Green–Tao says that a `K`-approximate
group `B` is covered by `O_K(1)` translates of a subgroup `G₀` containing a subgroup `H ⊆ B⁴` with
`G₀/H` generated by `O_K(1)` elements.  Using the fact that subgroups of a `d`-generated abelian
group are `d`-generated, and Ruzsa's covering, we deduce `Tointon.GreenRuzsaRank`, the only input of
our formalization of Tointon's normal-closure lemma.  Hence Tointon's lemma (Lemma 6.6 of
Tessera–Tointon), as stated in `TointonNormalClosure`, follows from `BGTMainTheorem`.
-/

@[expose] public section


open scoped Pointwise

namespace Lovasz

/-- The rank form of the Green–Ruzsa theorem follows from Theorem 1.6 of Breuillard–Green–Tao. -/
theorem greenRuzsaRank_of_BGTMain (hM : BGTMainTheorem) : Tointon.GreenRuzsaRank := by
  classical
  intro K hK
  obtain ⟨C, hC⟩ := hM (2 * K) (by linarith)
  set K₃ : ℝ := K ^ (2 * 2 - 1) * 1 ^ (2 * 2 - 1) with hK₃
  refine ⟨⌊K₃⌋₊ + C + C, 6, ?_⟩
  intro Z _ _ B hB
  have hB1 := hB.one_mem
  have hBinv := hB.inv_eq_self
  obtain ⟨G₀, H, -, -, -, ⟨T, hTC, hcov⟩, -, ⟨F, hFC, hFG₀, hFgen⟩, hH4, -⟩ :=
    hC Z B (isBGTApproxGroup_of_isApproximateSubgroup hB)
  -- representatives in `B` of the cosets of `G₀` meeting `B`
  let rep : Z → Z := fun t => if h : ∃ b ∈ B, b ∈ t • (G₀ : Set Z) then h.choose else 1
  have hrepB : ∀ t, rep t ∈ B := by
    intro t; simp only [rep]; split_ifs with h
    · exact h.choose_spec.1
    · exact hB1
  set T' := T.image rep with hT'
  have hT'B : (T' : Set Z) ⊆ B := by
    intro x hx; simp only [hT', Finset.coe_image, Set.mem_image] at hx
    obtain ⟨t, -, rfl⟩ := hx; exact hrepB t
  have hT'C : T'.card ≤ C := Finset.card_image_le.trans hTC
  set R₀ : Set Z := B ^ 2 ∩ (G₀ : Set Z) with hR₀
  have hG₀2 : (G₀ : Set Z) ^ 2 = G₀ := by rw [pow_two, coe_mul_coe G₀]
  have hBsplit : ∀ b ∈ B, ∃ r ∈ (T' : Set Z), r⁻¹ * b ∈ R₀ := by
    intro b hb
    have := hcov hb
    simp only [Set.mem_iUnion] at this
    obtain ⟨t, ht, hbt⟩ := this
    have hex : ∃ b ∈ B, b ∈ t • (G₀ : Set Z) := ⟨b, hb, hbt⟩
    have hrep : rep t = hex.choose := dif_pos hex
    refine ⟨rep t, Finset.mem_coe.2 (Finset.mem_image_of_mem _ ht), ?_, ?_⟩
    · rw [pow_two]
      refine Set.mul_mem_mul ?_ hb
      rw [← hBinv]; simpa using hrepB t
    · obtain ⟨g, hg, hgb⟩ := hbt
      obtain ⟨g', hg', hg'r⟩ := hex.choose_spec.2
      rw [hrep, ← hg'r, ← hgb]
      simp only [smul_eq_mul, mul_inv_rev, SetLike.mem_coe]
      have : g'⁻¹ * t⁻¹ * (t * g) = g'⁻¹ * g := by group
      rw [this]; exact G₀.mul_mem (G₀.inv_mem hg') hg
  have hR₀approx : IsApproximateSubgroup K₃ R₀ := by
    have := hB.pow_inter_pow (IsApproximateSubgroup.subgroup (H := G₀)) (le_refl 2) (le_refl 2)
    rwa [hG₀2] at this
  -- pass to `Z / H`
  set q : Z →* Z ⧸ H := QuotientGroup.mk' H with hq
  set R : Set (Z ⧸ H) := q '' R₀ with hRdef
  have hRapprox : IsApproximateSubgroup K₃ R := hR₀approx.image q
  have hR1 : (1 : Z ⧸ H) ∈ R := hRapprox.one_mem
  have hRinv : R⁻¹ = R := hRapprox.inv_eq_self
  have hRF : Subgroup.closure R ≤ Subgroup.closure ((F.image q : Finset _) : Set (Z ⧸ H)) := by
    rw [Subgroup.closure_le]
    rintro _ ⟨r, hr, rfl⟩
    have hrG : r ∈ Subgroup.closure (F : Set Z) ⊔ H := by rw [hFgen]; exact hr.2
    obtain ⟨w, hw, h, hh, rfl⟩ := Subgroup.mem_sup.1 hrG
    have hqh : q h = 1 := (QuotientGroup.eq_one_iff h).2 hh
    rw [map_mul, hqh, mul_one, Finset.coe_image, ← MonoidHom.map_closure]
    exact Subgroup.mem_map_of_mem q hw
  obtain ⟨Y₁, hY₁c, hY₁⟩ := Tointon.exists_finset_closure_eq_of_le_closure _ _ hRF
  -- Ruzsa covering for `R`, with covering set inside `R³`
  obtain ⟨Yc, hYc, hcovR⟩ := hRapprox.sq_covBySMul
  set Y := Yc.filter (· ∈ R ^ 3) with hYdef
  have hYR3 : (Y : Set (Z ⧸ H)) ⊆ R ^ 3 := fun y hy => (Finset.mem_filter.1 hy).2
  have hcovR' : R * R ⊆ (Y : Set (Z ⧸ H)) * R := by
    intro x hx
    have hx2 : x ∈ R ^ 2 := by rw [pow_two]; exact hx
    obtain ⟨y, hy, r, hr, rfl⟩ := hcovR hx2
    refine ⟨y, Finset.mem_filter.2 ⟨hy, ?_⟩, r, hr, rfl⟩
    have : y = (y • r) * r⁻¹ := by simp
    rw [this, pow_succ]
    refine Set.mul_mem_mul hx2 ?_
    rw [← hRinv]; simpa using hr
  have hYcard : Y.card ≤ ⌊K₃⌋₊ :=
    Nat.le_floor ((by exact_mod_cast Finset.card_filter_le _ _ : (Y.card : ℝ) ≤ Yc.card).trans hYc)
  have hclR : ∀ x ∈ Subgroup.closure R,
      x ∈ (Subgroup.closure (Y : Set (Z ⧸ H)) : Set (Z ⧸ H)) * R := by
    intro x hx
    induction hx using Subgroup.closure_induction with
    | mem r hr => exact ⟨1, one_mem _, r, hr, one_mul r⟩
    | one => exact ⟨1, one_mem _, 1, hR1, one_mul 1⟩
    | mul a b _ _ ha hb =>
      obtain ⟨w, hw, r, hr, rfl⟩ := ha
      obtain ⟨w', hw', r', hr', rfl⟩ := hb
      obtain ⟨y, hy, r'', hr'', hyr⟩ := hcovR' (Set.mul_mem_mul hr hr')
      refine ⟨w * w' * y, Subgroup.mul_mem _ (Subgroup.mul_mem _ hw hw')
        (Subgroup.subset_closure hy), r'', hr'', ?_⟩
      simp only at hyr ⊢
      calc w * w' * y * r'' = w * w' * (y * r'') := by rw [mul_assoc]
        _ = w * w' * (r * r') := by rw [hyr]
        _ = w * r * (w' * r') := by
          rw [mul_mul_mul_comm]
    | inv a _ ha =>
      obtain ⟨w, hw, r, hr, rfl⟩ := ha
      refine ⟨w⁻¹, Subgroup.inv_mem _ hw, r⁻¹, ?_, by simp [mul_comm]⟩
      rw [← hRinv]; simpa using hr
  -- a bounded generating set for `⟨R⟩` inside `R³`
  have hgen : ∀ g ∈ Y₁, ∃ r ∈ R, g * r⁻¹ ∈ Subgroup.closure (Y : Set (Z ⧸ H)) := by
    intro g hg
    have hgR : g ∈ Subgroup.closure R := by rw [← hY₁]; exact Subgroup.subset_closure hg
    obtain ⟨w, hw, r, hr, rfl⟩ := hclR g hgR
    exact ⟨r, hr, by simpa using hw⟩
  choose! rg hrgR hrg using hgen
  set Xq := Y ∪ Y₁.image rg with hXq
  have hXqR3 : (Xq : Set (Z ⧸ H)) ⊆ R ^ 3 := by
    intro x hx
    rcases Finset.mem_union.1 hx with h | h
    · exact hYR3 h
    · obtain ⟨g, hg, rfl⟩ := Finset.mem_image.1 h
      exact Set.pow_subset_pow_right hR1 (by norm_num : 1 ≤ 3) (by simpa using hrgR g hg)
  have hXqcard : Xq.card ≤ ⌊K₃⌋₊ + C :=
    (Finset.card_union_le _ _).trans (add_le_add hYcard (Finset.card_image_le.trans
      (hY₁c.trans (Finset.card_image_le.trans hFC))))
  have hRXq : Subgroup.closure R ≤ Subgroup.closure (Xq : Set (Z ⧸ H)) := by
    rw [← hY₁, Subgroup.closure_le]
    intro g hg
    have h1 : g * (rg g)⁻¹ ∈ Subgroup.closure (Xq : Set (Z ⧸ H)) :=
      Subgroup.closure_mono (by simp [hXq]) (hrg g hg)
    have h2 : rg g ∈ Subgroup.closure (Xq : Set (Z ⧸ H)) :=
      Subgroup.subset_closure
        (Finset.mem_coe.2 (Finset.mem_union_right _ (Finset.mem_image_of_mem rg hg)))
    have : g = g * (rg g)⁻¹ * rg g := by group
    rw [this]; exact Subgroup.mul_mem _ h1 h2
  -- lift the generators to `R₀³ ⊆ B⁶`
  have hlift : ∀ x ∈ Xq, ∃ x' ∈ R₀ ^ 3, q x' = x := by
    intro x hx
    have := hXqR3 hx
    rw [hRdef, ← Set.image_pow] at this
    obtain ⟨x', hx', rfl⟩ := this
    exact ⟨x', hx', rfl⟩
  choose! lift hliftR hliftq using hlift
  set X₁ := Xq.image lift with hX₁
  have hX₁B : (X₁ : Set Z) ⊆ B ^ 6 := by
    intro x hx
    obtain ⟨y, hy, rfl⟩ := Finset.mem_image.1 hx
    have h := hliftR y hy
    have hsub : R₀ ^ 3 ⊆ (B ^ 2) ^ 3 := Set.pow_subset_pow_left Set.inter_subset_left
    rw [← pow_mul] at hsub
    exact hsub h
  have hR₀sub : R₀ ⊆ (H : Set Z) * (Subgroup.closure (X₁ : Set Z) : Set Z) := by
    intro r hr
    have hqr : q r ∈ Subgroup.closure (Xq : Set (Z ⧸ H)) :=
      hRXq (Subgroup.subset_closure ⟨r, hr, rfl⟩)
    have hXqX₁ : Subgroup.closure (Xq : Set (Z ⧸ H)) ≤
        (Subgroup.closure (X₁ : Set Z)).map q := by
      rw [Subgroup.closure_le]
      intro x hx
      rw [← hliftq x hx]
      exact Subgroup.mem_map_of_mem q
        (Subgroup.subset_closure (Finset.mem_coe.2 (Finset.mem_image_of_mem lift hx)))
    obtain ⟨w, hw, hwr⟩ := hXqX₁ hqr
    have hmem : w⁻¹ * r ∈ H := QuotientGroup.eq.1 hwr
    exact ⟨w⁻¹ * r, hmem, w, hw, by rw [mul_comm]; group⟩
  refine ⟨H, X₁ ∪ T', ?_, ?_, ?_, ?_⟩
  · exact hH4.trans (Set.pow_subset_pow_right hB1 (by norm_num))
  · push_cast
    exact Set.union_subset hX₁B (hT'B.trans (by
      simpa using Set.pow_subset_pow_right hB1 (by norm_num : 1 ≤ 6)))
  · calc (X₁ ∪ T').card ≤ X₁.card + T'.card := Finset.card_union_le _ _
      _ ≤ (⌊K₃⌋₊ + C) + C := add_le_add (Finset.card_image_le.trans hXqcard) hT'C
  · intro b hb
    obtain ⟨r, hr, hrb⟩ := hBsplit b hb
    obtain ⟨h, hh, w, hw, hhw⟩ := hR₀sub hrb
    refine ⟨h, hh, r * w, ?_, ?_⟩
    · refine Subgroup.mul_mem _ (Subgroup.subset_closure (by simp [hr])) ?_
      exact Subgroup.closure_mono (by simp) hw
    · simp only at hhw ⊢
      calc h * (r * w) = r * (h * w) := mul_left_comm h r w
        _ = r * (r⁻¹ * b) := by rw [hhw]
        _ = b := by group

/-- **Tointon's normal-closure lemma** (Lemma 6.6 of Tessera–Tointon, Proposition 7.3 of Tointon)
for finite groups, derived from Theorem 1.6 of Breuillard–Green–Tao. -/
theorem tointonNormalClosure_of_BGTMain (hM : BGTMainTheorem) : TointonNormalClosure :=
  Tointon.normalClosure_subset_pow_of_greenRuzsa (greenRuzsaRank_of_BGTMain hM)

end Lovasz
