module
public import Mathlib

/-!
# Green–Ruzsa, dyadic residue counting along a flag

An abstract counting lemma.  Let `L` be a subgroup of an abelian group `V`, with integer-valued
additive forms `π 0, …, π (d-1)` which separate the points of `L`.  Put
`L_j = {x ∈ L | π k x = 0 for j ≤ k < d}`.  Suppose that for each `j < d` the values of `π j` on
`L_(j+1)` form the subgroup generated by `a j = π j (b j) > 0`, and that `m (d-1) ∣ ⋯ ∣ m 0` are
positive.  If a finite set `S ⊆ L` contains no two points whose difference is `m j • w` with
`w ∈ L_(j+1)` and `π j w ≠ 0`, then `|S| ≤ ∏_(j<d) m j`.
-/

@[expose] public section

open Finset

namespace GreenRuzsa

variable {V : Type*} [AddCommGroup V] [DecidableEq V]

/-- The `j`-th subgroup of the flag. -/
def flagMem (L : AddSubgroup V) (d : ℕ) (π : ℕ → V →+ ℤ) (j : ℕ) (x : V) : Prop :=
  x ∈ L ∧ ∀ k, j ≤ k → k < d → π k x = 0

theorem card_le_prod_of_flag (L : AddSubgroup V) (d : ℕ) (π : ℕ → V →+ ℤ) (m : ℕ → ℕ)
    (hm : ∀ j < d, 0 < m j) (hdvd : ∀ i j, i ≤ j → j < d → m j ∣ m i)
    (hsep : ∀ x ∈ L, (∀ k < d, π k x = 0) → x = 0)
    (hb : ∀ j < d, ∃ (b : V) (a : ℤ), flagMem L d π (j + 1) b ∧ π j b = a ∧ 0 < a ∧
      ∀ x, flagMem L d π (j + 1) x → a ∣ π j x) :
    ∀ j ≤ d, ∀ S : Finset V, (∀ x ∈ S, flagMem L d π j x) →
      (∀ x ∈ S, ∀ y ∈ S, ∀ i < d, ∀ w, flagMem L d π (i + 1) w → π i w ≠ 0 →
        x - y ≠ (m i : ℤ) • w) →
      S.card ≤ ∏ i ∈ range j, m i := by
  intro j
  induction j with
  | zero =>
    intro _ S hSL _
    rw [prod_range_zero]
    refine Finset.card_le_one.2 fun x hx y hy => ?_
    have h1 := hsep x (hSL x hx).1 fun k hk => (hSL x hx).2 k (Nat.zero_le _) hk
    have h2 := hsep y (hSL y hy).1 fun k hk => (hSL y hy).2 k (Nat.zero_le _) hk
    rw [h1, h2]
  | succ j ih =>
    intro hjd S hSL hS
    have hj : j < d := hjd
    obtain ⟨bj, aj, hbL, hba, ha, hdiv⟩ := hb j hj
    have hmj := hm j hj
    set t : V → ℤ := fun x => π j x / aj with ht
    set r : V → ℕ := fun x => (t x % (m j : ℤ)).toNat with hr
    -- the translated set of a residue class
    set T : ℕ → Finset V := fun c => (S.filter fun x => r x = c).image fun x => x - t x • bj
    have hmz : (0 : ℤ) < m j := by exact_mod_cast hmj
    have hrmod : ∀ x y, r x = r y → (m j : ℤ) ∣ t x - t y := by
      intro x y hxy
      have hx0 : 0 ≤ t x % (m j : ℤ) := Int.emod_nonneg _ hmz.ne'
      have hy0 : 0 ≤ t y % (m j : ℤ) := Int.emod_nonneg _ hmz.ne'
      have : t x % (m j : ℤ) = t y % (m j : ℤ) := by
        have := congrArg (fun n : ℕ => (n : ℤ)) hxy
        simpa [hr, Int.toNat_of_nonneg hx0, Int.toNat_of_nonneg hy0] using this
      exact Int.ModEq.dvd this.symm
    have htb : ∀ x, flagMem L d π (j + 1) x → t x * aj = π j x := fun x hx =>
      Int.ediv_mul_cancel (hdiv x hx)
    -- elements of the translated classes lie in `L_j`
    have hTL : ∀ c, ∀ x' ∈ T c, flagMem L d π j x' := by
      intro c x' hx'
      obtain ⟨x, hx, rfl⟩ := mem_image.1 hx'
      have hxS := (mem_filter.1 hx).1
      have hxf := hSL x hxS
      refine ⟨L.sub_mem hxf.1 (L.zsmul_mem hbL.1 _), fun k hk hkd => ?_⟩
      rcases eq_or_lt_of_le hk with rfl | hk'
      · simp only [map_sub, map_zsmul, smul_eq_mul, hba]
        rw [htb x hxf]
        ring
      · simp only [map_sub, map_zsmul, smul_eq_mul]
        rw [hxf.2 k hk' hkd, hbL.2 k hk' hkd]
        ring
    -- injectivity on each class
    have hinj : ∀ c, Set.InjOn (fun x => x - t x • bj) (S.filter fun x => r x = c : Set V) := by
      intro c x hx y hy hxy
      simp only [coe_filter, Set.mem_setOf_eq] at hx hy
      obtain ⟨k, hk⟩ := hrmod x y (hx.2.trans hy.2.symm)
      have hxy' : x - y = (m j : ℤ) • (k • bj) := by
        rw [smul_smul, ← hk, sub_smul]
        simp only at hxy
        linear_combination (norm := abel) hxy
      by_cases hk0 : k = 0
      · rw [hk0, zero_smul, smul_zero] at hxy'
        exact sub_eq_zero.1 hxy'
      · exfalso
        refine hS x hx.1 y hy.1 j hj (k • bj) ⟨L.zsmul_mem hbL.1 _, fun l hl hld => ?_⟩ ?_ hxy'
        · simp [hbL.2 l hl hld]
        · simp only [map_zsmul, smul_eq_mul, hba]
          exact mul_ne_zero hk0 ha.ne'
    -- the separation hypothesis for the translated classes
    have hTS : ∀ c, ∀ x' ∈ T c, ∀ y' ∈ T c, ∀ i < d, ∀ w, flagMem L d π (i + 1) w →
        π i w ≠ 0 → x' - y' ≠ (m i : ℤ) • w := by
      intro c x' hx' y' hy' i hi w hw hwi heq
      have hx'L := hTL c x' hx'
      have hy'L := hTL c y' hy'
      by_cases hij : j ≤ i
      · have h1 : π i (x' - y') = 0 := by
          rw [map_sub, hx'L.2 i hij hi, hy'L.2 i hij hi, sub_zero]
        rw [heq, map_zsmul, smul_eq_mul] at h1
        rcases mul_eq_zero.1 h1 with h | h
        · have := hm i hi
          omega
        · exact hwi h
      · push_neg at hij
        obtain ⟨x, hx, rfl⟩ := mem_image.1 hx'
        obtain ⟨y, hy, rfl⟩ := mem_image.1 hy'
        simp only [mem_filter] at hx hy
        obtain ⟨k, hk⟩ := hrmod x y (hx.2.trans hy.2.symm)
        obtain ⟨e, he⟩ := hdvd i j hij.le hj
        have hxy : x - y = (m i : ℤ) • w + ((m j : ℤ) * k) • bj := by
          rw [← hk, sub_smul]
          linear_combination (norm := abel) heq
        by_cases hk0 : k = 0
        · rw [hk0, mul_zero, zero_smul, add_zero] at hxy
          exact hS x hx.1 y hy.1 i hi w hw hwi hxy
        · refine hS x hx.1 y hy.1 j hj ((e : ℤ) • w + k • bj) ⟨?_, fun l hl hld => ?_⟩ ?_ ?_
          · exact L.add_mem (L.zsmul_mem hw.1 _) (L.zsmul_mem hbL.1 _)
          · simp only [map_add, map_zsmul, smul_eq_mul]
            rw [hw.2 l (by omega) hld, hbL.2 l hl hld]
            ring
          · simp only [map_add, map_zsmul, smul_eq_mul, hba]
            rw [hw.2 j (by omega) hj]
            simpa using mul_ne_zero hk0 ha.ne'
          · rw [hxy, smul_add, smul_smul, smul_smul, he]
            push_cast
            ring_nf
    -- counting
    have hmaps : ∀ x ∈ S, r x ∈ range (m j) := by
      intro x _
      rw [mem_range]
      have h0 : 0 ≤ t x % (m j : ℤ) := Int.emod_nonneg _ hmz.ne'
      have h1 : t x % (m j : ℤ) < m j := Int.emod_lt_of_pos _ hmz
      show (t x % (m j : ℤ)).toNat < m j
      omega
    rw [card_eq_sum_card_fiberwise (f := r) (t := range (m j)) (fun x hx => by simpa using hmaps x hx), prod_range_succ, mul_comm]
    calc ∑ c ∈ range (m j), (S.filter fun x => r x = c).card
        ≤ ∑ _c ∈ range (m j), ∏ i ∈ range j, m i := by
          refine sum_le_sum fun c _ => ?_
          rw [← card_image_of_injOn (hinj c)]
          exact ih (by omega) (T c) (hTL c) (hTS c)
      _ = m j * ∏ i ∈ range j, m i := by simp

end GreenRuzsa
