module
public import Mathlib

/-!
# Commutator width against an abelian normal subgroup (Guralnick's lemma)

If `D` is an abelian normal subgroup of a group `Q`, and `Q` is generated by `D` together with
elements `x₁, …, x_r`, then every element of `[Q, D]` is a product `∏ᵢ [xᵢ, dᵢ]` with `dᵢ ∈ D`.

We use Mathlib's commutator convention `⁅x, y⁆ = x * y * x⁻¹ * y⁻¹`.  The generators are given
as a list `l` (repetitions allowed), and the `dᵢ` as a list `ds` of the same length.

* `Tointon.commutator_abelian_normal_eq_prod`: the absolute statement.
* `Tointon.exists_commutator_product`: the relative version, modulo a normal subgroup `N ≤ E`
  with `⁅E, E⁆ ≤ N`.
-/

@[expose] public section

open scoped Pointwise
open scoped commutatorElement

namespace Tointon

variable {Q : Type*} [Group Q]

/-- The product `∏ᵢ ⁅lᵢ, dsᵢ⁆`. -/
def commProd (l ds : List Q) : Q := (List.zipWith (fun x d => ⁅x, d⁆) l ds).prod

@[simp] lemma commProd_nil_left (ds : List Q) : commProd [] ds = 1 := by simp [commProd]

@[simp] lemma commProd_cons_cons (x d : Q) (l ds : List Q) :
    commProd (x :: l) (d :: ds) = ⁅x, d⁆ * commProd l ds := by simp [commProd]

lemma map_commProd {R : Type*} [Group R] (f : Q →* R) (l ds : List Q) :
    f (commProd l ds) = commProd (l.map f) (ds.map f) := by
  induction l generalizing ds with
  | nil => simp
  | cons x l ih =>
    cases ds with
    | nil => simp [commProd]
    | cons d ds => simp [ih, map_commutatorElement]

/-- The set of products `∏ᵢ ⁅lᵢ, dᵢ⁆` with all `dᵢ ∈ D`. -/
def commProdSet (D : Subgroup Q) (l : List Q) : Set Q :=
  {g | ∃ ds : List Q, ds.length = l.length ∧ (∀ d ∈ ds, d ∈ D) ∧ g = commProd l ds}

section Abelian

variable {D : Subgroup Q} (hDn : D.Normal) (hDab : ∀ a ∈ D, ∀ b ∈ D, a * b = b * a)
include hDn hDab

omit hDab in
lemma comm_mem_of_normal (x : Q) {d : Q} (hd : d ∈ D) : ⁅x, d⁆ ∈ D := by
  rw [commutatorElement_def]
  exact D.mul_mem (hDn.conj_mem _ hd x) (D.inv_mem hd)

omit hDab in
lemma commProd_mem (l : List Q) {ds : List Q} (hds : ∀ d ∈ ds, d ∈ D) : commProd l ds ∈ D := by
  induction l generalizing ds with
  | nil => simp [D.one_mem]
  | cons x l ih =>
    cases ds with
    | nil => simp [commProd, D.one_mem]
    | cons d ds =>
      rw [commProd_cons_cons]
      exact D.mul_mem (comm_mem_of_normal hDn x (hds d (by simp)))
        (ih fun d' hd' => hds d' (by simp [hd']))

omit hDab in
lemma commProdSet_subset (l : List Q) : commProdSet D l ⊆ D := by
  rintro g ⟨ds, -, hds, rfl⟩
  exact commProd_mem hDn l hds

/-- In the abelian normal subgroup `D`, `d ↦ ⁅x, d⁆` is multiplicative. -/
lemma comm_mul_right_of_abelian (x : Q) {a b : Q} (ha : a ∈ D) (hb : b ∈ D) :
    ⁅x, a * b⁆ = ⁅x, a⁆ * ⁅x, b⁆ := by
  have hxb : x * b * x⁻¹ ∈ D := hDn.conj_mem _ hb x
  have h1 : a⁻¹ * (x * b * x⁻¹) = (x * b * x⁻¹) * a⁻¹ := hDab _ (D.inv_mem ha) _ hxb
  have h2 : b⁻¹ * a⁻¹ = a⁻¹ * b⁻¹ := hDab _ (D.inv_mem hb) _ (D.inv_mem ha)
  simp only [commutatorElement_def]
  calc x * (a * b) * x⁻¹ * (a * b)⁻¹
      = x * a * x⁻¹ * (x * b * x⁻¹) * (b⁻¹ * a⁻¹) := by group
    _ = x * a * x⁻¹ * (x * b * x⁻¹) * (a⁻¹ * b⁻¹) := by rw [h2]
    _ = x * a * x⁻¹ * ((x * b * x⁻¹) * a⁻¹) * b⁻¹ := by group
    _ = x * a * x⁻¹ * (a⁻¹ * (x * b * x⁻¹)) * b⁻¹ := by rw [h1]
    _ = x * a * x⁻¹ * a⁻¹ * (x * b * x⁻¹ * b⁻¹) := by group

lemma comm_inv_right_of_abelian (x : Q) {a : Q} (ha : a ∈ D) : ⁅x, a⁻¹⁆ = ⁅x, a⁆⁻¹ := by
  have h := comm_mul_right_of_abelian hDn hDab x ha (D.inv_mem ha)
  rw [mul_inv_cancel, commutatorElement_one_right] at h
  exact eq_inv_of_mul_eq_one_right h.symm

omit hDn hDab in
lemma one_mem_commProdSet (l : List Q) : (1 : Q) ∈ commProdSet D l := by
  refine ⟨List.replicate l.length 1, by simp, fun d hd => ?_, ?_⟩
  · rw [List.eq_of_mem_replicate hd]; exact D.one_mem
  · induction l with
    | nil => simp
    | cons x l ih => simp [List.replicate_succ, ← ih]

lemma mul_mem_commProdSet (l : List Q) {g h : Q} (hg : g ∈ commProdSet D l)
    (hh : h ∈ commProdSet D l) : g * h ∈ commProdSet D l := by
  obtain ⟨ds, hl, hds, rfl⟩ := hg
  obtain ⟨ds', hl', hds', rfl⟩ := hh
  induction l generalizing ds ds' with
  | nil => rw [commProd_nil_left, commProd_nil_left, one_mul]; exact one_mem_commProdSet _
  | cons x l ih =>
    cases ds with
    | nil => simp at hl
    | cons d ds =>
    cases ds' with
    | nil => simp at hl'
    | cons d' ds' =>
    have hd : d ∈ D := hds d (by simp)
    have hd' : d' ∈ D := hds' d' (by simp)
    obtain ⟨es, hel, hes, he⟩ := ih ds (by simpa using hl) (fun e he => hds e (by simp [he]))
      ds' (by simpa using hl') (fun e he => hds' e (by simp [he]))
    refine ⟨(d * d') :: es, by simpa using hel, ?_, ?_⟩
    · intro e he'
      rcases List.mem_cons.1 he' with rfl | he'
      · exact D.mul_mem hd hd'
      · exact hes e he'
    · rw [commProd_cons_cons, commProd_cons_cons, commProd_cons_cons, ← he,
        comm_mul_right_of_abelian hDn hDab x hd hd']
      have hm1 : commProd l ds ∈ D := commProd_mem hDn l (fun e he => hds e (by simp [he]))
      have hm2 : ⁅x, d'⁆ ∈ D := comm_mem_of_normal hDn x hd'
      calc ⁅x, d⁆ * commProd l ds * (⁅x, d'⁆ * commProd l ds')
          = ⁅x, d⁆ * (commProd l ds * ⁅x, d'⁆) * commProd l ds' := by group
        _ = ⁅x, d⁆ * (⁅x, d'⁆ * commProd l ds) * commProd l ds' := by rw [hDab _ hm1 _ hm2]
        _ = _ := by group

lemma inv_mem_commProdSet (l : List Q) {g : Q} (hg : g ∈ commProdSet D l) :
    g⁻¹ ∈ commProdSet D l := by
  obtain ⟨ds, hl, hds, rfl⟩ := hg
  induction l generalizing ds with
  | nil => rw [commProd_nil_left, inv_one]; exact one_mem_commProdSet _
  | cons x l ih =>
    cases ds with
    | nil => simp at hl
    | cons d ds =>
    have hd : d ∈ D := hds d (by simp)
    obtain ⟨es, hel, hes, he⟩ := ih ds (by simpa using hl) (fun e he => hds e (by simp [he]))
    refine ⟨d⁻¹ :: es, by simpa using hel, ?_, ?_⟩
    · intro e he'
      rcases List.mem_cons.1 he' with rfl | he'
      · exact D.inv_mem hd
      · exact hes e he'
    · rw [commProd_cons_cons, commProd_cons_cons, ← he, comm_inv_right_of_abelian hDn hDab x hd,
        mul_inv_rev]
      have hm1 : commProd l ds ∈ D := commProd_mem hDn l (fun e he => hds e (by simp [he]))
      have hm2 : ⁅x, d⁆ ∈ D := comm_mem_of_normal hDn x hd
      exact hDab _ (D.inv_mem hm1) _ (D.inv_mem hm2)

/-- The subgroup of products `∏ᵢ ⁅lᵢ, dᵢ⁆`. -/
def commProdSubgroup (l : List Q) : Subgroup Q where
  carrier := commProdSet D l
  one_mem' := one_mem_commProdSet l
  mul_mem' := mul_mem_commProdSet hDn hDab l
  inv_mem' := inv_mem_commProdSet hDn hDab l

omit hDn hDab in
lemma comm_mem_commProdSet_of_mem {l : List Q} {q : Q} (hq : q ∈ l) {d : Q} (hd : d ∈ D) :
    ⁅q, d⁆ ∈ commProdSet D l := by
  induction l with
  | nil => simp at hq
  | cons y l ih =>
    rcases List.mem_cons.1 hq with rfl | hl
    · refine ⟨d :: List.replicate l.length 1, by simp, ?_, ?_⟩
      · intro e he
        rcases List.mem_cons.1 he with rfl | he
        · exact hd
        · rw [List.eq_of_mem_replicate he]; exact D.one_mem
      · rw [commProd_cons_cons]
        have : commProd l (List.replicate l.length 1) = 1 := by
          clear ih
          induction l with
          | nil => simp
          | cons z l ih' => simp [List.replicate_succ, ih']
        rw [this, mul_one]
    · obtain ⟨es, hel, hes, he⟩ := ih hl
      refine ⟨1 :: es, by simpa using hel, ?_, ?_⟩
      · intro e he'
        rcases List.mem_cons.1 he' with rfl | he'
        · exact D.one_mem
        · exact hes e he'
      · rw [commProd_cons_cons, commutatorElement_one_right, one_mul, he]

/-- **Guralnick's lemma.**  If `D` is an abelian normal subgroup of `Q` and `Q` is generated by `D`
and the entries of the list `l`, then every element of `[Q, D]` is a product `∏ᵢ ⁅lᵢ, dᵢ⁆` with
all `dᵢ ∈ D`. -/
theorem commutator_abelian_normal_eq_prod (l : List Q)
    (hgen : Subgroup.closure ({x | x ∈ l} ∪ (D : Set Q)) = ⊤) :
    ∀ g ∈ ⁅(⊤ : Subgroup Q), D⁆, g ∈ commProdSet D l := by
  set W := commProdSubgroup hDn hDab l with hW
  have hWD : ∀ w ∈ W, w ∈ D := fun w hw => commProdSet_subset hDn l hw
  -- `T` = elements whose commutators with `D` lie in `W`
  let T : Subgroup Q :=
    { carrier := {q | ∀ d ∈ D, ⁅q, d⁆ ∈ W}
      one_mem' := fun d _ => by simp [W.one_mem]
      mul_mem' := by
        intro q₁ q₂ h₁ h₂ d hd
        have e : ⁅q₁ * q₂, d⁆ = ⁅q₁, ⁅q₂, d⁆⁆ * ⁅q₂, d⁆ * ⁅q₁, d⁆ := by
          simp only [commutatorElement_def]; group
        rw [e]
        exact W.mul_mem (W.mul_mem (h₁ _ (hWD _ (h₂ d hd))) (h₂ d hd)) (h₁ d hd)
      inv_mem' := by
        intro q h d hd
        have hd' : q⁻¹ * d * q ∈ D := by simpa using hDn.conj_mem d hd q⁻¹
        have e : ⁅q⁻¹, d⁆ = ⁅q, q⁻¹ * d * q⁆⁻¹ := by
          simp only [commutatorElement_def]; group
        rw [e]; exact W.inv_mem (h _ hd') }
  have hT : T = ⊤ := by
    rw [eq_top_iff, ← hgen, Subgroup.closure_le]
    rintro q (hq | hq)
    · intro d hd
      exact comm_mem_commProdSet_of_mem hq hd
    · intro d hd
      have : ⁅q, d⁆ = 1 := by
        rw [commutatorElement_eq_one_iff_mul_comm]; exact hDab _ hq _ hd
      rw [this]; exact W.one_mem
  intro g hg
  have hle : ⁅(⊤ : Subgroup Q), D⁆ ≤ W := by
    rw [Subgroup.commutator_le]
    intro q _ d hd
    have : q ∈ T := hT ▸ Subgroup.mem_top q
    exact this d hd
  exact hle hg

end Abelian

/-- **Guralnick's lemma, relative form.**  Let `N ≤ E` be normal subgroups of `Q` with
`⁅E, E⁆ ≤ N`, and suppose `Q` is generated by `E` and the entries of the list `l`.  Then every
element of `[Q, E]` has the form `(∏ᵢ ⁅lᵢ, dᵢ⁆) * n` with all `dᵢ ∈ E` and `n ∈ N`. -/
theorem exists_commutator_product {N E : Subgroup Q} [hN : N.Normal] (hE : E.Normal)
    (hEE : ⁅E, E⁆ ≤ N) (l : List Q)
    (hgen : Subgroup.closure ({x | x ∈ l} ∪ (E : Set Q)) = ⊤) :
    ∀ g ∈ ⁅(⊤ : Subgroup Q), E⁆, ∃ ds : List Q, ds.length = l.length ∧ (∀ d ∈ ds, d ∈ E) ∧
      ∃ n ∈ N, g = commProd l ds * n := by
  classical
  intro g hg
  set π := QuotientGroup.mk' N with hπ
  have hsurj : Function.Surjective π := QuotientGroup.mk'_surjective N
  set D := E.map π with hD
  have hDn : D.Normal := hE.map π hsurj
  have hDab : ∀ a ∈ D, ∀ b ∈ D, a * b = b * a := by
    rintro _ ⟨a, ha, rfl⟩ _ ⟨b, hb, rfl⟩
    rw [← map_mul, ← map_mul]
    have hc : ⁅a, b⁆ ∈ N := hEE (Subgroup.commutator_mem_commutator ha hb)
    rw [hπ, QuotientGroup.mk'_apply, QuotientGroup.mk'_apply, QuotientGroup.eq]
    have : (a * b)⁻¹ * (b * a) = (b⁻¹ * a⁻¹) * ⁅a, b⁆⁻¹ * (b⁻¹ * a⁻¹)⁻¹ := by
      simp only [commutatorElement_def]; group
    rw [this]; exact hN.conj_mem _ (N.inv_mem hc) _
  have hgen' : Subgroup.closure ({y | y ∈ l.map π} ∪ (D : Set (Q ⧸ N))) = ⊤ := by
    have := congrArg (Subgroup.map π) hgen
    rw [MonoidHom.map_closure, Subgroup.map_top_of_surjective π hsurj] at this
    rw [← this]
    congr 1
    rw [Set.image_union]
    congr 1
    ext y; simp
  have hg' : π g ∈ ⁅(⊤ : Subgroup (Q ⧸ N)), D⁆ := by
    have := Subgroup.map_commutator (⊤ : Subgroup Q) E π
    rw [Subgroup.map_top_of_surjective π hsurj] at this
    rw [hD, ← this]
    exact Subgroup.mem_map_of_mem π hg
  obtain ⟨dsb, hlen, hdsb, hgd⟩ := commutator_abelian_normal_eq_prod hDn hDab _ hgen' _ hg'
  -- lift each entry of `dsb` to `E`
  have hlift : ∀ y : Q ⧸ N, ∃ e : Q, (y ∈ D → e ∈ E ∧ π e = y) := fun y => by
    by_cases hy : y ∈ D
    · obtain ⟨e, he, h⟩ := hy; exact ⟨e, fun _ => ⟨he, h⟩⟩
    · exact ⟨1, fun h => absurd h hy⟩
  choose lift hlift using hlift
  refine ⟨dsb.map lift, by simpa using hlen, ?_, ?_⟩
  · intro e he
    obtain ⟨y, hy, rfl⟩ := List.mem_map.1 he
    exact (hlift y (hdsb y hy)).1
  · refine ⟨(commProd l (dsb.map lift))⁻¹ * g, ?_, by group⟩
    have hmap : (dsb.map lift).map π = dsb := by
      rw [List.map_map]
      conv_rhs => rw [← List.map_id dsb]
      apply List.map_congr_left
      intro y hy
      exact (hlift y (hdsb y hy)).2
    rw [← QuotientGroup.eq_one_iff (N := N)]
    change π ((commProd l (dsb.map lift))⁻¹ * g) = 1
    rw [map_mul, map_inv, map_commProd, hmap, ← hgd, inv_mul_cancel]

end Tointon
