module
public import Mathlib
public import RequestProject.FiniteTrapping
public import RequestProject.CompactSetUltralimit
public import RequestProject.NSSRelativeTrapping
public import RequestProject.WeakPeterWeyl

/-!
# Subgroup trapping

Let `G` be a locally compact Hausdorff group with a countable neighbourhood basis at the identity.

* `Lovasz.Trapping.exists_smallSubgroups_closure_subset`: for every symmetric open identity
  neighbourhood `U` with compact closure there is an open identity neighbourhood `V` such that the
  subgroup generated by all subgroups contained in `V` lies in `U`.
* `Lovasz.Trapping.subgroup_trapping`: for every open `O ∋ 1` there are an open `V ∋ 1` and a
  compact subgroup `H ⊆ O` containing every subgroup contained in `V`.
* `Lovasz.Trapping.exists_open_subgroup_nss_quotient`: for every open `U ∋ 1` there are a compact
  subgroup `N ⊆ U` and an open subgroup `L₀ ⊇ N` normalising `N` with `L₀ ⧸ N` NSS.  This is
  `PeterWeyl.exists_open_subgroup_nss_quotient_of_trapping` with its trapping hypothesis
  discharged.

The proof follows the ultrafilter/buffer argument: the first-exit powers `S i = Q(V i)^(r i)` have
an ultralimit `E` whose powers stay in `closure U ^ 4` (finite trapping), so `E` generates a
compact subgroup `H`; the compact NSS quotient of `H` gives a buffer `R`; the first exits `g i`
from `R` converge to `h ∈ H \ R`, while finite trapping at `R` forces all small powers of `h` into
`closure (R⁸)`, whence `h ∈ R` by buffered power trapping.  No metric and no Hausdorff distance
is used.
-/

@[expose] public section

open scoped Pointwise Topology
open Filter

namespace Lovasz.Trapping

variable {G : Type*} [Group G]

lemma smallSubgroupUnion_mono {V V' : Set G} (h : V ⊆ V') :
    smallSubgroupUnion V ⊆ smallSubgroupUnion V' := by
  rintro g ⟨H, hHV, hgH⟩; exact ⟨H, hHV.trans h, hgH⟩

lemma one_mem_smallSubgroupUnion {V : Set G} (h1 : (1 : G) ∈ V) :
    (1 : G) ∈ smallSubgroupUnion V :=
  ⟨⊥, by simpa using h1, Subgroup.one_mem _⟩

lemma smallSubgroupUnion_inv (V : Set G) : (smallSubgroupUnion V)⁻¹ = smallSubgroupUnion V := by
  ext g
  constructor
  · rintro ⟨H, hHV, hgH⟩; exact ⟨H, hHV, by simpa using H.inv_mem hgH⟩
  · rintro ⟨H, hHV, hgH⟩; exact ⟨H, hHV, H.inv_mem hgH⟩

lemma smallSubgroupUnion_subset (V : Set G) : smallSubgroupUnion V ⊆ V := by
  rintro _ ⟨H, hHV, hgH⟩; exact hHV hgH

lemma subgroup_subset_smallSubgroupUnion {V : Set G} (P : Subgroup G) (hP : (P : Set G) ⊆ V) :
    (P : Set G) ⊆ smallSubgroupUnion V := fun _ hg => ⟨P, hP, hg⟩

/-- The subgroup generated by a symmetric set `Q` is `⋃ₙ Qⁿ`; in particular it lies in `U`
if all powers do. -/
lemma closure_subset_of_pow_subset {Q U : Set G} (hQinv : Q⁻¹ = Q)
    (h : ∀ n : ℕ, Q ^ n ⊆ U) : (Subgroup.closure Q : Set G) ⊆ U := by
  let P : Subgroup G :=
    { carrier := {g | ∃ n : ℕ, g ∈ Q ^ n}
      one_mem' := ⟨0, by simp⟩
      mul_mem' := by
        rintro a b ⟨m, ha⟩ ⟨n, hb⟩
        exact ⟨m + n, by rw [pow_add]; exact Set.mul_mem_mul ha hb⟩
      inv_mem' := by
        rintro a ⟨n, ha⟩
        refine ⟨n, ?_⟩
        rw [← hQinv, inv_pow]
        exact Set.inv_mem_inv.2 ha }
  have hle : Subgroup.closure Q ≤ P :=
    (Subgroup.closure_le P).2 fun q hq => ⟨1, by simpa using hq⟩
  rintro g hg
  obtain ⟨n, hn⟩ := hle hg
  exact h n hn

variable [TopologicalSpace G] [IsTopologicalGroup G] [T2Space G] [LocallyCompactSpace G]

omit [IsTopologicalGroup G] [T2Space G] [LocallyCompactSpace G] in
/-- A shrinking sequence of open identity neighbourhoods inside `U`: for a first-countable group,
every identity neighbourhood eventually contains `V i`. -/
lemma exists_shrinking_open_nhds [FirstCountableTopology G] {U : Set G} (hUo : IsOpen U)
    (hU1 : (1 : G) ∈ U) :
    ∃ V : ℕ → Set G, (∀ i, IsOpen (V i)) ∧ (∀ i, (1 : G) ∈ V i) ∧ (∀ i, V i ⊆ U) ∧
      ∀ W ∈ 𝓝 (1 : G), ∀ᶠ i in (hyperfilter ℕ : Filter ℕ), V i ⊆ W := by
  obtain ⟨x, hx⟩ := (𝓝 (1 : G)).exists_antitone_basis
  refine ⟨fun i => interior (x i) ∩ U, fun i => isOpen_interior.inter hUo,
    fun i => ⟨mem_interior_iff_mem_nhds.2 (hx.mem i), hU1⟩, fun i => Set.inter_subset_right, ?_⟩
  intro W hW
  obtain ⟨i₀, -, hi₀⟩ := hx.1.mem_iff.1 hW
  have : ∀ᶠ i in (cofinite : Filter ℕ), interior (x i) ∩ U ⊆ W := by
    rw [Nat.cofinite_eq_atTop]
    exact eventually_atTop.2 ⟨i₀, fun i hi =>
      Set.inter_subset_left.trans (interior_subset.trans ((hx.antitone hi).trans hi₀))⟩
  exact hyperfilter_le_cofinite this

/-- **Subgroup trapping, core form.**  In a first-countable locally compact Hausdorff group, for
every symmetric open identity neighbourhood `U` with compact closure there is an open identity
neighbourhood `V` such that the subgroup generated by all subgroups contained in `V` lies in
`U`. -/
theorem exists_smallSubgroups_closure_subset [FirstCountableTopology G] {U : Set G}
    (hUo : IsOpen U) (hU1 : (1 : G) ∈ U) (hUinv : U⁻¹ = U) (hUc : IsCompact (closure U)) :
    ∃ V : Set G, IsOpen V ∧ (1 : G) ∈ V ∧
      (Subgroup.closure (smallSubgroupUnion V) : Set G) ⊆ U := by
  classical
  by_contra hcon
  push_neg at hcon
  obtain ⟨V, hVo, hV1, hVU, hVev⟩ := exists_shrinking_open_nhds hUo hU1
  set 𝒰 := hyperfilter ℕ with h𝒰
  set Q : ℕ → Set G := fun i => smallSubgroupUnion (V i) with hQdef
  have hQinv : ∀ i, (Q i)⁻¹ = Q i := fun i => smallSubgroupUnion_inv _
  have hQ1 : ∀ i, (1 : G) ∈ Q i := fun i => one_mem_smallSubgroupUnion (hV1 i)
  have hQV : ∀ i, Q i ⊆ V i := fun i => smallSubgroupUnion_subset _
  have hQU : ∀ i, Q i ⊆ U := fun i => (hQV i).trans (hVU i)
  -- eventual trapping inside any neighbourhood
  have hQev : ∀ W ∈ 𝓝 (1 : G), ∀ᶠ i in (𝒰 : Filter ℕ),
      Q i ⊆ smallSubgroupUnion W := fun W hW =>
    (hVev W hW).mono fun i hi => smallSubgroupUnion_mono hi
  -- first exit from `U`
  have hexit : ∀ i, ∃ n : ℕ, ¬ Q i ^ n ⊆ U := by
    intro i
    by_contra h
    push_neg at h
    exact hcon (V i) (hVo i) (hV1 i) (closure_subset_of_pow_subset (hQinv i) h)
  set e : ℕ → ℕ := fun i => Nat.find (hexit i) with hedef
  have he0 : ∀ i, e i ≠ 0 := by
    intro i h0
    have : ¬ Q i ^ e i ⊆ U := Nat.find_spec (hexit i)
    rw [h0] at this
    exact this (by simpa using hU1)
  have he1 : ∀ i, e i ≠ 1 := by
    intro i h1
    have : ¬ Q i ^ e i ⊆ U := Nat.find_spec (hexit i)
    rw [h1, pow_one] at this
    exact this (hQU i)
  obtain ⟨r, hr⟩ : ∃ r : ℕ → ℕ, ∀ i, r i = e i - 1 := ⟨fun i => e i - 1, fun _ => rfl⟩
  have hr1 : ∀ i, 1 ≤ r i := fun i => by have := he0 i; have := he1 i; have := hr i; omega
  have hrU : ∀ i, Q i ^ r i ⊆ U := fun i => by
    have := Nat.find_min (hexit i) (show r i < e i by have := he0 i; have := hr i; omega)
    simpa using this
  have hrexit : ∀ i, ¬ Q i ^ (r i + 1) ⊆ U := fun i => by
    have : ¬ Q i ^ e i ⊆ U := Nat.find_spec (hexit i)
    rwa [show r i + 1 = e i by have := he0 i; have := hr i; omega]
  set S : ℕ → Set G := fun i => Q i ^ r i with hSdef
  have hS1 : ∀ i, (1 : G) ∈ S i := fun i => Set.one_mem_pow (hQ1 i)
  have hSinv : ∀ i, (S i)⁻¹ = S i := fun i => by
    simp only [hSdef]; rw [← inv_pow, hQinv]
  have hSU : ∀ i, S i ⊆ U := hrU
  -- the ultralimit `E` and the compact subgroup `H` it generates
  set E := Ultralimit.ultraLimSet 𝒰 S with hEdef
  have hE1 : (1 : G) ∈ E := Ultralimit.one_mem_ultraLimSet (Eventually.of_forall hS1)
  have hEinv : E⁻¹ = E := Ultralimit.ultraLimSet_inv_eq (Eventually.of_forall hSinv)
  set C := closure U ^ 4 with hCdef
  have hCc : IsCompact C := isCompact_pow hUc 4
  have hEpow : ∀ a : ℕ, E ^ a ⊆ C := by
    intro a
    obtain ⟨V', hV'o, hV'1, -, -, htrap⟩ := finite_trapping hUo hU1 hUinv hUc a
    refine Ultralimit.ultraLimSet_pow_subset hCc.isClosed a ?_
    filter_upwards [hQev V' (hV'o.mem_nhds hV'1)] with i hi
    have := htrap (Q i) (hQinv i) (hQ1 i) hi (r i) (hr1 i) (hrU i)
    simp only [hSdef]
    rw [← pow_mul, mul_comm]
    exact this.trans (Set.pow_subset_pow_left subset_closure)
  set H := (Subgroup.closure E).topologicalClosure with hHdef
  have hHC : (H : Set G) ⊆ C := by
    rw [hHdef, Subgroup.topologicalClosure_coe]
    exact closure_minimal (closure_subset_of_pow_subset hEinv hEpow) hCc.isClosed
  have hHc : IsCompact (H : Set G) :=
    hCc.of_isClosed_subset (Subgroup.isClosed_topologicalClosure _) hHC
  have hEH : E ⊆ H := fun x hx =>
    Subgroup.le_topologicalClosure _ (Subgroup.subset_closure hx)
  -- the compact NSS quotient of `H` and the buffer `R`
  obtain ⟨N, hNH, hNc, -, hNU, O₁, hO₁, hNO₁, -, hnss⟩ :=
    PeterWeyl.exists_compact_normal_nss_of_compact_subgroup hHc hUo hU1
  obtain ⟨R, hRo, hRinv, hRc, hNR, hRU, k, hk, htrapR⟩ :=
    NSS.exists_buffered_power_trapping hHc hNc hUo hNU hO₁ hNO₁ hnss
  have h1R : (1 : G) ∈ R := hNR N.one_mem
  -- first exit from `R`
  have hexitR : ∀ i, ∃ t : ℕ, ¬ Q i ^ t ⊆ R := fun i =>
    ⟨r i + 1, fun h => hrexit i (h.trans hRU)⟩
  set t : ℕ → ℕ := fun i => Nat.find (hexitR i) with htdef
  have ht0 : ∀ i, t i ≠ 0 := by
    intro i h0
    have : ¬ Q i ^ t i ⊆ R := Nat.find_spec (hexitR i)
    rw [h0] at this
    exact this (by simpa using h1R)
  have htr : ∀ i, t i ≤ r i + 1 := fun i =>
    Nat.find_min' (hexitR i) (fun h => hrexit i (h.trans hRU))
  have htR : ∀ i, Q i ^ (t i - 1) ⊆ R := fun i => by
    have := Nat.find_min (hexitR i) (show t i - 1 < t i by have := ht0 i; omega)
    simpa using this
  have hg : ∀ i, ∃ g, g ∈ Q i ^ t i ∧ g ∉ R := fun i => by
    have := Nat.find_spec (hexitR i)
    exact Set.not_subset.1 this
  choose g hgQ hgR using hg
  have hgSS : ∀ i, ∃ a ∈ S i, ∃ b ∈ S i, a * b = g i := by
    intro i
    have hsub : Q i ^ t i ⊆ S i * S i := by
      simp only [hSdef]
      rw [← pow_add]
      exact Set.pow_subset_pow_right (hQ1 i) (by have := htr i; have := hr1 i; omega)
    exact hsub (hgQ i)
  choose a ha b hb hab using hgSS
  -- limits
  have hUcl : ∀ i, S i ⊆ closure U := fun i => (hSU i).trans subset_closure
  obtain ⟨α, -, hα⟩ := Ultralimit.exists_tendsto_of_isCompact (𝒰 := 𝒰) hUc
    (Eventually.of_forall fun i => hUcl i (ha i))
  obtain ⟨β, -, hβ⟩ := Ultralimit.exists_tendsto_of_isCompact (𝒰 := 𝒰) hUc
    (Eventually.of_forall fun i => hUcl i (hb i))
  have hαE : α ∈ E := Ultralimit.mem_ultraLimSet_of_tendsto (Eventually.of_forall ha) hα
  have hβE : β ∈ E := Ultralimit.mem_ultraLimSet_of_tendsto (Eventually.of_forall hb) hβ
  have hglim : Tendsto g (𝒰 : Filter ℕ) (𝓝 (α * β)) := by
    have : g = fun i => a i * b i := funext fun i => (hab i).symm
    rw [this]; exact hα.mul hβ
  have hhH : α * β ∈ H := H.mul_mem (hEH hαE) (hEH hβE)
  have hhR : α * β ∉ R := fun hh => by
    obtain ⟨i, hi⟩ := (hglim.eventually (hRo.mem_nhds hh)).exists
    exact hgR i hi
  -- finite trapping at `R` forces the small powers of `α β` into `closure (R⁸)`
  obtain ⟨V'', hV''o, hV''1, -, -, htrap2⟩ := finite_trapping hRo h1R hRinv hRc (2 * k)
  have hevR : ∀ᶠ i in (𝒰 : Filter ℕ), Q i ⊆ R :=
    (hVev R (hRo.mem_nhds h1R)).mono fun i hi => (hQV i).trans hi
  have hpow : ∀ j : ℕ, 1 ≤ j → j ≤ k → (α * β) ^ j ∈ closure (R ^ 8) := by
    intro j hj hjk
    have hev : ∀ᶠ i in (𝒰 : Filter ℕ), g i ^ j ∈ closure (R ^ 8) := by
      filter_upwards [hevR, hQev V'' (hV''o.mem_nhds hV''1)] with i hiR hiV
      have ht2 : 2 ≤ t i := by
        by_contra hlt
        have h1 : t i = 1 := by have := ht0 i; omega
        have : ¬ Q i ^ t i ⊆ R := Nat.find_spec (hexitR i)
        rw [h1, pow_one] at this
        exact this hiR
      have hsub := htrap2 (Q i) (hQinv i) (hQ1 i) hiV (t i - 1) (by omega) (htR i)
      have hmem : g i ^ j ∈ Q i ^ (t i * j) := by
        rw [pow_mul]; exact Set.pow_mem_pow (hgQ i)
      have hle : t i * j ≤ 2 * k * (t i - 1) := by
        obtain ⟨s, hs⟩ : ∃ s, t i = s + 2 := ⟨t i - 2, by omega⟩
        rw [hs, show s + 2 - 1 = s + 1 by omega]
        nlinarith
      have h48 : R ^ 4 ⊆ R ^ 8 := Set.pow_subset_pow_right h1R (by norm_num)
      exact subset_closure (h48 (hsub (Set.pow_subset_pow_right (hQ1 i) hle hmem)))
    exact isClosed_closure.mem_of_tendsto (hglim.pow j) hev
  exact hhR (htrapR _ hhH hpow)

/-- **Subgroup trapping.**  In a first-countable locally compact Hausdorff group, for every open
`O ∋ 1` there are an open `V ∋ 1` and a compact subgroup `H ⊆ O` such that every subgroup contained
in `V` lies in `H`. -/
theorem subgroup_trapping [FirstCountableTopology G] {O : Set G} (hO : IsOpen O)
    (h1 : (1 : G) ∈ O) :
    ∃ V : Set G, IsOpen V ∧ (1 : G) ∈ V ∧ V ⊆ O ∧ ∃ H : Subgroup G, IsCompact (H : Set G) ∧
      (H : Set G) ⊆ O ∧ ∀ P : Subgroup G, (P : Set G) ⊆ V → P ≤ H := by
  obtain ⟨W, hWo, h1W, hWcl, hWc⟩ :=
    exists_open_between_and_isCompact_closure isCompact_singleton hO
      (Set.singleton_subset_iff.2 h1)
  set U := W ∩ W⁻¹ with hUdef
  have hUo : IsOpen U := hWo.inter hWo.inv
  have hU1 : (1 : G) ∈ U := ⟨h1W rfl, by simpa using h1W rfl⟩
  have hUinv : U⁻¹ = U := by rw [hUdef, Set.inter_inv, inv_inv, Set.inter_comm]
  have hUcl : closure U ⊆ closure W := closure_mono Set.inter_subset_left
  have hUc : IsCompact (closure U) := hWc.of_isClosed_subset isClosed_closure hUcl
  obtain ⟨V, hVo, hV1, hVsub⟩ := exists_smallSubgroups_closure_subset hUo hU1 hUinv hUc
  set H := (Subgroup.closure (smallSubgroupUnion V)).topologicalClosure with hHdef
  have hHU : (H : Set G) ⊆ closure U := by
    rw [hHdef, Subgroup.topologicalClosure_coe]; exact closure_mono hVsub
  refine ⟨V ∩ O, hVo.inter hO, ⟨hV1, h1⟩, Set.inter_subset_right, H,
    hUc.of_isClosed_subset (Subgroup.isClosed_topologicalClosure _) hHU,
    hHU.trans (hUcl.trans hWcl), ?_⟩
  intro P hP p hp
  exact Subgroup.le_topologicalClosure _
    (Subgroup.subset_closure (subgroup_subset_smallSubgroupUnion P
      (hP.trans Set.inter_subset_left) hp))

/-- **Locally compact NSS quotient.**  In a first-countable locally compact Hausdorff group, for
every open `U ∋ 1` there are a compact subgroup `N ⊆ U` and an open subgroup `L₀ ⊇ N` normalising
`N` such that `L₀ ⧸ N` has no small subgroups.  (No trapping hypothesis remains.) -/
theorem exists_open_subgroup_nss_quotient [FirstCountableTopology G] {U : Set G}
    (hU : IsOpen U) (h1 : (1 : G) ∈ U) :
    ∃ N : Subgroup G, IsCompact (N : Set G) ∧ (N : Set G) ⊆ U ∧
      ∃ L₀ : Subgroup G, IsOpen (L₀ : Set G) ∧ N ≤ L₀ ∧
        ∃ _ : (N.subgroupOf L₀).Normal, NSS.HasNoSmallSubgroups (L₀ ⧸ N.subgroupOf L₀) := by
  obtain ⟨V, hVo, hV1, hVU, H, hHc, -, htrap⟩ := subgroup_trapping hU h1
  obtain ⟨N, hNc, hNV, hrest⟩ :=
    PeterWeyl.exists_open_subgroup_nss_quotient_of_trapping hHc hVo hV1 htrap
  exact ⟨N, hNc, hNV.trans hVU, hrest⟩

end Lovasz.Trapping
