module
public import Mathlib

/-!
# Generation of subgroups of finite abelian groups of bounded rank

This file contains the abelian-group input of Tointon's normal-closure argument
(*Freiman's theorem in an arbitrary nilpotent group*, Section 6):

* `exists_finset_closure_eq_of_le_closure`: a subgroup of a group generated by `d` elements is
  itself generated by `d` elements (commutative case);
* `exists_subset_closure_eq_of_pgroup`: a "Nakayama lemma" for abelian `p`-groups: if a
  subgroup `S` of exponent dividing `p^a` is generated by `d` elements and also by a set `T`, then
  it is generated by at most `d` elements of `T`;
* `closure_image_subset_pow` (**Proposition 6.1** of Tointon, bilinear case): if the image `T` of
  a bimultiplicative map from two groups into a finite abelian group lies in a subgroup generated
  by `d` elements, then the subgroup generated by `T` is `T^d`.
-/

@[expose] public section

open scoped Pointwise

namespace Tointon

section Rank

variable {Q : Type*} [CommGroup Q]

/-- In a commutative group, a subgroup of a subgroup generated by `d` elements is generated by
at most `d` elements. -/
theorem exists_finset_closure_eq_of_le_closure [DecidableEq Q] (X : Finset Q) :
    ∀ S : Subgroup Q, S ≤ Subgroup.closure (X : Set Q) →
      ∃ Y : Finset Q, Y.card ≤ X.card ∧ Subgroup.closure (Y : Set Q) = S := by
  induction X using Finset.induction_on with
  | empty =>
    intro S hS
    refine ⟨∅, by simp, ?_⟩
    simp only [Finset.coe_empty, Subgroup.closure_empty] at hS ⊢
    exact (le_bot_iff.1 hS).symm
  | @insert x X hx ih =>
    intro S hS
    obtain ⟨Y', hY'card, hY'⟩ := ih (S ⊓ Subgroup.closure (X : Set Q)) inf_le_right
    set f := QuotientGroup.mk' (Subgroup.closure (X : Set Q)) with hf
    have hmap : S.map f ≤ Subgroup.zpowers (f x) := by
      have h1 : S.map f ≤ (Subgroup.closure ((insert x X : Finset Q) : Set Q)).map f :=
        Subgroup.map_mono hS
      refine h1.trans ?_
      rw [MonoidHom.map_closure, Subgroup.closure_le]
      rintro _ ⟨y, hy, rfl⟩
      simp only [Finset.coe_insert, Set.mem_insert_iff, Finset.mem_coe] at hy
      rcases hy with rfl | hy
      · exact Subgroup.mem_zpowers _
      · have : f y = 1 := by
          rw [hf, QuotientGroup.mk'_apply, QuotientGroup.eq_one_iff]
          exact Subgroup.subset_closure hy
        rw [SetLike.mem_coe, this]; exact one_mem _
    obtain ⟨n, hn⟩ := (Subgroup.le_zpowers_iff _ _).1 hmap
    have hmem : f x ^ n ∈ S.map f := by rw [hn]; exact Subgroup.mem_zpowers _
    obtain ⟨s, hsS, hs⟩ := hmem
    refine ⟨insert s Y', ?_, ?_⟩
    · rw [Finset.card_insert_of_notMem hx]
      exact (Finset.card_insert_le _ _).trans (by omega)
    apply le_antisymm
    · rw [Subgroup.closure_le]
      intro y hy
      simp only [Finset.coe_insert, Set.mem_insert_iff, Finset.mem_coe] at hy
      rcases hy with rfl | hy
      · exact hsS
      · have : y ∈ S ⊓ Subgroup.closure (X : Set Q) := by
          rw [← hY']; exact Subgroup.subset_closure hy
        exact this.1
    · intro t ht
      have hft : f t ∈ Subgroup.zpowers (f s) := by
        rw [hs, ← hn]; exact Subgroup.mem_map_of_mem f ht
      obtain ⟨k, hk⟩ := Subgroup.mem_zpowers_iff.1 hft
      have hker : t * (s ^ k)⁻¹ ∈ Subgroup.closure (X : Set Q) := by
        rw [← QuotientGroup.eq_one_iff (N := Subgroup.closure (X : Set Q))]
        have : f (t * (s ^ k)⁻¹) = 1 := by
          rw [map_mul, map_inv, map_zpow, hk, mul_inv_cancel]
        simpa [hf] using this
      have hin : t * (s ^ k)⁻¹ ∈ Subgroup.closure (Y' : Set Q) := by
        rw [hY']; exact ⟨S.mul_mem ht (S.inv_mem (S.zpow_mem hsS k)), hker⟩
      have e : t = t * (s ^ k)⁻¹ * s ^ k := by group
      rw [e]
      refine Subgroup.mul_mem _ ?_ ?_
      · exact Subgroup.closure_mono (by simp) hin
      · exact Subgroup.zpow_mem _ (Subgroup.subset_closure (by simp)) k

/-- Elements of the subgroup generated by a finite set in a commutative group are products of
integer powers of its elements. -/
lemma exists_zpow_of_mem_closure (X : Finset Q) {x : Q}
    (hx : x ∈ Subgroup.closure (X : Set Q)) : ∃ n : Q → ℤ, x = ∏ y ∈ X, y ^ n y := by
  classical
  induction hx using Subgroup.closure_induction with
  | mem y hy => exact ⟨fun z => if z = y then 1 else 0, by
      rw [Finset.prod_eq_single y (fun b _ hb => by simp [hb]) (fun h => absurd hy h)]; simp⟩
  | one => exact ⟨0, by simp⟩
  | mul a b _ _ ha hb =>
    obtain ⟨n, rfl⟩ := ha
    obtain ⟨m, rfl⟩ := hb
    exact ⟨n + m, by rw [← Finset.prod_mul_distrib]; simp [zpow_add]⟩
  | inv a _ ha =>
    obtain ⟨n, rfl⟩ := ha
    exact ⟨-n, by simp [Finset.prod_inv_distrib, zpow_neg]⟩

end Rank

section PGroup

variable {Q : Type*} [CommGroup Q]

/-- The subgroup of `p`-th powers of elements of `S`. -/
def powSub (S : Subgroup Q) (p : ℕ) : Subgroup Q := S.map (powMonoidHom p)

lemma mem_powSub {S : Subgroup Q} {p : ℕ} {x : Q} :
    x ∈ powSub S p ↔ ∃ s ∈ S, s ^ p = x := by
  simp [powSub]

lemma powSub_le (S : Subgroup Q) (p : ℕ) : powSub S p ≤ S := by
  rintro _ ⟨s, hs, rfl⟩; exact S.pow_mem hs p

/-- Frattini argument for abelian `p`-groups: if `R · S^p = S` and `S` has exponent dividing
`p^a`, then `R = S`. -/
lemma eq_of_sup_powSub_eq {S R : Subgroup Q} {p a : ℕ} (hexp : ∀ s ∈ S, s ^ (p ^ a) = 1)
    (hRS : R ≤ S) (hsup : R ⊔ powSub S p = S) : R = S := by
  apply le_antisymm hRS
  have key : ∀ k : ℕ, ∀ s ∈ S, ∃ r ∈ R, ∃ u ∈ S, s = r * u ^ (p ^ k) := by
    intro k
    induction k with
    | zero => intro s hs; exact ⟨1, one_mem _, s, hs, by simp⟩
    | succ k ih =>
      intro s hs
      obtain ⟨r, hr, u, hu, rfl⟩ := ih s hs
      have hu' : u ∈ R ⊔ powSub S p := by rw [hsup]; exact hu
      obtain ⟨r', hr', v, hv, huv⟩ := Subgroup.mem_sup.1 hu'
      obtain ⟨w, hw, rfl⟩ := mem_powSub.1 hv
      refine ⟨r * r' ^ (p ^ k), R.mul_mem hr (R.pow_mem hr' _), w, hw, ?_⟩
      rw [← huv, mul_pow, ← pow_mul, pow_succ, mul_comm (p ^ k) p, mul_assoc]
  intro s hs
  obtain ⟨r, hr, u, hu, rfl⟩ := key a s hs
  rw [hexp u hu, mul_one]; exact hr

/-- The index of the `p`-th powers in a subgroup generated by `d` elements is at most `p^d`. -/
lemma card_le_pow_mul_card_powSub [Finite Q] {S : Subgroup Q} {p : ℕ} (hp : 0 < p) (Y : Finset Q)
    (hY : Subgroup.closure (Y : Set Q) = S) :
    Nat.card S ≤ p ^ Y.card * Nat.card (powSub S p) := by
  classical
  let F : (Y → Fin p) × powSub S p → Q := fun e => (∏ y : Y, (y : Q) ^ ((e.1 y : ℕ))) * e.2
  have hsub : (S : Set Q) ⊆ Set.range F := by
    intro x hx
    rw [← hY] at hx
    obtain ⟨n, rfl⟩ := exists_zpow_of_mem_closure Y hx
    have hyS : ∀ y ∈ Y, y ∈ S := fun y hy => hY ▸ Subgroup.subset_closure hy
    -- write `n y = p * q y + r y`
    set q : Q → ℤ := fun y => n y / p
    set r : Q → ℕ := fun y => (n y % p).toNat
    have hr : ∀ y, (r y : ℤ) = n y % p := fun y =>
      Int.toNat_of_nonneg (Int.emod_nonneg _ (by exact_mod_cast hp.ne'))
    have hrlt : ∀ y, r y < p := fun y => by
      have := Int.emod_lt_of_pos (n y) (by exact_mod_cast hp : (0 : ℤ) < p)
      have h := hr y
      omega
    have hdecomp : ∀ y : Q, y ^ n y = y ^ r y * (y ^ q y) ^ p := fun y => by
      rw [← zpow_natCast, ← zpow_natCast, ← zpow_mul, ← zpow_add, hr y]
      congr 1
      rw [mul_comm]; exact (Int.emod_add_mul_ediv (n y) p).symm
    have hmemP : (∏ y ∈ Y, (y ^ q y) ^ p) ∈ powSub S p := by
      rw [mem_powSub]
      refine ⟨∏ y ∈ Y, y ^ q y, Subgroup.prod_mem _ fun y hy => S.zpow_mem (hyS y hy) _, ?_⟩
      rw [Finset.prod_pow]
    refine ⟨(fun y => ⟨r y, hrlt y⟩, ⟨_, hmemP⟩), ?_⟩
    simp only [F]
    rw [Finset.prod_congr rfl (fun y _ => hdecomp y), Finset.prod_mul_distrib]
    congr 1
    rw [← Finset.prod_coe_sort Y]
  have hfin : (Set.range F).Finite := Set.toFinite _
  calc Nat.card S = (S : Set Q).ncard := (Nat.card_coe_set_eq _)
    _ ≤ (Set.range F).ncard := Set.ncard_le_ncard hsub hfin
    _ ≤ Nat.card ((Y → Fin p) × powSub S p) := by
      rw [← Set.image_univ]
      exact (Set.ncard_image_le (Set.toFinite _)).trans (Set.ncard_univ _).le
    _ = p ^ Y.card * Nat.card (powSub S p) := by
      rw [Nat.card_prod, Nat.card_fun, Nat.card_eq_fintype_card (α := Fin p), Fintype.card_fin,
        Nat.card_eq_fintype_card (α := Y), Fintype.card_coe]

/-- Subgroups of a subgroup of exponent dividing `p^a` have `p`-power order. -/
lemma card_eq_prime_pow_of_le [Finite Q] {p a : ℕ} (hp : p.Prime) {S R : Subgroup Q}
    (hexp : ∀ s ∈ S, s ^ (p ^ a) = 1) (hRS : R ≤ S) : ∃ n, Nat.card R = p ^ n := by
  haveI := Fact.mk hp
  have : IsPGroup p R := fun g => ⟨a, Subtype.ext (by simpa using hexp g (hRS g.2))⟩
  exact IsPGroup.iff_card.1 this

/-- **Nakayama's lemma for abelian `p`-groups.**  If `S` has exponent dividing `p^a`, is
generated by `d` elements, and is generated by a set `T`, then `S` is generated by at most `d`
elements of `T`. -/
theorem exists_subset_closure_eq_of_pgroup [Finite Q] [DecidableEq Q] {p a d : ℕ} (hp : p.Prime)
    {S : Subgroup Q} (hexp : ∀ s ∈ S, s ^ (p ^ a) = 1) (Y : Finset Q) (hYc : Y.card ≤ d)
    (hY : Subgroup.closure (Y : Set Q) = S) (T : Set Q) (hT : Subgroup.closure T = S) :
    ∃ F : Finset Q, (F : Set Q) ⊆ T ∧ F.card ≤ d ∧ Subgroup.closure (F : Set Q) = S := by
  set Φ := powSub S p with hΦ
  have hTS : T ⊆ S := fun t ht => hT ▸ Subgroup.subset_closure ht
  have hRS : ∀ F : Finset Q, (F : Set Q) ⊆ T → Subgroup.closure (F : Set Q) ⊔ Φ ≤ S :=
    fun F hF => sup_le ((Subgroup.closure_le _).2 (hF.trans hTS)) (powSub_le S p)
  have claim : ∀ i : ℕ, ∃ F : Finset Q, (F : Set Q) ⊆ T ∧ F.card ≤ i ∧
      (Subgroup.closure (F : Set Q) ⊔ Φ = S ∨
        p ^ i * Nat.card Φ ≤ Nat.card (Subgroup.closure (F : Set Q) ⊔ Φ : Subgroup Q)) := by
    intro i
    induction i with
    | zero =>
      refine ⟨∅, by simp, by simp, Or.inr ?_⟩
      simp
    | succ i ih =>
      obtain ⟨F, hFT, hFc, hF⟩ := ih
      by_cases hfull : Subgroup.closure (F : Set Q) ⊔ Φ = S
      · exact ⟨F, hFT, by omega, Or.inl hfull⟩
      have hF' := hF.resolve_left hfull
      obtain ⟨t, htT, htR⟩ : ∃ t ∈ T, t ∉ Subgroup.closure (F : Set Q) ⊔ Φ := by
        by_contra! hall
        apply hfull
        refine le_antisymm (hRS F hFT) ?_
        rw [← hT, Subgroup.closure_le]; exact hall
      refine ⟨insert t F, ?_, (Finset.card_insert_le _ _).trans (by omega), Or.inr ?_⟩
      · rw [Finset.coe_insert]; exact Set.insert_subset htT hFT
      set R := Subgroup.closure (F : Set Q) ⊔ Φ
      set R' := Subgroup.closure ((insert t F : Finset Q) : Set Q) ⊔ Φ
      have hle : R ≤ R' := sup_le_sup_right (Subgroup.closure_mono (by simp)) _
      have hne : R ≠ R' := by
        intro h; apply htR; rw [h]
        exact Subgroup.mem_sup_left (Subgroup.subset_closure (by simp))
      have hdvd : Nat.card R ∣ Nat.card R' := Subgroup.card_dvd_of_le hle
      have hlt : Nat.card R < Nat.card R' := by
        refine lt_of_le_of_ne (Nat.le_of_dvd Nat.card_pos hdvd) ?_
        intro h; exact hne (Subgroup.eq_of_le_of_card_ge hle h.ge)
      obtain ⟨m, hm⟩ := card_eq_prime_pow_of_le hp hexp (hRS F hFT)
      obtain ⟨m', hm'⟩ := card_eq_prime_pow_of_le hp hexp
        (hRS (insert t F) (by rw [Finset.coe_insert]; exact Set.insert_subset htT hFT))
      rw [hm, hm'] at hlt
      have hmm : m < m' := (Nat.pow_lt_pow_iff_right hp.one_lt).1 hlt
      calc p ^ (i + 1) * Nat.card Φ = p * (p ^ i * Nat.card Φ) := by ring
        _ ≤ p * Nat.card R := Nat.mul_le_mul_left _ hF'
        _ = p ^ (m + 1) := by rw [hm, pow_succ, mul_comm]
        _ ≤ p ^ m' := Nat.pow_le_pow_right hp.pos hmm
        _ = Nat.card R' := hm'.symm
  obtain ⟨F, hFT, hFc, hF⟩ := claim d
  refine ⟨F, hFT, hFc, ?_⟩
  have hsup : Subgroup.closure (F : Set Q) ⊔ Φ = S := by
    rcases hF with h | h
    · exact h
    · apply Subgroup.eq_of_le_of_card_ge (hRS F hFT)
      have h1 := card_le_pow_mul_card_powSub hp.pos Y hY
      have h2 : p ^ Y.card ≤ p ^ d := Nat.pow_le_pow_right hp.pos hYc
      calc Nat.card S ≤ p ^ Y.card * Nat.card Φ := h1
        _ ≤ p ^ d * Nat.card Φ := Nat.mul_le_mul_right _ h2
        _ ≤ _ := h
  exact eq_of_sup_powSub_eq hexp (le_sup_left.trans (hRS F hFT)) hsup

end PGroup

section Mixing

variable {Q : Type*} [CommGroup Q]

/-- `T` is closed under natural powers. -/
def PowClosed (T : Set Q) : Prop := ∀ t ∈ T, ∀ n : ℕ, t ^ n ∈ T

/-- `T` is closed under "mixing" of coprime components with respect to a splitting `e = u v`. -/
def MixClosed (e : ℕ) (T : Set Q) : Prop :=
  ∀ u v : ℕ, Nat.Coprime u v → u * v = e → ∀ t ∈ T, ∀ t' ∈ T, ∃ w ∈ T, w ^ v = t ^ v ∧ w ^ u = t' ^ u

/-- A finset of size at most `d` inside a set containing `1` can be listed as a `d`-tuple. -/
lemma exists_tuple_of_finset (T : Set Q) (h1 : (1 : Q) ∈ T) (F : Finset Q) (hFT : (F : Set Q) ⊆ T)
    {d : ℕ} (hFd : F.card ≤ d) :
    ∃ f : Fin d → Q, (∀ i, f i ∈ T) ∧
      Subgroup.closure (Set.range f) = Subgroup.closure (F : Set Q) := by
  classical
  let f : Fin d → Q := fun i => if h : (i : ℕ) < F.card then (F.equivFin.symm ⟨i, h⟩ : Q) else 1
  refine ⟨f, fun i => ?_, le_antisymm ?_ ?_⟩
  · simp only [f]; split_ifs
    · exact hFT (Finset.coe_mem _)
    · exact h1
  · rw [Subgroup.closure_le]
    rintro _ ⟨i, rfl⟩
    simp only [f]; split_ifs
    · exact Subgroup.subset_closure (Finset.coe_mem _)
    · exact one_mem _
  · rw [Subgroup.closure_le]
    intro x hx
    set j := F.equivFin ⟨x, hx⟩
    refine Subgroup.subset_closure ⟨⟨j, lt_of_lt_of_le j.2 hFd⟩, ?_⟩
    have : f ⟨j, lt_of_lt_of_le j.2 hFd⟩ = (F.equivFin.symm ⟨j, j.2⟩ : Q) := dif_pos j.2
    rw [this]; simp [j]

/-- Integer Bezout for coprime naturals. -/
lemma exists_bezout {u v : ℕ} (h : Nat.Coprime u v) : ∃ α β : ℤ, α * u + β * v = 1 := by
  refine ⟨Nat.gcdA u v, Nat.gcdB u v, ?_⟩
  have := Nat.gcd_eq_gcd_ab u v
  rw [h] at this
  push_cast at this
  linarith

/-- If `u, v` are coprime and both `s^u` and `s^v` lie in a subgroup, then so does `s`. -/
lemma mem_of_pow_mem {R : Subgroup Q} {u v : ℕ} (h : Nat.Coprime u v) {s : Q}
    (hu : s ^ u ∈ R) (hv : s ^ v ∈ R) : s ∈ R := by
  obtain ⟨α, β, hab⟩ := exists_bezout h
  have e : s = (s ^ u) ^ α * (s ^ v) ^ β := by
    rw [← zpow_natCast, ← zpow_natCast, ← zpow_mul, ← zpow_mul, ← zpow_add, mul_comm (u : ℤ),
      mul_comm (v : ℤ), hab, zpow_one]
  rw [e]; exact R.mul_mem (R.zpow_mem hu _) (R.zpow_mem hv _)

/-- **Local–global generation.**  If `T` is nonempty, closed under powers and under mixing with
respect to an exponent `e` of the subgroup it generates, and this subgroup is generated by `d`
elements, then it is generated by `d` elements of `T`. -/
theorem exists_tuple_closure_eq [Finite Q] [DecidableEq Q] :
    ∀ e : ℕ, 0 < e → ∀ (T : Set Q), T.Nonempty → PowClosed T → MixClosed e T →
      (∀ s ∈ Subgroup.closure T, s ^ e = 1) → ∀ d : ℕ, ∀ Y : Finset Q, Y.card ≤ d →
      Subgroup.closure (Y : Set Q) = Subgroup.closure T →
      ∃ f : Fin d → Q, (∀ i, f i ∈ T) ∧ Subgroup.closure (Set.range f) = Subgroup.closure T := by
  intro e
  induction e using Nat.strong_induction_on with
  | _ e ih =>
  intro he T hTne hpow hmix hexp d Y hYd hY
  obtain ⟨t₀, ht₀⟩ := hTne
  have h1T : (1 : Q) ∈ T := by simpa using hpow t₀ ht₀ 0
  by_cases he1 : e = 1
  · subst he1
    refine ⟨fun _ => 1, fun _ => h1T, ?_⟩
    have hbot : Subgroup.closure T = ⊥ := by
      rw [eq_bot_iff]; intro s hs; simpa using hexp s hs
    rw [hbot, eq_bot_iff, Subgroup.closure_le]
    rintro _ ⟨_, rfl⟩; exact one_mem _
  -- split off the `p`-part of `e`
  set p := e.minFac with hpdef
  have hp : p.Prime := Nat.minFac_prime he1
  set a := e.factorization p
  set m := e / p ^ a with hmdef
  have hpam : p ^ a * m = e := Nat.ordProj_mul_ordCompl_eq_self e p
  have hcop : Nat.Coprime (p ^ a) m :=
    Nat.Coprime.pow_left _ (Nat.coprime_ordCompl hp he.ne')
  have ha : 1 ≤ a := by
    have : p ∣ e := Nat.minFac_dvd e
    exact (hp.dvd_iff_one_le_factorization he.ne').1 this
  have hm0 : 0 < m := Nat.pos_of_ne_zero (fun h => by rw [h, mul_zero] at hpam; omega)
  have hme : m < e := by
    have : 2 ≤ p ^ a := le_trans hp.two_le (Nat.le_self_pow (by omega) p)
    nlinarith
  -- the `m`-part
  set Tm := (fun t => t ^ (p ^ a)) '' T with hTm
  have hclTm : Subgroup.closure Tm = (Subgroup.closure T).map (powMonoidHom (p ^ a)) := by
    rw [MonoidHom.map_closure]; rfl
  obtain ⟨fm, hfmT, hfm⟩ : ∃ f : Fin d → Q, (∀ i, f i ∈ Tm) ∧
      Subgroup.closure (Set.range f) = Subgroup.closure Tm := by
    refine ih m hme hm0 Tm ⟨_, ⟨t₀, ht₀, rfl⟩⟩ ?_ ?_ ?_ d (Y.image (· ^ (p ^ a)))
      (Finset.card_image_le.trans hYd) ?_
    · rintro _ ⟨t, ht, rfl⟩ n
      refine ⟨t ^ n, hpow t ht n, ?_⟩
      show (t ^ n) ^ (p ^ a) = (t ^ (p ^ a)) ^ n
      rw [← pow_mul, ← pow_mul, mul_comm]
    · rintro u v huv huvm _ ⟨x, hx, rfl⟩ _ ⟨x', hx', rfl⟩
      have hc : Nat.Coprime (u * p ^ a) v := by
        refine Nat.Coprime.mul_left huv ?_
        exact Nat.Coprime.coprime_dvd_right (Dvd.intro_left u huvm) hcop
      obtain ⟨w, hw, hwv, hwu⟩ := hmix (u * p ^ a) v hc (by rw [← hpam, ← huvm]; ring) x hx x' hx'
      refine ⟨w ^ (p ^ a), ⟨w, hw, rfl⟩, ?_, ?_⟩
      · rw [← pow_mul, mul_comm, pow_mul, hwv, ← pow_mul, ← pow_mul, mul_comm]
      · rw [← pow_mul, mul_comm, hwu, ← pow_mul, mul_comm]
    · intro s hs
      rw [hclTm] at hs
      obtain ⟨y, hy, rfl⟩ := hs
      simp only [powMonoidHom_apply]
      rw [← pow_mul, hpam]; exact hexp y hy
    · rw [hclTm, Finset.coe_image]
      change Subgroup.closure ((powMonoidHom (p ^ a)) '' (Y : Set Q)) = _
      rw [← MonoidHom.map_closure, hY]
  -- the `p`-part
  set Tp := (fun t => t ^ m) '' T with hTp
  have hclTp : Subgroup.closure Tp = (Subgroup.closure T).map (powMonoidHom m) := by
    rw [MonoidHom.map_closure]; rfl
  obtain ⟨Fp, hFpT, hFpd, hFp⟩ := exists_subset_closure_eq_of_pgroup (a := a) hp
    (S := Subgroup.closure Tp) (by
      intro s hs
      rw [hclTp] at hs
      obtain ⟨y, hy, rfl⟩ := hs
      simp only [powMonoidHom_apply]
      rw [← pow_mul, mul_comm, hpam]; exact hexp y hy)
    (Y.image (· ^ m)) (Finset.card_image_le.trans hYd)
    (by
      rw [hclTp, Finset.coe_image]
      change Subgroup.closure ((powMonoidHom m) '' (Y : Set Q)) = _
      rw [← MonoidHom.map_closure, hY]) Tp rfl
  obtain ⟨fp, hfpT, hfp⟩ := exists_tuple_of_finset Tp (show (1 : Q) ∈ Tp from ⟨1, h1T, one_pow m⟩) Fp hFpT hFpd
  rw [hFp] at hfp
  -- mix
  choose x hx hxe using hfmT
  choose y hy hye using hfpT
  have hmix' : ∀ i, ∃ w ∈ T, w ^ (p ^ a) = x i ^ (p ^ a) ∧ w ^ m = y i ^ m := fun i =>
    hmix m (p ^ a) hcop.symm (by rw [← hpam, mul_comm]) (x i) (hx i) (y i) (hy i)
  choose w hwT hw1 hw2 using hmix'
  refine ⟨w, hwT, le_antisymm ?_ ?_⟩
  · rw [Subgroup.closure_le]; rintro _ ⟨i, rfl⟩; exact Subgroup.subset_closure (hwT i)
  · intro s hs
    refine mem_of_pow_mem hcop ?_ ?_
    · have : s ^ (p ^ a) ∈ Subgroup.closure Tm := by rw [hclTm]; exact ⟨s, hs, rfl⟩
      rw [← hfm] at this
      refine (Subgroup.closure_le _).2 ?_ this
      rintro _ ⟨i, rfl⟩
      rw [← hxe i]; dsimp only; rw [← hw1 i]
      exact Subgroup.pow_mem _ (Subgroup.subset_closure (Set.mem_range_self i)) _
    · have : s ^ m ∈ Subgroup.closure Tp := by rw [hclTp]; exact ⟨s, hs, rfl⟩
      rw [← hfp] at this
      refine (Subgroup.closure_le _).2 ?_ this
      rintro _ ⟨i, rfl⟩
      rw [← hye i]; dsimp only; rw [← hw2 i]
      exact Subgroup.pow_mem _ (Subgroup.subset_closure (Set.mem_range_self i)) _

end Mixing

section Bilinear

variable {Q : Type*} [CommGroup Q]

/-- A product of elements of `T` indexed by `Fin d` lies in `T^d`. -/
lemma prod_mem_pow {T : Set Q} : ∀ {d : ℕ} (g : Fin d → Q), (∀ i, g i ∈ T) → ∏ i, g i ∈ T ^ d
  | 0, _, _ => by simp
  | d + 1, g, hg => by
    rw [Fin.prod_univ_succ, pow_succ']
    exact Set.mul_mem_mul (hg 0) (prod_mem_pow _ fun i => hg i.succ)

lemma zpow_eq_zpow_of_dvd {e : ℕ} (he : ∀ z : Q, z ^ e = 1) (z : Q) {k l : ℤ}
    (h : (e : ℤ) ∣ k - l) : z ^ k = z ^ l := by
  obtain ⟨j, hj⟩ := h
  have : k = l + e * j := by linarith
  rw [this, zpow_add, zpow_mul, zpow_natCast, he, one_zpow, mul_one]

/-- **Proposition 6.1** of Tointon (bilinear case).  Let `b : Γ₁ × Γ₂ → Q` be multiplicative in
each variable, where `Q` is a finite abelian group, and suppose that its image `T` lies in a
subgroup generated by a set `X`.  Then the subgroup generated by `T` is `T^|X|`. -/
theorem closure_range_subset_pow [Finite Q] [DecidableEq Q] {Γ₁ Γ₂ : Type*} [Group Γ₁] [Group Γ₂]
    (b : Γ₁ → Γ₂ → Q) (hb1 : ∀ x x' y, b (x * x') y = b x y * b x' y)
    (hb2 : ∀ x y y', b x (y * y') = b x y * b x y') (X : Finset Q)
    (hX : ∀ x y, b x y ∈ Subgroup.closure (X : Set Q)) :
    (Subgroup.closure (Set.range (Function.uncurry b)) : Set Q) ⊆
      Set.range (Function.uncurry b) ^ X.card := by
  set T := Set.range (Function.uncurry b) with hT
  let φ₁ : Γ₂ → Γ₁ →* Q := fun y => MonoidHom.mk' (fun x => b x y) (fun x x' => hb1 x x' y)
  let φ₂ : Γ₁ → Γ₂ →* Q := fun x => MonoidHom.mk' (fun y => b x y) (fun y y' => hb2 x y y')
  have hz1 : ∀ x y (k : ℤ), b (x ^ k) y = b x y ^ k := fun x y k => map_zpow (φ₁ y) x k
  have hz2 : ∀ x y (k : ℤ), b x (y ^ k) = b x y ^ k := fun x y k => map_zpow (φ₂ x) y k
  have hmemT : ∀ x y, b x y ∈ T := fun x y => ⟨(x, y), rfl⟩
  have hTz : ∀ t ∈ T, ∀ k : ℤ, t ^ k ∈ T := by
    rintro _ ⟨⟨x, y⟩, rfl⟩ k
    refine ⟨(x ^ k, y), ?_⟩
    simp [Function.uncurry, hz1]
  set e := Nat.card Q with he
  have hpowe : ∀ z : Q, z ^ e = 1 := fun z => pow_card_eq_one'
  have hpos : 0 < e := Nat.card_pos
  have hpow : PowClosed T := fun t ht n => by simpa using hTz t ht n
  have hmix : MixClosed e T := by
    rintro u v huv huve _ ⟨⟨x, y⟩, rfl⟩ _ ⟨⟨x', y'⟩, rfl⟩
    obtain ⟨α, β, hab⟩ := exists_bezout huv
    set c : ℤ := β * v
    set c' : ℤ := α * u
    have heuv : (e : ℤ) = u * v := by rw [← huve]; push_cast; ring
    have hw : b (x ^ c * x' ^ c') (y ^ c * y' ^ c') =
        b x y ^ (c * c) * b x y' ^ (c * c') * (b x' y ^ (c' * c) * b x' y' ^ (c' * c')) := by
      simp only [hb1, hb2, hz1, hz2, ← zpow_mul]
      group
    refine ⟨_, hmemT (x ^ c * x' ^ c') (y ^ c * y' ^ c'), ?_, ?_⟩
    · simp only [Function.uncurry]
      rw [hw, ← zpow_natCast, ← zpow_natCast]
      simp only [mul_zpow, ← zpow_mul]
      rw [zpow_eq_zpow_of_dvd hpowe (b x y) (l := (v : ℤ)) ⟨-(α * (β * v + 1)), by
          rw [heuv]; linear_combination (β * v * v + v) * hab⟩,
        zpow_eq_zpow_of_dvd hpowe (b x y') (l := 0) ⟨α * β * v, by
          rw [heuv]; ring⟩,
        zpow_eq_zpow_of_dvd hpowe (b x' y) (l := 0) ⟨α * β * v, by
          rw [heuv]; ring⟩,
        zpow_eq_zpow_of_dvd hpowe (b x' y') (l := 0) ⟨α * α * u, by
          rw [heuv]; ring⟩]
      simp
    · simp only [Function.uncurry]
      rw [hw, ← zpow_natCast, ← zpow_natCast]
      simp only [mul_zpow, ← zpow_mul]
      rw [zpow_eq_zpow_of_dvd hpowe (b x y) (l := 0) ⟨β * β * v, by
          rw [heuv]; ring⟩,
        zpow_eq_zpow_of_dvd hpowe (b x y') (l := 0) ⟨α * β * u, by
          rw [heuv]; ring⟩,
        zpow_eq_zpow_of_dvd hpowe (b x' y) (l := 0) ⟨α * β * u, by
          rw [heuv]; ring⟩,
        zpow_eq_zpow_of_dvd hpowe (b x' y') (l := (u : ℤ)) ⟨-(β * (α * u + 1)), by
          rw [heuv]; linear_combination (α * u * u + u) * hab⟩]
      simp
  have hle : Subgroup.closure T ≤ Subgroup.closure (X : Set Q) := by
    rw [Subgroup.closure_le]; rintro _ ⟨⟨x, y⟩, rfl⟩; exact hX x y
  obtain ⟨Y, hYc, hY⟩ := exists_finset_closure_eq_of_le_closure X _ hle
  obtain ⟨f, hfT, hf⟩ := exists_tuple_closure_eq e hpos T ⟨_, hmemT 1 1⟩ hpow hmix
    (fun s _ => hpowe s) X.card Y hYc hY
  intro s hs
  rw [SetLike.mem_coe, ← hf] at hs
  obtain ⟨n, rfl⟩ := Subgroup.exists_of_mem_closure_range f s hs
  exact prod_mem_pow _ fun i => hTz _ (hfT i) _

end Bilinear

end Tointon
