module
public import RequestProject.TointonStep

/-!
# Tointon's normal-closure lemma from the rank form of Green–Ruzsa

**Proposition 7.3** of Tointon, *Freiman's theorem in an arbitrary nilpotent group* (quoted as
Lemma 6.6 by Tessera–Tointon), for finite groups: if `N` is an `s`-step nilpotent finite group
generated by a `K`-approximate group `A` and `L ⊆ A` is a subgroup, then the normal closure of `L`
lies in `A^C` with `C = C(K, s)`.

The proof iterates `central_step` along the series `L = L₀`, `L_{j+1} = [L_j, N]`, working modulo
`L_{j+2}` at step `j`, exactly as in the induction in the proof of Tointon's Proposition 7.2.
-/

@[expose] public section

open scoped Pointwise
open scoped commutatorElement

namespace Tointon

variable {N : Type*} [Group N]

/-- The series `L₀ = L`, `L_{j+1} = [L_j, N]`. -/
def commSeries (L : Subgroup N) : ℕ → Subgroup N
  | 0 => L
  | n + 1 => ⁅commSeries L n, (⊤ : Subgroup N)⁆

lemma commSeries_succ (L : Subgroup N) (n : ℕ) :
    commSeries L (n + 1) = ⁅commSeries L n, (⊤ : Subgroup N)⁆ := rfl

lemma commSeries_le_lowerCentralSeries (L : Subgroup N) (n : ℕ) :
    commSeries L n ≤ (⊤ : Subgroup N).lowerCentralSeries n := by
  induction n with
  | zero => exact le_top
  | succ n ih => exact Subgroup.commutator_mono ih le_rfl

lemma commSeries_map {Q : Type*} [Group Q] (f : N →* Q) (hf : Function.Surjective f)
    (L : Subgroup N) (n : ℕ) : (commSeries L n).map f = commSeries (L.map f) n := by
  induction n with
  | zero => rfl
  | succ n ih =>
    rw [commSeries_succ, commSeries_succ, Subgroup.map_commutator, ih,
      Subgroup.map_top_of_surjective f hf]

/-- One step of the series: `L_j ⊆ A^(C_j) L_{j+1}`. -/
theorem commSeries_subset (hGR : GreenRuzsaRank) (K : ℝ) (hK : 1 ≤ K) (j : ℕ) :
    ∃ C : ℕ, ∀ (N : Type) [Group N] [Finite N] (A : Set N) (L : Subgroup N),
      IsApproximateSubgroup K A → Subgroup.closure A = ⊤ → (L : Set N) ⊆ A →
      (commSeries L j : Set N) ⊆ A ^ C * (commSeries L (j + 1) : Set N) := by
  induction j with
  | zero =>
    refine ⟨1, fun N _ _ A L _ _ hL x hx => ⟨x, by simpa using hL hx, 1, one_mem _, mul_one x⟩⟩
  | succ j ih =>
    obtain ⟨Cj, hCj⟩ := ih
    obtain ⟨C', hC'⟩ := central_step hGR K hK Cj
    refine ⟨C', ?_⟩
    intro N _ _ A L hA hcl hL
    set D := commSeries L (j + 2) with hD
    haveI : D.Normal := commutator_top_normal _
    set f := QuotientGroup.mk' D with hf
    have hfs : Function.Surjective f := QuotientGroup.mk'_surjective D
    set P := (commSeries L j).map f with hP
    have hP1 : ⁅P, (⊤ : Subgroup (N ⧸ D))⁆ = (commSeries L (j + 1)).map f := by
      rw [hP, commSeries_map f hfs, commSeries_map f hfs, commSeries_succ]
    have hP2 : ⁅⁅P, (⊤ : Subgroup (N ⧸ D))⁆, (⊤ : Subgroup (N ⧸ D))⁆ = ⊥ := by
      rw [hP1, commSeries_map f hfs, ← commSeries_succ, ← commSeries_map f hfs, ← hD, hf,
        QuotientGroup.map_mk'_self]
    have hA' : IsApproximateSubgroup K (f '' A) := hA.image f
    have hcl' : Subgroup.closure (f '' A) = ⊤ := by
      rw [← MonoidHom.map_closure, hcl, Subgroup.map_top_of_surjective f hfs]
    have hPsub : (P : Set (N ⧸ D)) ⊆ (f '' A) ^ Cj *
        ((⁅P, (⊤ : Subgroup (N ⧸ D))⁆ : Subgroup (N ⧸ D)) : Set (N ⧸ D)) := by
      rw [hP1, hP, Subgroup.coe_map, Subgroup.coe_map, ← Set.image_pow, ← Set.image_mul]
      exact Set.image_mono (hCj N A L hA hcl hL)
    have key := hC' (N ⧸ D) (f '' A) P hA' hcl' hP2 hPsub
    rw [hP1] at key
    intro x hx
    have hfx : f x ∈ (f '' A) ^ C' := key ⟨x, hx, rfl⟩
    rw [← Set.image_pow] at hfx
    obtain ⟨a, ha, hax⟩ := hfx
    have hmem : a⁻¹ * x ∈ D := QuotientGroup.eq.1 hax
    exact ⟨a, ha, a⁻¹ * x, hmem, by group⟩

/-- Iterating: `L₁ ⊆ A^(D_i) L_{1+i}`. -/
theorem commSeries_one_subset (hGR : GreenRuzsaRank) (K : ℝ) (hK : 1 ≤ K) (i : ℕ) :
    ∃ C : ℕ, ∀ (N : Type) [Group N] [Finite N] (A : Set N) (L : Subgroup N),
      IsApproximateSubgroup K A → Subgroup.closure A = ⊤ → (L : Set N) ⊆ A →
      (commSeries L 1 : Set N) ⊆ A ^ C * (commSeries L (1 + i) : Set N) := by
  induction i with
  | zero => exact ⟨0, fun N _ _ A L _ _ _ x hx => ⟨1, by simp, x, hx, one_mul x⟩⟩
  | succ i ih =>
    obtain ⟨D, hD⟩ := ih
    obtain ⟨C, hC⟩ := commSeries_subset hGR K hK (1 + i)
    refine ⟨D + C, fun N _ _ A L hA hcl hL => ?_⟩
    refine (hD N A L hA hcl hL).trans ?_
    rw [pow_add, mul_assoc]
    exact Set.mul_subset_mul_left (hC N A L hA hcl hL)

/-- `L ⊔ [L, N]` is normal, so it contains the normal closure of `L`. -/
lemma normalClosure_le_sup_commutator (L : Subgroup N) :
    Subgroup.normalClosure (L : Set N) ≤ L ⊔ ⁅L, (⊤ : Subgroup N)⁆ := by
  haveI hM : (⁅L, (⊤ : Subgroup N)⁆).Normal := commutator_top_normal L
  haveI : (L ⊔ ⁅L, (⊤ : Subgroup N)⁆).Normal := by
    constructor
    intro x hx g
    rw [← SetLike.mem_coe, Subgroup.mul_normal] at hx
    obtain ⟨l, hl, m, hm, rfl⟩ := hx
    have e : g * (l * m) * g⁻¹ = ⁅l, g⁆⁻¹ * l * (g * m * g⁻¹) := by
      simp only [commutatorElement_def]; group
    rw [e]
    refine Subgroup.mul_mem _ (Subgroup.mul_mem _ ?_ (Subgroup.mem_sup_left hl)) ?_
    · exact Subgroup.mem_sup_right (Subgroup.inv_mem _
        (Subgroup.commutator_mem_commutator hl trivial))
    · exact Subgroup.mem_sup_right (hM.conj_mem m hm g)
  exact Subgroup.normalClosure_le_normal (fun x hx => Subgroup.mem_sup_left hx)

/-- **Proposition 7.3** of Tointon (Lemma 6.6 of Tessera–Tointon), for finite groups, assuming
the rank form of the Green–Ruzsa theorem. -/
theorem normalClosure_subset_pow_of_greenRuzsa (hGR : GreenRuzsaRank) :
    ∀ (K : ℝ) (s : ℕ), 1 ≤ K → ∃ C : ℕ, ∀ (N : Type) [Group N] [Finite N] (A : Set N)
      (L : Subgroup N), (⊤ : Subgroup N).lowerCentralSeries s = ⊥ → IsApproximateSubgroup K A →
      Subgroup.closure A = ⊤ → (L : Set N) ⊆ A →
      (Subgroup.normalClosure (L : Set N) : Set N) ⊆ A ^ C := by
  intro K s hK
  obtain ⟨D, hD⟩ := commSeries_one_subset hGR K hK s
  refine ⟨1 + D, fun N _ _ A L hnil hA hcl hL => ?_⟩
  haveI : (⁅L, (⊤ : Subgroup N)⁆).Normal := commutator_top_normal L
  have hbot : commSeries L (1 + s) = ⊥ := by
    rw [eq_bot_iff, ← hnil]
    exact (commSeries_le_lowerCentralSeries L _).trans
      ((⊤ : Subgroup N).lowerCentralSeries_antitone (by omega))
  intro x hx
  have hx' := normalClosure_le_sup_commutator L hx
  rw [← SetLike.mem_coe, Subgroup.mul_normal] at hx'
  obtain ⟨l, hl, m, hm, rfl⟩ := hx'
  have hm' := hD N A L hA hcl hL (show m ∈ (commSeries L 1 : Set N) from hm)
  rw [hbot] at hm'
  obtain ⟨a, ha, b, hb, rfl⟩ := hm'
  have hb1 : b = 1 := hb
  show l * (a * b) ∈ _
  rw [hb1, mul_one, pow_add, pow_one]
  exact Set.mul_mem_mul (hL hl) ha

end Tointon
