module
public import RequestProject.TointonRank

/-!
# Tointon's normal-closure argument: the central step

This file formalizes the inductive step of the proof of Proposition 7.2/7.3 of Tointon,
*Freiman's theorem in an arbitrary nilpotent group*, in the case needed here (finite groups, a
single subgroup).  The only input from outside is a rank form of the Green–Ruzsa theorem for
finite abelian groups, `GreenRuzsaRank` (Theorem 2.5 of Tointon's paper implies it); it is derived
from the Breuillard–Green–Tao theorem elsewhere in the project.

The step (`central_step`): if `P` is a subgroup of a finite group `N` generated by a
`K`-approximate group `A`, the commutator `M = [P, N]` is central, and `P ⊆ A^c M`, then
`M ⊆ A^C` with `C` depending only on `K` and `c`.
-/

@[expose] public section

open scoped Pointwise
open scoped commutatorElement

namespace Tointon

/-- **Rank form of the Green–Ruzsa theorem** (a consequence of Theorem 2.5 of Tointon's paper,
due to Green and Ruzsa), for finite abelian groups: a `K`-approximate group `B` is contained in
`H · ⟨X⟩` where `H` is a subgroup and `X` a set of at most `d = O_K(1)` elements, both inside a
bounded power `B^c`. -/
def GreenRuzsaRank : Prop :=
  ∀ K : ℝ, 1 ≤ K → ∃ d c : ℕ, ∀ (Z : Type) [CommGroup Z] [Finite Z] (B : Set Z),
    IsApproximateSubgroup K B → ∃ (H : Subgroup Z) (X : Finset Z),
      (H : Set Z) ⊆ B ^ c ∧ (X : Set Z) ⊆ B ^ c ∧ X.card ≤ d ∧
      B ⊆ (H : Set Z) * (Subgroup.closure (X : Set Z) : Set Z)

section Lemmas

variable {N : Type*} [Group N]

lemma commutator_mul_left_of_central {x x' g : N} (h : ∀ y, ⁅x', g⁆ * y = y * ⁅x', g⁆) :
    ⁅x * x', g⁆ = ⁅x, g⁆ * ⁅x', g⁆ := by
  have e1 : ⁅x * x', g⁆ = x * ⁅x', g⁆ * (g * x⁻¹ * g⁻¹) := by
    simp only [commutatorElement_def]; group
  rw [e1, ← h x, mul_assoc, h]
  simp only [commutatorElement_def]; group

lemma commutator_mul_right_of_central {x g g' : N} (h : ∀ y, ⁅x, g'⁆ * y = y * ⁅x, g'⁆) :
    ⁅x, g * g'⁆ = ⁅x, g⁆ * ⁅x, g'⁆ := by
  have e1 : ⁅x, g * g'⁆ = ⁅x, g⁆ * (g * ⁅x, g'⁆ * g⁻¹) := by
    simp only [commutatorElement_def]; group
  rw [e1, ← h g, mul_inv_cancel_right]

lemma commutator_mul_central_left {a z g : N} (hz : ∀ y, z * y = y * z) :
    ⁅a * z, g⁆ = ⁅a, g⁆ := by
  simp only [commutatorElement_def]
  have : z * g * z⁻¹ = g := by rw [hz g, mul_inv_cancel_right]
  calc a * z * g * (a * z)⁻¹ * g⁻¹ = a * (z * g * z⁻¹) * a⁻¹ * g⁻¹ := by group
    _ = a * g * a⁻¹ * g⁻¹ := by rw [this]

/-- A commutator of elements of `A^c` and `A^c'` lies in `A^(2c+2c')`. -/
lemma commutator_mem_pow {A : Set N} (hA : A⁻¹ = A) {c c' : ℕ} {a g : N} (ha : a ∈ A ^ c)
    (hg : g ∈ A ^ c') : ⁅a, g⁆ ∈ A ^ (2 * c + 2 * c') := by
  have hinv : ∀ n : ℕ, (A ^ n)⁻¹ = A ^ n := fun n => by rw [← inv_pow, hA]
  rw [commutatorElement_def]
  have e : 2 * c + 2 * c' = c + c' + c + c' := by ring
  rw [e, pow_add, pow_add, pow_add]
  refine Set.mul_mem_mul (Set.mul_mem_mul (Set.mul_mem_mul ha hg) ?_) ?_
  · rw [← hinv]; simpa using ha
  · rw [← hinv]; simpa using hg

/-- The commutator with the whole group is normal. -/
lemma commutator_top_normal (P : Subgroup N) : (⁅P, (⊤ : Subgroup N)⁆).Normal := by
  constructor
  intro x hx g
  rw [Subgroup.commutator_def] at hx ⊢
  induction hx using Subgroup.closure_induction with
  | mem y hy =>
    obtain ⟨p, hp, k, -, rfl⟩ := hy
    have e : g * ⁅p, k⁆ * g⁻¹ = ⁅p, g⁆⁻¹ * ⁅p, g * k⁆ := by
      simp only [commutatorElement_def]; group
    rw [e]
    exact Subgroup.mul_mem _ (Subgroup.inv_mem _ (Subgroup.subset_closure ⟨p, hp, g, trivial, rfl⟩))
      (Subgroup.subset_closure ⟨p, hp, g * k, trivial, rfl⟩)
  | one => simp
  | mul a b _ _ ha hb =>
    have e : g * (a * b) * g⁻¹ = (g * a * g⁻¹) * (g * b * g⁻¹) := by group
    rw [e]; exact Subgroup.mul_mem _ ha hb
  | inv a _ ha =>
    have e : g * a⁻¹ * g⁻¹ = (g * a * g⁻¹)⁻¹ := by group
    rw [e]; exact Subgroup.inv_mem _ ha

/-- An approximate group contained in a subgroup is an approximate group of the subgroup. -/
lemma isApproximateSubgroup_preimage_subtype {K : ℝ} {M : Subgroup N} {B : Set N}
    (hB : IsApproximateSubgroup K B) (hBM : B ⊆ M) :
    IsApproximateSubgroup K (((↑) : M → N) ⁻¹' B) := by
  classical
  obtain ⟨h1, hinv, F, hF, hcov⟩ := hB
  refine ⟨h1, ?_, ?_⟩
  · ext x; simp only [Set.mem_inv, Set.mem_preimage, Subgroup.coe_inv]
    rw [← Set.mem_inv, hinv]
  · refine ⟨F.subtype (· ∈ M), ?_, ?_⟩
    · refine le_trans ?_ hF
      rw [Finset.card_subtype]; exact_mod_cast Finset.card_filter_le _ _
    · intro x hx
      rw [pow_two] at hx
      obtain ⟨y, hy, z, hz, rfl⟩ := hx
      have hmem : ((y * z : M) : N) ∈ B ^ 2 := by
        rw [pow_two]; exact Set.mul_mem_mul hy hz
      obtain ⟨f, hf, b, hb, hfb⟩ := hcov hmem
      have hbM : b ∈ M := hBM hb
      have hfM : f ∈ M := by
        have : f = ((y * z : M) : N) * b⁻¹ := by rw [← hfb]; simp
        rw [this]; exact M.mul_mem (y * z).2 (M.inv_mem hbM)
      refine ⟨⟨f, hfM⟩, ?_, ⟨b, hbM⟩, hb, ?_⟩
      · exact Finset.mem_subtype.2 hf
      · apply Subtype.ext; simpa using hfb

end Lemmas

/-- **The central step** of Tointon's argument (proof of Proposition 7.2, specialised to a single
subgroup and to finite groups).  If `A` is a `K`-approximate group generating a finite group `N`,
`P ≤ N` is a subgroup such that `M = [P, N]` is central, and `P ⊆ A^c M`, then `M ⊆ A^C` where `C`
depends only on `K` and `c`. -/
theorem central_step (hGR : GreenRuzsaRank) (K : ℝ) (hK : 1 ≤ K) (c : ℕ) :
    ∃ C : ℕ, ∀ (N : Type) [Group N] [Finite N] (A : Set N) (P : Subgroup N),
      IsApproximateSubgroup K A → Subgroup.closure A = ⊤ →
      ⁅⁅P, (⊤ : Subgroup N)⁆, (⊤ : Subgroup N)⁆ = ⊥ →
      (P : Set N) ⊆ A ^ c * ((⁅P, (⊤ : Subgroup N)⁆ : Subgroup N) : Set N) →
      ((⁅P, (⊤ : Subgroup N)⁆ : Subgroup N) : Set N) ⊆ A ^ C := by
  classical
  obtain ⟨d₁, c₁, hGR1⟩ := hGR K hK
  set c₀ := 2 * c + 2 * c₁ with hc₀
  set c₂ := c₀ + 2 with hc₂
  set K₂ : ℝ := K ^ (2 * c₂ - 1) * 1 ^ (2 * 2 - 1) with hK₂def
  have hK₂ : 1 ≤ K₂ := by simp only [K₂, one_pow, mul_one]; exact one_le_pow₀ hK
  obtain ⟨d₂, c₃, hGR2⟩ := hGR K₂ hK₂
  refine ⟨c₀ * d₂ + c₂ * c₃ + c₀ * d₁, ?_⟩
  intro N _ _ A P hA hcl hcent hP
  set M := ⁅P, (⊤ : Subgroup N)⁆ with hMdef
  have hA1 := hA.one_mem
  have hAinv := hA.inv_eq_self
  have hApow1 : ∀ n : ℕ, (1 : N) ∈ A ^ n := fun n => Set.one_mem_pow hA1
  -- `M` is central
  have hcentral : ∀ z ∈ M, ∀ y : N, z * y = y * z := by
    intro z hz y
    have : ⁅z, y⁆ ∈ ⁅M, (⊤ : Subgroup N)⁆ := Subgroup.commutator_mem_commutator hz trivial
    rw [hcent, Subgroup.mem_bot, commutatorElement_eq_one_iff_mul_comm] at this
    exact this
  letI instM : CommGroup M :=
    { (inferInstance : Group M) with mul_comm := fun a b => Subtype.ext (hcentral a a.2 b) }
  -- the bilinear commutator map `P × N → M`
  have hmemM : ∀ x ∈ P, ∀ g : N, ⁅x, g⁆ ∈ M := fun x hx g =>
    Subgroup.commutator_mem_commutator hx trivial
  let β : P → N → M := fun x g => ⟨⁅(x : N), g⁆, hmemM x x.2 g⟩
  have hβ1 : ∀ x x' g, β (x * x') g = β x g * β x' g := fun x x' g =>
    Subtype.ext (commutator_mul_left_of_central (fun y => hcentral _ (hmemM _ x'.2 g) y))
  have hβ2 : ∀ x g g', β x (g * g') = β x g * β x g' := fun x g g' =>
    Subtype.ext (commutator_mul_right_of_central (fun y => hcentral _ (hmemM _ x.2 g') y))
  let φ : P → N →* M := fun x => MonoidHom.mk' (β x) (hβ2 x)
  let π : N →* Abelianization N := Abelianization.of
  have hπsurj : Function.Surjective π := fun v => QuotientGroup.mk_surjective v
  let bt : P → Abelianization N → M := fun x v => Abelianization.lift (φ x) v
  have hbt_of : ∀ x g, bt x (π g) = β x g := fun x g => Abelianization.lift_apply_of _ _
  have hbt1 : ∀ x x' v, bt (x * x') v = bt x v * bt x' v := by
    intro x x' v
    obtain ⟨g, rfl⟩ := hπsurj v
    rw [hbt_of, hbt_of, hbt_of, hβ1]
  have hbt2 : ∀ x v v', bt x (v * v') = bt x v * bt x v' := fun x v v' => map_mul _ _ _
  let ψ : Abelianization N → P →* M := fun v => MonoidHom.mk' (fun x => bt x v) (fun x x' => hbt1 x x' v)
  have hbtz1 : ∀ x v (k : ℤ), bt (x ^ k) v = bt x v ^ k := fun x v k => map_zpow (ψ v) x k
  have hbtinv : ∀ x v, bt x⁻¹ v = (bt x v)⁻¹ := fun x v => map_inv (ψ v) x
  have hbt1' : ∀ v, bt 1 v = 1 := fun v => map_one (ψ v)
  -- the key bound on commutators
  have hE : ∀ x : P, ∀ g ∈ A ^ c₁, ((β x g : M) : N) ∈ A ^ c₀ := by
    intro x g hg
    obtain ⟨a, ha, z, hz, hxaz⟩ := hP x.2
    show ⁅(x : N), g⁆ ∈ _
    rw [← hxaz, commutator_mul_central_left (hcentral z hz)]
    exact commutator_mem_pow hAinv ha hg
  -- Green–Ruzsa in the abelianisation
  have hπA : IsApproximateSubgroup K (π '' A) := hA.image π
  obtain ⟨H, Xb, hH, hXb, hXbd, hcovV⟩ := hGR1 (Abelianization N) (π '' A) hπA
  have hVtop : H ⊔ Subgroup.closure (Xb : Set (Abelianization N)) = ⊤ := by
    rw [eq_top_iff]
    have : Subgroup.closure (π '' A) = ⊤ := by
      rw [← MonoidHom.map_closure, hcl, Subgroup.map_top_of_surjective π hπsurj]
    rw [← this, Subgroup.closure_le]
    intro v hv
    obtain ⟨h, hh, w, hw, rfl⟩ := hcovV hv
    exact Subgroup.mul_mem _ (Subgroup.mem_sup_left hh) (Subgroup.mem_sup_right hw)
  have hbtbound : ∀ x : P, ∀ v ∈ (π '' A) ^ c₁, ((bt x v : M) : N) ∈ A ^ c₀ := by
    intro x v hv
    rw [← Set.image_pow] at hv
    obtain ⟨g, hg, rfl⟩ := hv
    rw [hbt_of]; exact hE x g hg
  -- the part coming from the subgroup `H`
  let b' : P → H → M := fun x h => bt x h
  set T : Set M := Set.range (Function.uncurry b') with hTdef
  have hT : ∀ t ∈ T, ((t : M) : N) ∈ A ^ c₀ := by
    rintro _ ⟨⟨x, h⟩, rfl⟩; exact hbtbound x h (hH h.2)
  set Bn : Set N := A ^ c₂ ∩ (M : Set N) ^ 2 with hBndef
  have hM2 : (M : Set N) ^ 2 = M := by rw [pow_two, coe_mul_coe M]
  have hBn : IsApproximateSubgroup K₂ Bn :=
    hA.pow_inter_pow IsApproximateSubgroup.subgroup (by omega) le_rfl
  have hBnM : Bn ⊆ M := fun x hx => by have := hx.2; rwa [hM2] at this
  set B' : Set M := ((↑) : M → N) ⁻¹' Bn with hB'def
  have hB' : IsApproximateSubgroup K₂ B' := isApproximateSubgroup_preimage_subtype hBn hBnM
  obtain ⟨Z₀, XZ, hZ₀, hXZ, hXZd, hcovM⟩ := hGR2 M B' hB'
  have hTB' : T ⊆ B' := fun t ht =>
    ⟨Set.pow_subset_pow_right hA1 (by omega) (hT t ht), by rw [hM2]; exact t.2⟩
  -- pass to `M / Z₀` and apply Proposition 6.1
  let ρ : M →* M ⧸ Z₀ := QuotientGroup.mk' Z₀
  let b'' : P → H → M ⧸ Z₀ := fun x h => ρ (b' x h)
  have hb''1 : ∀ x x' h, b'' (x * x') h = b'' x h * b'' x' h := fun x x' h => by
    simp only [b'', b', hbt1, map_mul]
  have hb''2 : ∀ x h h', b'' x (h * h') = b'' x h * b'' x h' := fun x h h' => by
    simp only [b'', b', Subgroup.coe_mul, hbt2, map_mul]
  have hb''X : ∀ x h, b'' x h ∈ Subgroup.closure ((XZ.image ρ : Finset _) : Set (M ⧸ Z₀)) := by
    intro x h
    have hmem : b' x h ∈ B' := hTB' ⟨(x, h), rfl⟩
    obtain ⟨z, hz, w, hw, hzw⟩ := hcovM hmem
    simp only [b'']
    rw [← hzw, map_mul]
    have hρz : ρ z = 1 := (QuotientGroup.eq_one_iff z).2 hz
    rw [hρz, one_mul, Finset.coe_image, ← MonoidHom.map_closure]
    exact Subgroup.mem_map_of_mem ρ hw
  have hprop := closure_range_subset_pow b'' hb''1 hb''2 (XZ.image ρ) hb''X
  have hrange : Set.range (Function.uncurry b'') = ρ '' T := by
    ext q; constructor
    · rintro ⟨⟨x, h⟩, rfl⟩; exact ⟨b' x h, ⟨(x, h), rfl⟩, rfl⟩
    · rintro ⟨_, ⟨⟨x, h⟩, rfl⟩, rfl⟩; exact ⟨(x, h), rfl⟩
  have hclT : ∀ s ∈ Subgroup.closure T, ((s : M) : N) ∈ A ^ (c₀ * d₂ + c₂ * c₃) := by
    intro s hs
    have hρs : ρ s ∈ (Subgroup.closure (Set.range (Function.uncurry b'')) : Set (M ⧸ Z₀)) := by
      rw [hrange, ← MonoidHom.map_closure]; exact ⟨s, hs, rfl⟩
    have h1 := hprop hρs
    have hone : (1 : M ⧸ Z₀) ∈ Set.range (Function.uncurry b'') :=
      ⟨(1, 1), by simp [b'', b', hbt1']⟩
    have h2 : ρ s ∈ Set.range (Function.uncurry b'') ^ d₂ :=
      Set.pow_subset_pow_right hone ((Finset.card_image_le).trans hXZd) h1
    rw [hrange, ← Set.image_pow] at h2
    obtain ⟨t, ht, hts⟩ := h2
    have hz : t⁻¹ * s ∈ Z₀ := QuotientGroup.eq.1 hts
    have hs_eq : s = t * (t⁻¹ * s) := by group
    rw [hs_eq, Subgroup.coe_mul, pow_add]
    refine Set.mul_mem_mul ?_ ?_
    · have : ((↑) : M → N) '' (T ^ d₂) ⊆ (A ^ c₀) ^ d₂ := by
        rw [show ((↑) : M → N) = M.subtype from rfl, Set.image_pow]
        exact Set.pow_subset_pow_left (by rintro _ ⟨t, ht, rfl⟩; exact hT t ht)
      rw [pow_mul]; exact this ⟨t, ht, rfl⟩
    · have : ((↑) : M → N) '' (B' ^ c₃) ⊆ (A ^ c₂) ^ c₃ := by
        rw [show ((↑) : M → N) = M.subtype from rfl, Set.image_pow]
        exact Set.pow_subset_pow_left (by rintro _ ⟨t, ht, rfl⟩; exact ht.1)
      rw [pow_mul]; exact this ⟨_, hZ₀ hz, rfl⟩
  -- the part coming from the bounded generating set `Xb`
  set Sstar : Set M := {m | ∃ s ∈ Subgroup.closure T, ∃ f : Abelianization N → P,
    m = s * ∏ xb ∈ Xb, bt (f xb) xb} with hSstar
  have hgen : ∀ x : P, ∀ g : N, β x g ∈ Sstar := by
    intro x g
    have hg : π g ∈ H ⊔ Subgroup.closure (Xb : Set (Abelianization N)) := by
      rw [hVtop]; trivial
    obtain ⟨h, hh, w, hw, hhw⟩ := Subgroup.mem_sup.1 hg
    obtain ⟨n, rfl⟩ := exists_zpow_of_mem_closure Xb hw
    refine ⟨bt x h, Subgroup.subset_closure ⟨(x, ⟨h, hh⟩), rfl⟩, fun xb => x ^ n xb, ?_⟩
    rw [← hbt_of, ← hhw, hbt2]
    congr 1
    have hprod : bt x (∏ y ∈ Xb, y ^ n y) = ∏ y ∈ Xb, bt x (y ^ n y) :=
      map_prod (Abelianization.lift (φ x)) _ _
    rw [hprod]
    refine Finset.prod_congr rfl fun xb _ => ?_
    have hz : bt x (xb ^ n xb) = bt x xb ^ n xb := map_zpow (Abelianization.lift (φ x)) _ _
    rw [hz, hbtz1]
  have hmul : ∀ m ∈ Sstar, ∀ m' ∈ Sstar, m * m' ∈ Sstar := by
    rintro _ ⟨s, hs, f, rfl⟩ _ ⟨s', hs', f', rfl⟩
    refine ⟨s * s', Subgroup.mul_mem _ hs hs', fun xb => f xb * f' xb, ?_⟩
    simp only [hbt1, Finset.prod_mul_distrib]
    exact mul_mul_mul_comm _ _ _ _
  have hinvS : ∀ m ∈ Sstar, m⁻¹ ∈ Sstar := by
    rintro _ ⟨s, hs, f, rfl⟩
    refine ⟨s⁻¹, Subgroup.inv_mem _ hs, fun xb => (f xb)⁻¹, ?_⟩
    simp only [hbtinv, Finset.prod_inv_distrib, mul_inv]
  have hone : (1 : M) ∈ Sstar := ⟨1, Subgroup.one_mem _, fun _ => 1, by simp [hbt1']⟩
  have hall : ∀ m ∈ Subgroup.closure {m : N | ∃ x ∈ P, ∃ g ∈ (⊤ : Subgroup N), ⁅x, g⁆ = m},
      ∃ hm : m ∈ M, (⟨m, hm⟩ : M) ∈ Sstar := by
    intro m hm
    induction hm using Subgroup.closure_induction with
    | mem y hy =>
      obtain ⟨x, hx, g, -, rfl⟩ := hy
      exact ⟨hmemM x hx g, hgen ⟨x, hx⟩ g⟩
    | one => exact ⟨one_mem _, hone⟩
    | mul a b _ _ ha hb =>
      obtain ⟨ha', ha''⟩ := ha
      obtain ⟨hb', hb''⟩ := hb
      exact ⟨M.mul_mem ha' hb', hmul _ ha'' _ hb''⟩
    | inv a _ ha =>
      obtain ⟨ha', ha''⟩ := ha
      exact ⟨M.inv_mem ha', hinvS _ ha''⟩
  -- conclusion
  intro m hm
  have hm' : m ∈ Subgroup.closure {m : N | ∃ x ∈ P, ∃ g ∈ (⊤ : Subgroup N), ⁅x, g⁆ = m} := by
    rw [← Subgroup.commutator_def]; exact hm
  obtain ⟨hmM, s, hs, f, hsf⟩ := hall m hm'
  have e : m = ((s : M) : N) * ((∏ xb ∈ Xb, bt (f xb) xb : M) : N) := by
    rw [← Subgroup.coe_mul, ← hsf]
  rw [e, pow_add]
  refine Set.mul_mem_mul (hclT s hs) ?_
  have hprodcoe : ∀ (s : Finset (Abelianization N)) (F : Abelianization N → M),
      (∀ i ∈ s, ((F i : M) : N) ∈ A ^ c₀) → ((∏ i ∈ s, F i : M) : N) ∈ (A ^ c₀) ^ s.card := by
    intro s F hF
    induction s using Finset.induction_on with
    | empty => simp
    | @insert i s hi ih =>
      rw [Finset.prod_insert hi, Finset.card_insert_of_notMem hi, pow_succ']
      exact (Set.mul_mem_mul (hF i (by simp)) (ih fun j hj => hF j (by simp [hj])) :)
  have h1 : ((∏ xb ∈ Xb, bt (f xb) xb : M) : N) ∈ (A ^ c₀) ^ Xb.card :=
    hprodcoe Xb _ fun xb hxb => hbtbound (f xb) xb (hXb hxb)
  rw [pow_mul]
  exact Set.pow_subset_pow_right (hApow1 c₀) hXbd h1

end Tointon
