module
public import Mathlib.Combinatorics.Additive.ApproximateSubgroup
public import Mathlib.GroupTheory.Nilpotent
public import Mathlib.GroupTheory.Index

/-!
# Normal closures in virtually nilpotent approximate groups (Proposition 6.5 of Tessera–Tointon)

Tessera and Tointon deduce their Proposition 6.5 from a lemma of Tointon on nilpotent approximate
groups (their Lemma 6.6, which is Proposition 7.3 of Tointon, *Freiman's theorem in an arbitrary
nilpotent group*).  That lemma is stated here, for finite groups, as the hypothesis
`TointonNormalClosure`.  The deduction of Proposition 6.5 is proved in full, including the
standard facts it uses:

* Lemma 6.7: `A^(k-1)` meets every coset of a subgroup of index at most `k`;
* Schreier's lemma in the form `⟨A^(2k-1) ∩ N⟩ = N` (Lemma 4.2 of Breuillard–Tointon);
* the fact that `A^(2k) ∩ N` is again an approximate group (Mathlib's
  `IsApproximateSubgroup.pow_inter_pow`);
* Lemma 6.9: passing from the normal closure in `N` to the normal closure in the whole group.
-/

@[expose] public section


open scoped Pointwise

namespace Lovasz

/-- **Tointon's lemma** (Lemma 6.6 of Tessera–Tointon; Proposition 7.3 of Tointon, *Freiman's
theorem in an arbitrary nilpotent group*), for finite groups and with an unspecified bound in
place of `K^(O_s(1))`: if a nilpotent group `N` of class at most `s` is generated by a
`K`-approximate group `A`, and `L ⊆ A` is a subgroup, then the normal closure of `L` in `N` is
contained in `A^C` for some `C` depending only on `K` and `s`. -/
def TointonNormalClosure : Prop :=
  ∀ (K : ℝ) (s : ℕ), 1 ≤ K → ∃ C : ℕ, ∀ (N : Type) [Group N] [Finite N] (A : Set N)
    (L : Subgroup N), (⊤ : Subgroup N).lowerCentralSeries s = ⊥ → IsApproximateSubgroup K A →
    Subgroup.closure A = ⊤ → (L : Set N) ⊆ A →
    (Subgroup.normalClosure (L : Set N) : Set N) ⊆ A ^ C

section Group

variable {Q : Type*} [Group Q]

/-- A set containing `1` and closed under left multiplication by a symmetric generating set is
everything. -/
lemma eq_univ_of_mul_closed (A : Set Q) (hA : A⁻¹ = A) (hcl : Subgroup.closure A = ⊤)
    (P : Set Q) (h1 : 1 ∈ P) (hAP : ∀ a ∈ A, ∀ p ∈ P, a * p ∈ P) : P = Set.univ := by
  ext q
  simp only [Set.mem_univ, iff_true]
  have hq : q ∈ Subgroup.closure A := hcl ▸ Subgroup.mem_top q
  suffices h : ∀ p ∈ P, q * p ∈ P by simpa using h 1 h1
  refine Subgroup.closure_induction'' (p := fun q _ => ∀ p ∈ P, q * p ∈ P) ?_ ?_ ?_ ?_ hq
  · exact fun x hx => hAP x hx
  · intro x hx
    apply hAP
    rw [← hA]; simpa using hx
  · simp only [one_mul]; exact fun p hp => hp
  · intro x y _ _ ihx ihy p hp
    rw [mul_assoc]; exact ihx _ (ihy p hp)

/-- **Lemma 6.7** of Tessera–Tointon: `A^(k-1)` meets every left coset of a subgroup of index at
most `k`. -/
lemma exists_rep_in_pow [Finite Q] (A : Set Q) (h1 : 1 ∈ A) (hA : A⁻¹ = A)
    (hcl : Subgroup.closure A = ⊤) (N : Subgroup Q) (k : ℕ) (hk : N.index ≤ k) (x : Q ⧸ N) :
    ∃ r ∈ A ^ (k - 1), (r : Q ⧸ N) = x := by
  classical
  have hidx : 1 ≤ N.index := Nat.one_le_iff_ne_zero.2 Subgroup.index_ne_zero_of_finite
  set c : ℕ → Set (Q ⧸ N) := fun i => (QuotientGroup.mk : Q → Q ⧸ N) '' (A ^ i) with hc
  have hmono : ∀ i, c i ⊆ c (i + 1) := fun i =>
    Set.image_mono (Set.pow_subset_pow_right h1 (by omega))
  have key : ∀ i, c i = Set.univ ∨ i + 1 ≤ (c i).ncard := by
    intro i
    induction i with
    | zero => right; simp [c]
    | succ i ih =>
      by_cases hu : c (i + 1) = Set.univ
      · left; exact hu
      right
      rcases ih with h | h
      · exact absurd (Set.eq_univ_of_univ_subset (h ▸ hmono i)) hu
      have hne : c i ≠ c (i + 1) := by
        intro heq
        apply hu
        have hP := eq_univ_of_mul_closed A hA hcl ((QuotientGroup.mk : Q → Q ⧸ N) ⁻¹' c i) ?_ ?_
        · rw [← heq]
          ext y
          obtain ⟨z, rfl⟩ := QuotientGroup.mk_surjective y
          simp only [Set.mem_univ, iff_true]
          have : z ∈ (QuotientGroup.mk : Q → Q ⧸ N) ⁻¹' c i := hP ▸ Set.mem_univ z
          exact this
        · exact ⟨1, Set.one_mem_pow h1, rfl⟩
        · intro a ha p hp
          obtain ⟨q', hq', hpq⟩ := hp
          show (QuotientGroup.mk (a * p) : Q ⧸ N) ∈ c i
          rw [heq]
          refine ⟨a * q', ?_, ?_⟩
          · rw [pow_succ']; exact Set.mul_mem_mul ha hq'
          · rw [QuotientGroup.eq] at hpq ⊢
            simpa [mul_assoc] using hpq
      have hlt : (c i).ncard < (c (i + 1)).ncard :=
        Set.ncard_lt_ncard (lt_of_le_of_ne (hmono i) hne) (Set.toFinite _)
      omega
  by_cases hu : c (k - 1) = Set.univ
  · have : x ∈ c (k - 1) := hu ▸ Set.mem_univ _
    obtain ⟨r, hr, e⟩ := this
    exact ⟨r, hr, e⟩
  · exfalso
    have h := (key (k - 1)).resolve_left hu
    have hlt : (c (k - 1)).ncard < (Set.univ : Set (Q ⧸ N)).ncard :=
      Set.ncard_lt_ncard (Set.ssubset_univ_iff.2 hu) (Set.toFinite _)
    rw [Set.ncard_univ] at hlt
    have : Nat.card (Q ⧸ N) = N.index := rfl
    omega

/-- **Schreier's lemma**: if `N` has index at most `k`, then `A^(2k-1) ∩ N` generates `N`. -/
lemma closure_pow_inter_eq [Finite Q] (A : Set Q) (h1 : 1 ∈ A) (hA : A⁻¹ = A)
    (hcl : Subgroup.closure A = ⊤) (N : Subgroup Q) (k : ℕ) (hk : N.index ≤ k) :
    Subgroup.closure (A ^ (2 * k - 1) ∩ N) = N := by
  have hk1 : 1 ≤ k := (Nat.one_le_iff_ne_zero.2 Subgroup.index_ne_zero_of_finite).trans hk
  set N' := Subgroup.closure (A ^ (2 * k - 1) ∩ N) with hN'
  have hsub : A ^ (k - 1) ⊆ A ^ (2 * k - 1) := Set.pow_subset_pow_right h1 (by omega)
  have hinv : (A ^ (k - 1))⁻¹ = A ^ (k - 1) := by rw [← inv_pow, hA]
  have hmem3 : ∀ r' ∈ A ^ (k - 1), ∀ a ∈ A, ∀ r ∈ A ^ (k - 1), r'⁻¹ * a * r ∈ A ^ (2 * k - 1) := by
    intro r' hr' a ha r hr
    have e : 2 * k - 1 = (k - 1) + 1 + (k - 1) := by omega
    rw [e, pow_add, pow_add, pow_one]
    refine Set.mul_mem_mul (Set.mul_mem_mul ?_ ha) hr
    rw [← hinv]; simpa using hr'
  have hN'N : N' ≤ N := (Subgroup.closure_le _).2 Set.inter_subset_right
  apply le_antisymm hN'N
  intro n hn
  set P : Set Q := {q | ∃ r ∈ A ^ (k - 1), ∃ m ∈ N', q = r * m} with hPdef
  have hP : P = Set.univ := by
    apply eq_univ_of_mul_closed A hA hcl P
    · obtain ⟨r₀, hr₀, e⟩ := exists_rep_in_pow A h1 hA hcl N k hk (1 : Q)
      have : r₀ ∈ N := by
        rw [QuotientGroup.eq] at e; simpa using e
      exact ⟨r₀, hr₀, r₀⁻¹, N'.inv_mem (Subgroup.subset_closure ⟨hsub hr₀, this⟩), by simp⟩
    · rintro a ha _ ⟨r, hr, m, hm, rfl⟩
      obtain ⟨r', hr', e⟩ := exists_rep_in_pow A h1 hA hcl N k hk ((a * r : Q) : Q ⧸ N)
      rw [QuotientGroup.eq] at e
      refine ⟨r', hr', r'⁻¹ * (a * r) * m, N'.mul_mem (Subgroup.subset_closure ⟨?_, e⟩) hm, by group⟩
      rw [← mul_assoc]; exact hmem3 r' hr' a ha r hr
  obtain ⟨r, hr, m, hm, rfl⟩ : n ∈ P := hP ▸ Set.mem_univ n
  have hrN : r ∈ N := by
    have := N.mul_mem hn (N.inv_mem (hN'N hm)); simpa using this
  exact N'.mul_mem (Subgroup.subset_closure ⟨hsub hr, hrN⟩) hm

/-- An approximate group contained in a subgroup `N` is an approximate group of `N`. -/
lemma isApproximateSubgroup_subtype (N : Subgroup Q) (B : Set Q) (K : ℝ) (hBN : B ⊆ N)
    (hB : IsApproximateSubgroup K B) :
    IsApproximateSubgroup K (((↑) : N → Q) ⁻¹' B) := by
  classical
  obtain ⟨F, hF, hcov⟩ := hB.sq_covBySMul
  refine ⟨hB.one_mem, ?_, ?_⟩
  · ext x
    simp only [Set.mem_inv, Set.mem_preimage, Subgroup.coe_inv]
    rw [← Set.mem_inv, hB.inv_eq_self]
  · refine ⟨F.subtype (· ∈ N), ?_, ?_⟩
    · refine le_trans ?_ hF
      rw [Finset.card_subtype]
      exact_mod_cast Finset.card_filter_le _ _
    · intro x hx
      rw [sq] at hx
      obtain ⟨y, hy, z, hz, rfl⟩ := Set.mem_mul.1 hx
      have hyz : ((y * z : N) : Q) ∈ B ^ 2 := by
        rw [sq, Subgroup.coe_mul]; exact Set.mul_mem_mul hy hz
      obtain ⟨f, hf, b, hb, e⟩ := Set.mem_smul.1 (hcov hyz)
      have hfN : f ∈ N := by
        have : f = ((y * z : N) : Q) * b⁻¹ := by rw [← e, smul_eq_mul]; group
        rw [this]; exact N.mul_mem (y * z).2 (N.inv_mem (hBN hb))
      refine Set.mem_smul.2 ⟨⟨f, hfN⟩, by simpa using hf, ⟨b, hBN hb⟩, hb, ?_⟩
      apply Subtype.ext
      simpa using e

/-- The join of subgroups `f i` (`i ∈ R`), all contained in a subgroup `M` which normalises each
of them, is contained in `D^|R|` whenever each `f i` is contained in `D ∋ 1`. -/
lemma sup_subset_pow {ι : Type*} (R : Finset ι) (f : ι → Subgroup Q) (M : Subgroup Q) (D : Set Q)
    (hf : ∀ i ∈ R, (f i : Set Q) ⊆ D)
    (hM : ∀ i ∈ R, f i ≤ M ∧ M ≤ Subgroup.normalizer (f i : Set Q)) :
    ((R.sup f : Subgroup Q) : Set Q) ⊆ D ^ R.card := by
  classical
  induction R using Finset.induction_on with
  | empty => simp
  | insert a s ha ih =>
    rw [Finset.sup_insert, Finset.card_insert_of_notMem ha, pow_succ']
    have hs : s.sup f ≤ M :=
      Finset.sup_le (fun i hi => (hM i (Finset.mem_insert_of_mem hi)).1)
    rw [Subgroup.coe_mul_of_right_le_normalizer_left _ _
      (hs.trans (hM a (Finset.mem_insert_self a s)).2)]
    exact Set.mul_subset_mul (hf a (Finset.mem_insert_self a s))
      (ih (fun i hi => hf i (Finset.mem_insert_of_mem hi))
        (fun i hi => hM i (Finset.mem_insert_of_mem hi)))

/-- **Proposition 6.5** of Tessera–Tointon, for finite groups: if `A` is a `K`-approximate group
generating `Q`, `N ◁ Q` has index at most `k` and is nilpotent of class at most `s`, and `L ⊆ A`
is a subgroup of `N`, then the normal closure of `L` in `Q` is contained in `A^D` for some `D`
depending only on `K`, `s`, `k`. -/
theorem normalClosure_subset_pow (hT : TointonNormalClosure) (K : ℝ) (s k : ℕ) (hK : 1 ≤ K) :
    ∃ D : ℕ, ∀ (Q : Type) [Group Q] [Finite Q] (A : Set Q) (N L : Subgroup Q),
      IsApproximateSubgroup K A → Subgroup.closure A = ⊤ → N.Normal → N.index ≤ k →
      (⊤ : Subgroup N).lowerCentralSeries s = ⊥ → (L : Set Q) ⊆ A → L ≤ N →
      (Subgroup.normalClosure (L : Set Q) : Set Q) ⊆ A ^ D := by
  obtain ⟨C, hC⟩ := hT (K ^ (2 * (2 * k) - 1) * 1 ^ (2 * 2 - 1)) s
    (by rw [one_pow, mul_one]; exact one_le_pow₀ hK)
  refine ⟨k * (2 * (k - 1) + 2 * k * C), ?_⟩
  intro Q _ _ A N L hA hcl hN hk hlcs hLA hLN
  classical
  have h1 := hA.one_mem
  have hk1 : 1 ≤ k := (Nat.one_le_iff_ne_zero.2 Subgroup.index_ne_zero_of_finite).trans hk
  have hinv : (A ^ (k - 1))⁻¹ = A ^ (k - 1) := by rw [← inv_pow, hA.inv_eq_self]
  have hN2 : (N : Set Q) ^ 2 = N := by rw [sq]; exact coe_mul_coe N
  set B : Set Q := A ^ (2 * k) ∩ (N : Set Q) ^ 2 with hBdef
  have hB : IsApproximateSubgroup (K ^ (2 * (2 * k) - 1) * 1 ^ (2 * 2 - 1)) B :=
    hA.pow_inter_pow IsApproximateSubgroup.subgroup (by omega) le_rfl
  have hBN : B ⊆ N := fun x hx => hN2 ▸ hx.2
  have hA2k : A ⊆ A ^ (2 * k) := by
    have := Set.pow_subset_pow_right (s := A) h1 (show 1 ≤ 2 * k by omega)
    rwa [pow_one] at this
  have hBgen : Subgroup.closure B = N := by
    apply le_antisymm ((Subgroup.closure_le _).2 hBN)
    rw [← closure_pow_inter_eq A h1 hA.inv_eq_self hcl N k hk]
    apply Subgroup.closure_mono
    rintro x ⟨hx1, hx2⟩
    exact ⟨Set.pow_subset_pow_right h1 (by omega) hx1, hN2.symm ▸ hx2⟩
  set A' : Set N := ((↑) : N → Q) ⁻¹' B with hA'def
  have hA' := isApproximateSubgroup_subtype N B _ hBN hB
  have hA'gen : Subgroup.closure A' = ⊤ := by
    apply Subgroup.map_injective N.subtype_injective
    rw [MonoidHom.map_closure]
    have him : (N.subtype : N → Q) '' A' = B := by
      ext x
      constructor
      · rintro ⟨y, hy, rfl⟩; exact hy
      · intro hx; exact ⟨⟨x, hBN hx⟩, hx, rfl⟩
    rw [him, hBgen]
    ext x
    simp
  have hL' : ((L.subgroupOf N : Subgroup N) : Set N) ⊆ A' := by
    intro x hx
    rw [SetLike.mem_coe, Subgroup.mem_subgroupOf] at hx
    exact ⟨hA2k (hLA hx), hN2.symm ▸ x.2⟩
  have hW := hC N A' (L.subgroupOf N) hlcs hA' hA'gen hL'
  set W : Subgroup Q :=
    (Subgroup.normalClosure ((L.subgroupOf N : Subgroup N) : Set N)).map N.subtype with hWdef
  have hWsub : (W : Set Q) ⊆ A ^ (2 * k * C) := by
    rintro _ ⟨x, hx, rfl⟩
    have hx' := hW hx
    have : (N.subtype x) ∈ N.subtype '' (A' ^ C) := ⟨x, hx', rfl⟩
    rw [Set.image_pow] at this
    rw [pow_mul]
    refine Set.pow_subset_pow_left ?_ this
    rintro _ ⟨y, hy, rfl⟩
    exact hy.1
  have hWN : W ≤ N := Subgroup.map_subtype_le _
  have hWnorm : ∀ n ∈ N, ∀ w ∈ W, n * w * n⁻¹ ∈ W := by
    rintro n hn _ ⟨x, hx, rfl⟩
    exact ⟨⟨n, hn⟩ * x * ⟨n, hn⟩⁻¹, Subgroup.normalClosure_normal.conj_mem x hx ⟨n, hn⟩,
      by simp⟩
  have hLW : ∀ n ∈ N, ∀ l ∈ L, n * l * n⁻¹ ∈ W := by
    intro n hn l hl
    refine hWnorm n hn l ⟨⟨l, hLN hl⟩, Subgroup.subset_normalClosure ?_, rfl⟩
    simpa [Subgroup.mem_subgroupOf] using hl
  have hrep : ∀ x : Q ⧸ N, ∃ r ∈ A ^ (k - 1), (r : Q ⧸ N) = x :=
    exists_rep_in_pow A h1 hA.inv_eq_self hcl N k hk
  choose rep hrepA hrepmk using hrep
  haveI : Fintype (Q ⧸ N) := Fintype.ofFinite _
  set R : Finset Q := Finset.univ.image rep with hRdef
  have hRcard : R.card ≤ k := by
    refine Finset.card_image_le.trans ?_
    rw [Finset.card_univ, ← Nat.card_eq_fintype_card]
    exact hk
  set f : Q → Subgroup Q := fun r => W.map (MulAut.conj r).toMonoidHom with hfdef
  have hU : Subgroup.normalClosure (L : Set Q) ≤ R.sup f := by
    rw [Subgroup.normalClosure, Subgroup.closure_le]
    intro x hx
    obtain ⟨l, hl, hconj⟩ := Group.mem_conjugatesOfSet_iff.1 hx
    obtain ⟨c, rfl⟩ := isConj_iff.1 hconj
    have hrc : (rep (c : Q ⧸ N))⁻¹ * c ∈ N := QuotientGroup.eq.1 (hrepmk _)
    apply Finset.le_sup (f := f) (Finset.mem_image_of_mem rep (Finset.mem_univ (c : Q ⧸ N)))
    refine ⟨((rep (c : Q ⧸ N))⁻¹ * c) * l * ((rep (c : Q ⧸ N))⁻¹ * c)⁻¹, hLW _ hrc l hl, ?_⟩
    simp only [MulEquiv.coe_toMonoidHom, MulAut.conj_apply]
    group
  have hUsub : ((R.sup f : Subgroup Q) : Set Q) ⊆ A ^ ((2 * (k - 1) + 2 * k * C) * R.card) := by
    rw [pow_mul]
    apply sup_subset_pow R f N
    · intro r hr
      obtain ⟨x, -, rfl⟩ := Finset.mem_image.1 hr
      rintro _ ⟨w, hw, rfl⟩
      simp only [MulEquiv.coe_toMonoidHom, MulAut.conj_apply]
      have e : 2 * (k - 1) + 2 * k * C = (k - 1) + 2 * k * C + (k - 1) := by ring
      rw [e, pow_add, pow_add]
      refine Set.mul_mem_mul (Set.mul_mem_mul (hrepA x) (hWsub hw)) ?_
      rw [← hinv]; simpa using hrepA x
    · intro r _
      constructor
      · rintro _ ⟨w, hw, rfl⟩
        simp only [MulEquiv.coe_toMonoidHom, MulAut.conj_apply]
        exact hN.conj_mem w (hWN hw) r
      · intro n hn
        rw [Subgroup.mem_normalizer_iff]
        intro y
        have hc1 : r⁻¹ * n * r ∈ N := by
          have := hN.conj_mem n hn r⁻¹; simpa using this
        have hc2 : r⁻¹ * n⁻¹ * r ∈ N := by
          have := hN.conj_mem n⁻¹ (N.inv_mem hn) r⁻¹; simpa using this
        constructor
        · rintro ⟨w, hw, rfl⟩
          refine ⟨(r⁻¹ * n * r) * w * (r⁻¹ * n * r)⁻¹, hWnorm _ hc1 w hw, ?_⟩
          simp only [MulEquiv.coe_toMonoidHom, MulAut.conj_apply]
          group
        · rintro ⟨w, hw, e⟩
          refine ⟨(r⁻¹ * n⁻¹ * r) * w * (r⁻¹ * n⁻¹ * r)⁻¹, hWnorm _ hc2 w hw, ?_⟩
          simp only [MulEquiv.coe_toMonoidHom, MulAut.conj_apply] at e ⊢
          rw [show y = n⁻¹ * (n * y * n⁻¹) * n by group, ← e]
          group
  intro x hx
  exact Set.pow_subset_pow_right h1 ((Nat.mul_le_mul_left _ hRcard).trans (le_of_eq (mul_comm _ _)))
    (hUsub (hU hx))

end Group

end Lovasz
