module
public import Mathlib
public import RequestProject.UltraWordTransfer

/-!
# The locally compact model of an ultraproduct of approximate groups

Let `A*` be an internal set in an algebraic ultraproduct (along a nonprincipal ultrafilter),
together with a normal tower of internal sets `B j` (the internal interpretation of a Sanders
tower, see `SandersTower.lean`) with

* `1 ∈ B j`, `B j` symmetric, `B (j+1) * B (j+1) ⊆ B j`,
* `a⁻¹ B (j+1) a ⊆ B j` for `a ∈ A*`,
* `B j ⊆ A*⁴`,
* for all `r, j`, a finite cover `A*^r ⊆ F · B j` with `F ⊆ A*^r`.

This is packaged as `TowerData`.  Then:

* `TowerData.Γ`: the subgroup `⋃ᵣ A*^r` generated by `A*`;
* `TowerData.basis`: the sets `B j` form a group filter basis on `Γ`; this defines the (not
  necessarily Hausdorff) group topology on `Γ`, which is first countable;
* `TowerData.L = Γ ⧸ Z` with `Z` the closure of the identity, `Z ⊆ ⋂ⱼ B j`; `L` is a Hausdorff,
  first-countable topological group, and `π : Γ → L` is open;
* `isCompact_image_of_internal`: images of bounded internal sets are compact.  The proof is by
  open covers and countable internal covers (`Ultra.internal_subset_finite_subcover`); no metric
  is constructed;
* `L` is locally compact;
* `sandwich`: for compact `F ⊆ O` open in `L` there is a bounded internal `D` with
  `π⁻¹(F) ⊆ D ⊆ π⁻¹(O)` (full fibres), symmetric if `F` and `O` are.
-/

@[expose] public section

open Filter Topology
open scoped Pointwise

namespace Lovasz.UltraModel

open Ultra

variable {G : ℕ → Type*} [∀ n, Group (G n)] {U : Ultrafilter ℕ}

/-- A normal tower of internal sets in the ultraproduct (see the module docstring). -/
structure TowerData (U : Ultrafilter ℕ) (G : ℕ → Type*) [∀ n, Group (G n)] where
  nonprincipal : (U : Filter ℕ) ≤ cofinite
  A : Set (UProd (G := G) U)
  B : ℕ → Set (UProd (G := G) U)
  A_int : IsInternal U A
  B_int : ∀ j, IsInternal U (B j)
  one_mem_A : (1 : UProd (G := G) U) ∈ A
  inv_A : A⁻¹ = A
  one_mem_B : ∀ j, (1 : UProd (G := G) U) ∈ B j
  inv_B : ∀ j, (B j)⁻¹ = B j
  mul_B : ∀ j, B (j + 1) * B (j + 1) ⊆ B j
  conj_B : ∀ j, ∀ a ∈ A, ∀ b ∈ B (j + 1), a⁻¹ * b * a ∈ B j
  B_sub : ∀ j, B j ⊆ A ^ 4
  cover : ∀ r j, ∃ F : Finset (UProd (G := G) U), (F : Set (UProd (G := G) U)) ⊆ A ^ r ∧
    A ^ r ⊆ (F : Set (UProd (G := G) U)) * B j

namespace TowerData

variable (T : TowerData U G)

/-! ### The subgroup generated by `A*` -/

/-- The subgroup `⋃ᵣ A*^r` generated by `A*`. -/
def Γ : Subgroup (UProd (G := G) U) where
  carrier := {g | ∃ r : ℕ, g ∈ T.A ^ r}
  one_mem' := ⟨0, by simp⟩
  mul_mem' := by
    rintro a b ⟨r, ha⟩ ⟨s, hb⟩
    exact ⟨r + s, by rw [pow_add]; exact Set.mul_mem_mul ha hb⟩
  inv_mem' := by
    rintro a ⟨r, ha⟩
    refine ⟨r, ?_⟩
    rw [← T.inv_A, inv_pow]
    exact Set.inv_mem_inv.2 ha

lemma mem_Γ {g : UProd (G := G) U} {r : ℕ} (h : g ∈ T.A ^ r) : g ∈ T.Γ := ⟨r, h⟩

lemma pow_subset_Γ (r : ℕ) : T.A ^ r ⊆ T.Γ := fun _ h => T.mem_Γ h

lemma B_subset_Γ (j : ℕ) : T.B j ⊆ T.Γ := (T.B_sub j).trans (T.pow_subset_Γ 4)

lemma pow_subset_pow {r s : ℕ} (h : r ≤ s) : T.A ^ r ⊆ T.A ^ s :=
  Set.pow_subset_pow_right T.one_mem_A h

lemma B_succ_subset (j : ℕ) : T.B (j + 1) ⊆ T.B j := fun b hb => by
  have := T.mul_B j (Set.mul_mem_mul hb (T.one_mem_B (j + 1)))
  simpa using this

lemma B_antitone {j j' : ℕ} (h : j ≤ j') : T.B j' ⊆ T.B j := by
  induction h with
  | refl => exact le_rfl
  | step _ ih => exact (T.B_succ_subset _).trans ih

lemma inv_mem_A {a : UProd (G := G) U} (ha : a ∈ T.A) : a⁻¹ ∈ T.A := by
  rw [← T.inv_A]; exact Set.inv_mem_inv.2 ha

lemma inv_mem_B {j : ℕ} {b : UProd (G := G) U} (hb : b ∈ T.B j) : b⁻¹ ∈ T.B j := by
  rw [← T.inv_B j]; exact Set.inv_mem_inv.2 hb

/-- Conjugating a deep scale by a word of length `r` lands `r` scales higher. -/
lemma conj_pow (r : ℕ) {x : UProd (G := G) U} (hx : x ∈ T.A ^ r) (j : ℕ)
    {b : UProd (G := G) U} (hb : b ∈ T.B (j + r)) : x * b * x⁻¹ ∈ T.B j := by
  induction r generalizing x b with
  | zero =>
    rw [pow_zero, Set.mem_one] at hx
    subst hx; simpa using hb
  | succ r ih =>
    rw [pow_succ] at hx
    obtain ⟨y, hy, a, ha, rfl⟩ := hx
    have h1 : a * b * a⁻¹ ∈ T.B (j + r) := by
      have := T.conj_B (j + r) a⁻¹ (T.inv_mem_A ha) b (by simpa [add_assoc] using hb)
      simpa using this
    have := ih hy h1
    simpa [mul_assoc] using this

/-! ### The group topology on `Γ` -/

/-- The sets `B j` form a group filter basis on `Γ`. -/
def basis : GroupFilterBasis T.Γ where
  sets := {V | ∃ j, V = Subtype.val ⁻¹' T.B j}
  nonempty := ⟨_, 0, rfl⟩
  inter_sets := by
    rintro _ _ ⟨i, rfl⟩ ⟨j, rfl⟩
    exact ⟨_, ⟨max i j, rfl⟩, fun g hg =>
      ⟨T.B_antitone (le_max_left i j) hg, T.B_antitone (le_max_right i j) hg⟩⟩
  one' := by rintro _ ⟨j, rfl⟩; exact T.one_mem_B j
  mul' := by
    rintro _ ⟨j, rfl⟩
    refine ⟨_, ⟨j + 1, rfl⟩, ?_⟩
    rintro _ ⟨a, ha, b, hb, rfl⟩
    exact T.mul_B j (Set.mul_mem_mul ha hb)
  inv' := by
    rintro _ ⟨j, rfl⟩
    exact ⟨_, ⟨j, rfl⟩, fun g hg => T.inv_mem_B hg⟩
  conj' := by
    rintro x₀ _ ⟨j, rfl⟩
    obtain ⟨r, hr⟩ := x₀.2
    exact ⟨_, ⟨j + r, rfl⟩, fun g hg => T.conj_pow r hr j hg⟩

instance topology : TopologicalSpace T.Γ := T.basis.topology

instance : IsTopologicalGroup T.Γ := T.basis.isTopologicalGroup

lemma nhds_one_basis :
    (𝓝 (1 : T.Γ)).HasBasis (fun _ : ℕ => True) (fun j => Subtype.val ⁻¹' T.B j) := by
  refine ⟨fun W => ?_⟩
  rw [T.basis.nhds_one_hasBasis.mem_iff]
  constructor
  · rintro ⟨_, ⟨j, rfl⟩, h⟩; exact ⟨j, trivial, h⟩
  · rintro ⟨j, -, h⟩; exact ⟨_, ⟨j, rfl⟩, h⟩

lemma nhds_basis (g : T.Γ) :
    (𝓝 g).HasBasis (fun _ : ℕ => True) (fun j => (fun y => g * y) '' (Subtype.val ⁻¹' T.B j)) := by
  refine ⟨fun W => ?_⟩
  rw [(T.basis.nhds_hasBasis g).mem_iff]
  constructor
  · rintro ⟨_, ⟨j, rfl⟩, h⟩; exact ⟨j, trivial, h⟩
  · rintro ⟨j, -, h⟩; exact ⟨_, ⟨j, rfl⟩, h⟩

lemma mem_nhds_one (j : ℕ) : Subtype.val ⁻¹' T.B j ∈ 𝓝 (1 : T.Γ) :=
  (T.nhds_one_basis).mem_of_mem trivial

instance : FirstCountableTopology T.Γ :=
  ⟨fun g => (T.nhds_basis g).isCountablyGenerated⟩

/-! ### The Hausdorff quotient `L` -/

/-- The closure of the identity in `Γ`. -/
def Z : Subgroup T.Γ := (⊥ : Subgroup T.Γ).topologicalClosure

instance : T.Z.Normal := Subgroup.is_normal_topologicalClosure _

instance Z_isClosed : IsClosed (T.Z : Set T.Γ) := Subgroup.isClosed_topologicalClosure _

/-- The locally compact model `L = Γ ⧸ Z`. -/
abbrev L : Type _ := T.Γ ⧸ T.Z

/-- The quotient map `π : Γ → L`. -/
def π : T.Γ →* T.L := QuotientGroup.mk' T.Z

lemma π_surjective : Function.Surjective T.π := QuotientGroup.mk'_surjective _

lemma continuous_π : Continuous T.π := continuous_quot_mk

lemma isOpenMap_π : IsOpenMap T.π := QuotientGroup.isOpenMap_coe

lemma Z_subset_B (j : ℕ) {z : T.Γ} (hz : z ∈ T.Z) : (z : UProd (G := G) U) ∈ T.B j := by
  have hz' : z ∈ closure ({1} : Set T.Γ) := by
    have : (z : T.Γ) ∈ ((⊥ : Subgroup T.Γ).topologicalClosure : Set T.Γ) := hz
    rwa [Subgroup.topologicalClosure_coe, Subgroup.coe_bot] at this
  obtain ⟨w, hw, hw1⟩ := mem_closure_iff_nhds.1 hz' _ ((T.nhds_basis z).mem_of_mem (i := j) trivial)
  obtain ⟨b, hb, rfl⟩ := hw
  rw [Set.mem_singleton_iff] at hw1
  have : z = b⁻¹ := eq_inv_of_mul_eq_one_left hw1
  rw [this]
  exact T.inv_mem_B hb

/-! ### Compactness from countable internal covers -/

/-- **Compactness of bounded internal sets.**  If `C` is internal and `C ⊆ A*^r`, then the set
of elements of `Γ` lying in `C` is compact.  The proof uses open covers and countable internal
covers directly. -/
theorem isCompact_of_internal {C : Set (UProd (G := G) U)} (hC : IsInternal U C) {r : ℕ}
    (hCr : C ⊆ T.A ^ r) : IsCompact {g : T.Γ | (g : UProd (G := G) U) ∈ C} := by
  classical
  rw [isCompact_iff_finite_subcover]
  intro ι Uo hUo hcov
  by_cases hne : Nonempty ι
  swap
  · refine ⟨∅, fun g hg => ?_⟩
    obtain ⟨i, -⟩ := Set.mem_iUnion.1 (hcov hg)
    exact (hne ⟨i⟩).elim
  choose F hFsub hFcov using fun j => T.cover r (j + 1)
  -- the qualifying translates `x B (j+1)`, `x ∈ F j`, lying in one member of the cover
  set qual : ℕ → UProd (G := G) U → Prop := fun j x =>
    ∃ i, ∀ g : T.Γ, (g : UProd (G := G) U) ∈ {x} * T.B (j + 1) → g ∈ Uo i with hqual
  set D : ℕ → Set (UProd (G := G) U) := fun j =>
    ⋃ x ∈ (F j).filter (qual j), {x} * T.B (j + 1) with hD
  have hDint : ∀ j, IsInternal U (D j) := fun j =>
    IsInternal.biUnion _ fun x _ => (T.B_int _).translate x
  have hCD : C ⊆ ⋃ j, D j := by
    intro c hc
    have hcΓ : c ∈ T.Γ := T.mem_Γ (hCr hc)
    obtain ⟨i, hi⟩ := Set.mem_iUnion.1
      (hcov (show (⟨c, hcΓ⟩ : T.Γ) ∈ {g : T.Γ | (g : UProd (G := G) U) ∈ C} from hc))
    obtain ⟨j, -, hj⟩ := (T.nhds_basis ⟨c, hcΓ⟩).mem_iff.1 ((hUo i).mem_nhds hi)
    obtain ⟨x, hxF, b, hb, hxb⟩ := hFcov j (hCr hc)
    refine Set.mem_iUnion.2 ⟨j, Set.mem_biUnion (Finset.mem_filter.2 ⟨hxF, i, ?_⟩)
      ⟨x, rfl, b, hb, hxb⟩⟩
    rintro g ⟨_, rfl, b', hb', hg⟩
    apply hj
    have hmem : c⁻¹ * (g : UProd (G := G) U) ∈ T.B j := by
      have e : c⁻¹ * (g : UProd (G := G) U) = b⁻¹ * b' := by
        rw [← hxb, ← hg]; group
      rw [e]
      exact T.mul_B j (Set.mul_mem_mul (T.inv_mem_B hb) hb')
    refine ⟨⟨c⁻¹ * g, T.Γ.mul_mem (T.Γ.inv_mem hcΓ) g.2⟩, hmem, ?_⟩
    apply Subtype.ext
    simp
  obtain ⟨J, hJ⟩ := internal_subset_finite_subcover T.nonprincipal hC hDint hCD
  choose! idx hidx using fun j x (h : qual j x) => h
  refine ⟨(Finset.range J).biUnion fun j => ((F j).filter (qual j)).image (idx j), ?_⟩
  intro g hg
  obtain ⟨j, hjJ, hgj⟩ := Set.mem_iUnion₂.1 (hJ hg)
  obtain ⟨x, hx, hgx⟩ := Set.mem_iUnion₂.1 hgj
  refine Set.mem_iUnion₂.2 ⟨idx j x, Finset.mem_biUnion.2 ⟨j, hjJ,
    Finset.mem_image.2 ⟨x, hx, rfl⟩⟩, hidx j x (Finset.mem_filter.1 hx).2 g hgx⟩

theorem isCompact_image_of_internal {C : Set (UProd (G := G) U)} (hC : IsInternal U C) {r : ℕ}
    (hCr : C ⊆ T.A ^ r) : IsCompact (T.π '' {g : T.Γ | (g : UProd (G := G) U) ∈ C}) :=
  (T.isCompact_of_internal hC hCr).image T.continuous_π

instance : LocallyCompactSpace T.L := by
  have hK := T.isCompact_image_of_internal (T.B_int 0) (T.B_sub 0)
  have hmem : T.π '' {g : T.Γ | (g : UProd (G := G) U) ∈ T.B 0} ∈ 𝓝 (1 : T.L) := by
    have := T.isOpenMap_π.image_mem_nhds (T.mem_nhds_one 0)
    rwa [map_one] at this
  exact hK.locallyCompactSpace_of_mem_nhds_of_group hmem

/-! ### The full-fibre sandwich -/

/-- **Full-fibre sandwich.**  For a compact `F` and an open `O ⊇ F` in `L` there is a bounded
internal set `D` with `π⁻¹(F) ⊆ D ⊆ π⁻¹(O)`. -/
theorem sandwich {F O : Set T.L} (hF : IsCompact F) (hO : IsOpen O) (hFO : F ⊆ O) :
    ∃ D : Set (UProd (G := G) U), IsInternal U D ∧ (∃ q : ℕ, D ⊆ T.A ^ q) ∧
      (∀ g : T.Γ, T.π g ∈ F → (g : UProd (G := G) U) ∈ D) ∧
      (∀ g : T.Γ, (g : UProd (G := G) U) ∈ D → T.π g ∈ O) := by
  classical
  have hch : ∀ y : T.L, ∃ g : T.Γ, ∃ j : ℕ, T.π g = y ∧
      (y ∈ O → ∀ b : T.Γ, (b : UProd (G := G) U) ∈ T.B j → T.π (g * b) ∈ O) := by
    intro y
    obtain ⟨g, rfl⟩ := T.π_surjective y
    by_cases hy : T.π g ∈ O
    · have : T.π ⁻¹' O ∈ 𝓝 g := (hO.preimage T.continuous_π).mem_nhds hy
      obtain ⟨j, -, hj⟩ := (T.nhds_basis g).mem_iff.1 this
      exact ⟨g, j, rfl, fun _ b hb => hj ⟨b, hb, rfl⟩⟩
    · exact ⟨g, 0, rfl, fun h => absurd h hy⟩
  choose g j hgy hgO using hch
  choose r hr using fun y => (g y).2
  set W : T.L → Set T.L := fun y =>
    T.π '' ((fun z => g y * z) '' (Subtype.val ⁻¹' T.B (j y + 1))) with hWdef
  have hW : ∀ y ∈ F, W y ∈ 𝓝 y := by
    intro y _
    have h1 : (fun z => g y * z) '' (Subtype.val ⁻¹' T.B (j y + 1)) ∈ 𝓝 (g y) :=
      (T.nhds_basis (g y)).mem_of_mem trivial
    have := T.isOpenMap_π.image_mem_nhds h1
    rwa [hgy] at this
  obtain ⟨t, htF, hFt⟩ := hF.elim_nhds_subcover W hW
  refine ⟨⋃ y ∈ t, {(g y : UProd (G := G) U)} * T.B (j y),
    IsInternal.biUnion _ fun y _ => (T.B_int _).translate _, ⟨t.sup r + 4, ?_⟩, ?_, ?_⟩
  · intro x hx
    obtain ⟨y, hyt, _, rfl, b, hb, rfl⟩ := Set.mem_iUnion₂.1 hx
    rw [pow_add]
    exact Set.mul_mem_mul (T.pow_subset_pow (Finset.le_sup hyt) (hr y)) (T.B_sub _ hb)
  · intro h hh
    obtain ⟨y, hyt, hy⟩ := Set.mem_iUnion₂.1 (hFt hh)
    obtain ⟨_, ⟨b, hb, rfl⟩, hπ⟩ := hy
    obtain ⟨z, hz, hzh⟩ := (QuotientGroup.mk'_eq_mk' T.Z).1 hπ
    refine Set.mem_iUnion₂.2 ⟨y, hyt, g y, rfl, (b : UProd (G := G) U) * z,
      T.mul_B _ (Set.mul_mem_mul hb (T.Z_subset_B _ hz)), ?_⟩
    rw [← hzh]; simp [mul_assoc]
  · intro h hh
    obtain ⟨y, hyt, _, rfl, b', hb', hgb⟩ := Set.mem_iUnion₂.1 hh
    have hyO : y ∈ O := hFO (htF y hyt)
    have := hgO y hyO ⟨b', T.B_subset_Γ _ hb'⟩ hb'
    have e : h = g y * ⟨b', T.B_subset_Γ _ hb'⟩ := Subtype.ext hgb.symm
    rw [e]; exact this

/-- The symmetric sandwich: for symmetric compact `F ⊆ O` open, the internal set can be chosen
symmetric. -/
theorem sandwich_symm {F O : Set T.L} (hF : IsCompact F) (hO : IsOpen O) (hFO : F ⊆ O)
    (hFinv : F⁻¹ = F) :
    ∃ D : Set (UProd (G := G) U), IsInternal U D ∧ D⁻¹ = D ∧ (∃ q : ℕ, D ⊆ T.A ^ q) ∧
      (∀ g : T.Γ, T.π g ∈ F → (g : UProd (G := G) U) ∈ D) ∧
      (∀ g : T.Γ, (g : UProd (G := G) U) ∈ D → T.π g ∈ O) := by
  obtain ⟨D, hD, ⟨q, hq⟩, hlow, hup⟩ := T.sandwich hF hO hFO
  refine ⟨D ∩ D⁻¹, hD.inter hD.inv, by rw [Set.inter_inv, inv_inv, Set.inter_comm],
    ⟨q, Set.inter_subset_left.trans hq⟩, fun g hg => ⟨hlow g hg, ?_⟩,
    fun g hg => hup g hg.1⟩
  have : T.π g⁻¹ ∈ F := by
    rw [map_inv, ← hFinv]; exact Set.inv_mem_inv.2 hg
  have := hlow _ this
  rw [Set.mem_inv]; simpa using this

/-- Every identity neighbourhood of `L` contains the image of some scale `B j`. -/
lemma exists_B_subset_preimage {W : Set T.L} (hW : W ∈ 𝓝 (1 : T.L)) :
    ∃ j, ∀ g : T.Γ, (g : UProd (G := G) U) ∈ T.B j → T.π g ∈ W := by
  have : T.π ⁻¹' W ∈ 𝓝 (1 : T.Γ) :=
    T.continuous_π.continuousAt.preimage_mem_nhds (by rwa [map_one])
  obtain ⟨j, -, hj⟩ := T.nhds_one_basis.mem_iff.1 this
  exact ⟨j, fun g hg => hj hg⟩

end TowerData

end Lovasz.UltraModel
